// src/themes/dashboardStyles.js
const injectGlobalStyles = () => {
  if (typeof document !== 'undefined' && !document.getElementById('lux-editorial')) {
    const style = document.createElement('style');
    style.id = 'lux-editorial';
    style.innerHTML = `
      * {
        scrollbar-width: none;
      }
      *::-webkit-scrollbar {
        display: none;
      }
      body {
        background-color: #f8fafc;
        margin: 0;
      }
    `;
    document.head.appendChild(style);
  }
};
injectGlobalStyles();

const champagne = "#15803d";
const champagneDim = "#f0fdf4";
const sansFont = "Inter, Arial, sans-serif";

const glassPanel = {
  backgroundColor: "#ffffff",
  border: "1px solid #e2e8f0",
  boxShadow: "0 1px 2px rgba(0, 0, 0, 0.03)",
  borderRadius: "8px",
};

export const dashboardStyles = {
  shell: {
    display: "flex",
    height: "100vh",
    background: "#f8fafc",
    color: "#0f172a",
    fontFamily: sansFont,
    overflow: "hidden",
  },
  main: {
    flex: 1,
    padding: "16px 24px",
    marginLeft: "216px",
    height: "100vh",
    display: "flex",
    flexDirection: "column",
    gap: "16px",
    overflowX: "hidden",
    overflowY: "auto",
    paddingBottom: "28px",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-end",
    paddingBottom: "12px",
    borderBottom: "1px solid #e2e8f0",
    flexShrink: 0,
  },
  title: {
    fontFamily: sansFont,
    fontSize: "20px",
    fontWeight: "600",
    color: "#0f172a",
    margin: 0,
    letterSpacing: "-0.02em",
    lineHeight: 1.2,
  },
  liveTag: {
    backgroundColor: "#f0fdf4",
    color: "#15803d",
    fontSize: "10px",
    fontWeight: "600",
    padding: "3px 8px",
    borderRadius: "6px",
    letterSpacing: "0.04em",
    textTransform: "uppercase",
    border: "1px solid #dcfce7",
    marginLeft: "10px",
    verticalAlign: "middle",
  },
  subtitle: {
    fontSize: "13px",
    margin: "4px 0 0 0",
    fontWeight: "400",
    color: "#64748b",
    textTransform: "none",
    letterSpacing: "0",
  },
  statusBadge: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    backgroundColor: "#ffffff",
    border: "1px solid #e2e8f0",
    padding: "6px 12px",
    borderRadius: "6px",
    fontSize: "11px",
    fontWeight: "600",
    color: "#15803d",
    letterSpacing: "0.02em",
    textTransform: "uppercase",
  },
  statusDot: {
    width: "6px",
    height: "6px",
    borderRadius: "50%",
    backgroundColor: "#15803d",
  },
  soundBtnActive: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    backgroundColor: "#15803d",
    border: "none",
    color: "#ffffff",
    padding: "6px 12px",
    borderRadius: "6px",
    fontSize: "11px",
    fontWeight: "600",
    cursor: "pointer",
    letterSpacing: "0.02em",
    textTransform: "uppercase",
    transition: "background-color 0.15s ease",
  },
  soundBtnMuted: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    backgroundColor: "#ffffff",
    border: "1px solid #e2e8f0",
    color: "#64748b",
    padding: "6px 12px",
    borderRadius: "6px",
    fontSize: "11px",
    fontWeight: "500",
    cursor: "pointer",
    letterSpacing: "0.02em",
    textTransform: "uppercase",
    transition: "all 0.15s ease",
  },
  cardGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(5, 1fr)",
    gap: "12px",
    flexShrink: 0,
  },
  masterGrid: {
    display: "grid",
    gridTemplateColumns: "minmax(340px, 0.85fr) minmax(0, 2fr)",
    gridTemplateRows: "minmax(0, 1fr) minmax(150px, 0.7fr)",
    gap: "14px",
    flex: "0 0 auto",
    height: "clamp(520px, calc(100vh - 220px), 760px)",
    minHeight: 0,
  },
  gridCol: {
    display: "flex",
    flexDirection: "column",
    gap: "14px",
    minHeight: 0,
  },
  rightGridCol: {
    display: "flex",
    flexDirection: "column",
    gap: "14px",
    minHeight: 0,
    gridColumn: "1",
    gridRow: "2",
  },
  panelFlex: {
    ...glassPanel,
    display: "flex",
    flexDirection: "column",
    padding: "16px",
    flex: 1,
    minHeight: 0,
    overflow: "hidden",
  },
  panelFixed: {
    ...glassPanel,
    padding: "16px",
    flexShrink: 0,
  },
  mapPanel: {
    ...glassPanel,
    gridColumn: "2",
    gridRow: "1 / span 2",
    display: "flex",
    flexDirection: "column",
    padding: "16px",
    minHeight: 0,
    overflow: "hidden",
  },
  sosPanel: {
    backgroundColor: "#ffffff",
    border: "1px solid #fecaca",
    boxShadow: "0 1px 2px rgba(0, 0, 0, 0.03)",
    borderRadius: "8px",
    padding: "16px",
    flexShrink: 0,
    display: "flex",
    flexDirection: "column",
    maxHeight: "180px",
  },
  sosHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "10px",
    flexShrink: 0,
  },
  sosHeading: {
    fontFamily: sansFont,
    fontSize: "13px",
    fontWeight: "600",
    color: "#b91c1c",
    margin: 0,
    display: "flex",
    alignItems: "center",
    gap: "6px",
  },
  sosViewBtn: {
    background: "#fef2f2",
    border: "1px solid #fee2e2",
    color: "#b91c1c",
    fontWeight: "600",
    fontSize: "10px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: "4px",
    padding: "3px 8px",
    borderRadius: "4px",
    textTransform: "uppercase",
    letterSpacing: "0.02em",
  },
  panelHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "10px",
    flexShrink: 0,
  },
  sectionTitle: {
    fontFamily: sansFont,
    fontSize: "13px",
    fontWeight: "600",
    color: "#0f172a",
    margin: 0,
    display: "flex",
    alignItems: "center",
    gap: "6px",
  },
  ghostBtn: {
    background: "transparent",
    border: "none",
    color: "#15803d",
    fontSize: "11px",
    fontWeight: "600",
    cursor: "pointer",
    padding: "3px 6px",
    letterSpacing: "0.02em",
  },
  emptyState: {
    color: "#94a3b8",
    fontSize: "11px",
    textAlign: "center",
    margin: "24px 0",
    fontWeight: "500",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
  },
  thRow: {},
  th: {
    textAlign: "left",
    padding: "6px 8px",
    fontSize: "10px",
    fontWeight: "600",
    color: "#64748b",
    letterSpacing: "0.04em",
    textTransform: "uppercase",
    borderBottom: "1px solid #e2e8f0",
  },
  thRight: {
    textAlign: "right",
    padding: "6px 8px",
    fontSize: "10px",
    fontWeight: "600",
    color: "#64748b",
    letterSpacing: "0.04em",
    textTransform: "uppercase",
    borderBottom: "1px solid #e2e8f0",
  },
  tr: {
    backgroundColor: "transparent",
    borderBottom: "1px solid #f1f5f9",
  },
  td: {
    padding: "7px 8px",
    verticalAlign: "middle",
    color: "#334155",
    fontWeight: "400",
    fontSize: "12px",
  },
  tdBold: {
    padding: "7px 8px",
    fontSize: "12px",
    fontWeight: "600",
    color: "#0f172a",
  },
  tdMuted: {
    padding: "7px 8px",
    fontSize: "11px",
    color: "#64748b",
    fontWeight: "400",
  },
  tdHighlight: {
    padding: "7px 8px",
    fontSize: "12px",
    fontWeight: "500",
    color: "#15803d",
  },
  tdRight: {
    padding: "7px 8px",
    textAlign: "right",
  },
  sosBadge: {
    backgroundColor: "#fef2f2",
    color: "#b91c1c",
    fontSize: "10px",
    fontWeight: "600",
    padding: "2px 6px",
    borderRadius: "4px",
    border: "1px solid #fee2e2",
  },
  sosActionBtn: {
    background: "#b91c1c",
    color: "#ffffff",
    border: "none",
    padding: "4px 10px",
    borderRadius: "4px",
    fontSize: "10px",
    fontWeight: "600",
    cursor: "pointer",
  },
  dispatchBtn: {
    background: "#f0fdf4",
    color: "#15803d",
    border: "1px solid #dcfce7",
    padding: "4px 10px",
    borderRadius: "4px",
    fontSize: "10px",
    fontWeight: "600",
    cursor: "pointer",
  },
  typeTag: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
  },
  inlineIcon: {
    verticalAlign: "middle",
    color: "#15803d",
  },
  subBadge: {
    backgroundColor: "#f8fafc",
    color: "#64748b",
    fontSize: "10px",
    fontWeight: "500",
    border: "1px solid #e2e8f0",
    padding: "2px 6px",
    borderRadius: "4px",
  },
  subBadgeBlue: {
    backgroundColor: "#f0fdf4",
    color: "#15803d",
    fontSize: "10px",
    fontWeight: "600",
    border: "1px solid #dcfce7",
    padding: "2px 6px",
    borderRadius: "4px",
  },
  categoryList: {
    display: "flex",
    flexDirection: "column",
    gap: "1px",
    backgroundColor: "#f1f5f9",
    borderRadius: "6px",
    overflow: "hidden",
    border: "1px solid #e2e8f0",
  },
  categoryRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#ffffff",
    padding: "8px 12px",
  },
  categoryCountBadge: {
    color: "#0f172a",
    fontSize: "13px",
    fontFamily: sansFont,
    fontWeight: "600",
  },
  fleetSubtext: {
    color: "#64748b",
    fontSize: "11px",
    margin: 0,
    lineHeight: "1.4",
    fontWeight: "400",
  },
  auditList: {
    listStyle: "none",
    padding: 0,
    margin: 0,
    display: "flex",
    flexDirection: "column",
    gap: "1px",
    backgroundColor: "#f1f5f9",
    borderRadius: "6px",
    overflow: "auto",
    flex: 1,
    border: "1px solid #e2e8f0",
  },
  auditItem: {
    display: "flex",
    gap: "8px",
    backgroundColor: "#ffffff",
    padding: "8px 10px",
  },
  auditContent: {
    flex: 1,
  },
  auditText: {
    margin: 0,
    color: "#334155",
    fontWeight: "400",
    lineHeight: "1.4",
    fontSize: "11px",
  },
  auditTime: {
    color: "#94a3b8",
    fontSize: "10px",
    fontWeight: "500",
    marginTop: "2px",
    display: "block",
  },
  mapOverlayPosition: {
    position: "absolute",
    top: "12px",
    right: "12px",
    zIndex: 1000,
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    width: "clamp(200px, 18vw, 50px)",
    maxWidth: "calc(100% - 24px)",
  },
  mapStatusPanel: {
    width: "100%",
    minHeight: "100px",
    maxHeight: "min(260px, 50vh)",
    overflowY: "auto",
    padding: "12px",
    boxSizing: "border-box",
    backgroundColor: "rgba(255, 255, 255, 0.96)",
    border: "1px solid #e2e8f0",
    borderRadius: "8px",
    boxShadow: "0 4px 12px rgba(0, 0, 0, 0.05)",
  },
  mapStatusHeader: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    marginBottom: "8px",
  },
  mapStatusHeaderButton: {
    width: "100%",
    padding: 0,
    border: "none",
    backgroundColor: "transparent",
    cursor: "pointer",
    textAlign: "left",
  },
  mapStatusDot: {
    width: "8px",
    height: "8px",
    flexShrink: 0,
    borderRadius: "50%",
    backgroundColor: "#ef4444",
  },
  mapStatusTitle: {
    color: "#0f172a",
    fontSize: "12px",
    fontWeight: "600",
  },
  mapStatusDivider: {
    width: "100%",
    height: "1px",
    backgroundColor: "#f1f5f9",
  },
  mapStatusLabel: {
    marginTop: "8px",
    marginBottom: "4px",
    color: "#64748b",
    fontSize: "10px",
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: "0.04em",
  },
  mapStatusItem: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    minHeight: "24px",
    color: "#334155",
  },
  mapStatusTypeDot: {
    width: "8px",
    height: "8px",
    flexShrink: 0,
    borderRadius: "50%",
  },
  mapStatusType: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: "11px",
    textTransform: "capitalize",
  },
  mapStatusEmpty: {
    color: "#94a3b8",
    fontSize: "11px",
    lineHeight: "1.4",
  },
  mapStatusCollapsed: {
    width: "36px",
    height: "36px",
    alignSelf: "flex-end",
    padding: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    border: "1px solid #e2e8f0",
    borderRadius: "6px",
    backgroundColor: "#ffffff",
    boxShadow: "0 2px 8px rgba(0, 0, 0, 0.05)",
    cursor: "pointer",
  },
};
export const darkStyles = dashboardStyles;
