// src/dashboardStyles.js

export const dashboardStyles = {
  shell: {
    display: "flex",
    minHeight: "100vh",
    backgroundColor: "#0b0f19",
    color: "#f8fafc",
    fontFamily: "'Inter', sans-serif",
  },
  main: {
    flex: 1,
    padding: "32px",
    marginLeft: "260px",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "28px",
    paddingBottom: "20px",
    borderBottom: "1px solid #1e293b",
  },
  title: {
    fontSize: "28px",
    fontWeight: "900",
    letterSpacing: "-0.5px",
    color: "#ffffff",
    margin: 0,
  },
  liveTag: {
    backgroundColor: "#ef4444",
    color: "#ffffff",
    fontSize: "10px",
    fontWeight: "800",
    padding: "2px 8px",
    borderRadius: "6px",
    letterSpacing: "0.5px",
    textTransform: "uppercase",
  },
  subtitle: {
    color: "#94a3b8",
    fontSize: "14px",
    margin: "6px 0 0 0",
    fontWeight: "500",
  },
  statusBadge: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    backgroundColor: "#1e293b",
    border: "1px solid #334155",
    padding: "6px 14px",
    borderRadius: "20px",
    fontSize: "12px",
    fontWeight: "800",
    color: "#34d399",
  },
  statusDot: {
    width: "8px",
    height: "8px",
    borderRadius: "50%",
    backgroundColor: "#34d399",
    boxShadow: "0 0 8px #34d399",
  },
  soundBtnActive: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    backgroundColor: "#1e293b",
    border: "1px solid #ef4444",
    color: "#f8fafc",
    padding: "6px 14px",
    borderRadius: "20px",
    fontSize: "12px",
    fontWeight: "800",
    cursor: "pointer",
  },
  soundBtnMuted: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    backgroundColor: "#1e293b",
    border: "1px solid #334155",
    color: "#94a3b8",
    padding: "6px 14px",
    borderRadius: "20px",
    fontSize: "12px",
    fontWeight: "800",
    cursor: "pointer",
  },
  cardGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))",
    gap: "16px",
    marginBottom: "28px",
  },
  sosPanel: {
    backgroundColor: "rgba(239, 68, 68, 0.08)",
    border: "1px solid #ef4444",
    borderRadius: "20px",
    padding: "20px",
    marginBottom: "28px",
  },
  sosHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "16px",
  },
  sosHeading: {
    fontSize: "14px",
    fontWeight: "900",
    color: "#ef4444",
    letterSpacing: "0.5px",
    margin: 0,
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  sosViewBtn: {
    background: "none",
    border: "none",
    color: "#ef4444",
    fontWeight: "800",
    fontSize: "12px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: "4px",
  },
  splitGrid: {
    display: "grid",
    gridTemplateColumns: "2fr 1fr",
    gap: "24px",
  },
  panel: {
    backgroundColor: "#1e293b",
    border: "1px solid #334155",
    borderRadius: "20px",
    padding: "20px",
  },
  panelHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "16px",
  },
  sectionTitle: {
    fontSize: "16px",
    fontWeight: "800",
    color: "#f8fafc",
    margin: 0,
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  ghostBtn: {
    background: "none",
    border: "none",
    color: "#94a3b8",
    fontSize: "12px",
    fontWeight: "700",
    cursor: "pointer",
  },
  emptyState: {
    color: "#94a3b8",
    fontSize: "13px",
    textAlign: "center",
    margin: "20px 0",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
  },
  thRow: {
    borderBottom: "1px solid #334155",
  },
  th: {
    textAlign: "left",
    padding: "10px 12px",
    fontSize: "11px",
    fontWeight: "800",
    color: "#94a3b8",
    letterSpacing: "0.5px",
  },
  thRight: {
    textAlign: "right",
    padding: "10px 12px",
    fontSize: "11px",
    fontWeight: "800",
    color: "#94a3b8",
    letterSpacing: "0.5px",
  },
  tr: {
    borderBottom: "1px solid rgba(255, 255, 255, 0.05)",
  },
  td: {
    padding: "12px",
    fontSize: "13px",
    color: "#cbd5e1",
  },
  tdBold: {
    padding: "12px",
    fontSize: "13px",
    fontWeight: "700",
    color: "#f8fafc",
  },
  tdMuted: {
    padding: "12px",
    fontSize: "12px",
    color: "#94a3b8",
  },
  tdHighlight: {
    padding: "12px",
    fontSize: "13px",
    fontWeight: "700",
    color: "#f59e0b",
  },
  tdRight: {
    padding: "12px",
    textAlign: "right",
  },
  sosBadge: {
    backgroundColor: "#ef4444",
    color: "white",
    fontSize: "10px",
    fontWeight: "800",
    padding: "2px 6px",
    borderRadius: "4px",
  },
  sosActionBtn: {
    backgroundColor: "#ef4444",
    color: "white",
    border: "none",
    padding: "6px 12px",
    borderRadius: "8px",
    fontSize: "12px",
    fontWeight: "800",
    cursor: "pointer",
  },
  dispatchBtn: {
    backgroundColor: "#f59e0b",
    color: "#0f172a",
    border: "none",
    padding: "6px 12px",
    borderRadius: "8px",
    fontSize: "12px",
    fontWeight: "800",
    cursor: "pointer",
  },
  typeTag: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
  },
  inlineIcon: {
    verticalAlign: "middle",
    marginRight: "4px",
  },
  rightColumnStack: {
    display: "flex",
    flexDirection: "column",
    gap: "24px",
  },
  subBadge: {
    backgroundColor: "rgba(168, 85, 247, 0.15)",
    color: "#c084fc",
    border: "1px solid rgba(168, 85, 247, 0.3)",
    fontSize: "11px",
    fontWeight: "800",
    padding: "2px 8px",
    borderRadius: "12px",
  },
  subBadgeBlue: {
    backgroundColor: "rgba(56, 189, 248, 0.15)",
    color: "#38bdf8",
    border: "1px solid rgba(56, 189, 248, 0.3)",
    fontSize: "11px",
    fontWeight: "800",
    padding: "2px 8px",
    borderRadius: "12px",
  },
  categoryList: {
    display: "flex",
    flexDirection: "column",
    gap: "10px",
  },
  categoryRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#0f172a",
    padding: "10px 14px",
    borderRadius: "10px",
    border: "1px solid #334155",
  },
  categoryCountBadge: {
    backgroundColor: "#1e293b",
    color: "#f8fafc",
    fontSize: "12px",
    fontWeight: "800",
    padding: "2px 8px",
    borderRadius: "6px",
    border: "1px solid #334155",
  },
  fleetSubtext: {
    color: "#94a3b8",
    fontSize: "13px",
    margin: 0,
    lineHeight: "1.5",
  },
  auditList: {
    listStyle: "none",
    padding: 0,
    margin: 0,
    display: "flex",
    flexDirection: "column",
    gap: "12px",
  },
  auditItem: {
    display: "flex",
    gap: "10px",
    fontSize: "12px",
  },
  auditContent: {
    flex: 1,
  },
  auditText: {
    margin: 0,
    color: "#cbd5e1",
    fontWeight: "600",
  },
  auditTime: {
    color: "#94a3b8",
    fontSize: "10px",
    fontWeight: "700",
  },
};

// Backwards compatibility alias
export const darkStyles = dashboardStyles;
