// src/themes/dashboardStyles.js
const injectGlobalStyles = () => {
  if (typeof document !== 'undefined' && !document.getElementById('lux-editorial')) {
    const style = document.createElement('style');
    style.id = 'lux-editorial';
    style.innerHTML = `
      @keyframes gradientPulse {
        0% { background-position: 0% 50%; }
        50% { background-position: 100% 50%; }
        100% { background-position: 0% 50%; }
      }
      @keyframes floatGlow {
        0% { box-shadow: 0 20px 40px rgba(0,0,0,0.5), inset 0 0 0 1px rgba(255,255,255,0.02); transform: translateY(0); }
        50% { box-shadow: 0 30px 60px rgba(212,175,55,0.05), inset 0 0 0 1px rgba(212,175,55,0.1); transform: translateY(-4px); }
        100% { box-shadow: 0 20px 40px rgba(0,0,0,0.5), inset 0 0 0 1px rgba(255,255,255,0.02); transform: translateY(0); }
      }
      * {
        scrollbar-width: none;
      }
      *::-webkit-scrollbar {
        display: none;
      }
      body {
        background-color: #f6faf7;
        margin: 0;
      }
      .lux-hover:hover {
        transform: translateY(-6px);
        box-shadow: 0 12px 28px rgba(24, 95, 53, 0.12), inset 0 0 0 1px rgba(24, 134, 75, 0.16) !important;
        background-color: #ffffff !important;
      }
    `;
    document.head.appendChild(style);
  }
};
injectGlobalStyles();

const champagne = "#18864b";
const champagneDim = "#e7f5eb";
const midnightSlate = "#111111";
const editorialFont = "Inter, Arial, sans-serif";
const sansFont = "Inter, Arial, sans-serif";

const glassPanel = {
  backgroundColor: "#ffffff",
  border: "1px solid #d7e5da",
  boxShadow: "0 8px 24px rgba(24, 95, 53, 0.06)",
  borderRadius: "12px",
};

export const dashboardStyles = {
  shell: {
    display: "flex",
    height: "100vh",
    background: "radial-gradient(circle at 50% -20%, #ffffff 0%, #f6faf7 80%)",
    color: "#111111",
    fontFamily: sansFont,
    overflow: "hidden",
  },
  main: {
    flex: 1,
    padding: "16px 24px",
    marginLeft: "216px",
    height: "100vh",
    display: "flex",
    flexDirection: "column",
    gap: "20px",
    overflowX: "hidden",
    overflowY: "auto",
    paddingBottom: "28px",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-end",
    paddingBottom: "12px",
    borderBottom: "1px solid #d7e5da",
    flexShrink: 0,
  },
  title: {
    fontFamily: editorialFont,
    fontSize: "clamp(24px, 3vw, 32px)",
    fontWeight: "800",
    color: "#111111",
    margin: 0,
    letterSpacing: "-0.5px",
    lineHeight: 1,
  },
  liveTag: {
    backgroundColor: champagneDim,
    color: champagne,
    fontSize: "9px",
    fontWeight: "600",
    padding: "4px 8px",
    borderRadius: "99px",
    letterSpacing: "2px",
    textTransform: "uppercase",
    border: "1px solid #b8d7c1",
    marginLeft: "12px",
    verticalAlign: "middle",
  },
  subtitle: {
    fontSize: "9px",
    margin: "6px 0 0 0",
    fontWeight: "600",
    color: "#477257",
    textTransform: "none",
    letterSpacing: "0.3px",
  },
  statusBadge: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    backgroundColor: "transparent",
    border: "1px solid #b8d7c1",
    padding: "8px 16px",
    borderRadius: "99px",
    fontSize: "9px",
    fontWeight: "600",
    color: champagne,
    letterSpacing: "2px",
    textTransform: "uppercase",
  },
  statusDot: {
    width: "6px",
    height: "6px",
    borderRadius: "50%",
    backgroundColor: champagne,
    boxShadow: `0 0 10px ${champagne}`,
  },
  soundBtnActive: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    backgroundColor: champagne,
    border: "none",
    color: "#000000",
    padding: "8px 16px",
    borderRadius: "99px",
    fontSize: "9px",
    fontWeight: "700",
    cursor: "pointer",
    letterSpacing: "2px",
    textTransform: "uppercase",
    transition: "all 0.4s ease",
  },
  soundBtnMuted: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    backgroundColor: "transparent",
    border: "1px solid rgba(255, 255, 255, 0.1)",
    color: "#71717a",
    padding: "8px 16px",
    borderRadius: "99px",
    fontSize: "9px",
    fontWeight: "600",
    cursor: "pointer",
    letterSpacing: "2px",
    textTransform: "uppercase",
    transition: "all 0.4s ease",
  },
  cardGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(5, 1fr)",
    gap: "10px",
    flexShrink: 0,
  },
  masterGrid: {
    display: "grid",
    gridTemplateColumns: "minmax(340px, 0.85fr) minmax(0, 2fr)",
    gridTemplateRows: "minmax(0, 1fr) minmax(150px, 0.7fr)",
    gap: "16px",
    flex: "0 0 auto",
    height: "clamp(520px, calc(100vh - 220px), 760px)",
    minHeight: 0,
  },
  gridCol: {
    display: "flex",
    flexDirection: "column",
    gap: "16px",
    minHeight: 0,
  },
  rightGridCol: {
    display: "flex",
    flexDirection: "column",
    gap: "16px",
    minHeight: 0,
    gridColumn: "1",
    gridRow: "2",
  },
  panelFlex: {
    ...glassPanel,
    display: "flex",
    flexDirection: "column",
    padding: "16px",
    flex: 1,
    minHeight: 0,
    overflow: "hidden",
  },
  panelFixed: {
    ...glassPanel,
    padding: "16px",
    flexShrink: 0,
  },
  mapPanel: {
    ...glassPanel,
    gridColumn: "2",
    gridRow: "1 / span 2",
    display: "flex",
    flexDirection: "column",
    padding: "16px",
    minHeight: 0,
    overflow: "hidden",
  },
  sosPanel: {
    backgroundColor: "#fff7f7",
    border: "1px solid #f3d3d3",
    boxShadow: "0 8px 24px rgba(95, 24, 24, 0.06)",
    borderRadius: "12px",
    padding: "16px",
    flexShrink: 0,
    display: "flex",
    flexDirection: "column",
    maxHeight: "180px",
  },
  sosHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "12px",
    flexShrink: 0,
  },
  sosHeading: {
    fontFamily: editorialFont,
    fontSize: "14px",
    fontWeight: "400",
    color: "#ef4444",
    margin: 0,
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  sosViewBtn: {
    background: "transparent",
    border: "1px solid rgba(239, 68, 68, 0.3)",
    color: "#ef4444",
    fontWeight: "600",
    fontSize: "8px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: "4px",
    padding: "4px 8px",
    borderRadius: "99px",
    letterSpacing: "2px",
    textTransform: "uppercase",
  },
  panelHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "12px",
    flexShrink: 0,
  },
  sectionTitle: {
    fontFamily: editorialFont,
    fontSize: "14px",
    fontWeight: "400",
    color: "#111111",
    margin: 0,
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  ghostBtn: {
    background: "transparent",
    border: "none",
    color: "#18864b",
    fontSize: "8px",
    fontWeight: "600",
    cursor: "pointer",
    padding: "4px 8px",
    letterSpacing: "2px",
    textTransform: "uppercase",
  },
  emptyState: {
    color: "#477257",
    fontSize: "10px",
    textAlign: "center",
    margin: "32px 0",
    fontWeight: "500",
    letterSpacing: "1px",
    textTransform: "uppercase",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
  },
  thRow: {},
  th: {
    textAlign: "left",
    padding: "6px",
    fontSize: "8px",
    fontWeight: "700",
    color: "#477257",
    letterSpacing: "1px",
    textTransform: "uppercase",
    borderBottom: "1px solid #d7e5da",
  },
  thRight: {
    textAlign: "right",
    padding: "6px",
    fontSize: "8px",
    fontWeight: "600",
    color: "#52525b",
    letterSpacing: "1px",
    textTransform: "uppercase",
    borderBottom: "1px solid rgba(255, 255, 255, 0.03)",
  },
  tr: {
    backgroundColor: "transparent",
    borderBottom: "1px solid rgba(255, 255, 255, 0.015)",
  },
  td: {
    padding: "6px",
    verticalAlign: "middle",
    color: "#111111",
    fontWeight: "500",
    fontSize: "10px",
  },
  tdBold: {
    padding: "6px",
    fontSize: "10px",
    fontWeight: "600",
    color: "#111111",
    letterSpacing: "0.5px",
  },
  tdMuted: {
    padding: "6px",
    fontSize: "10px",
    color: "#477257",
    fontWeight: "400",
  },
  tdHighlight: {
    padding: "6px",
    fontSize: "10px",
    fontWeight: "500",
    color: champagne,
  },
  tdRight: {
    padding: "6px",
    textAlign: "right",
  },
  sosBadge: {
    backgroundColor: "transparent",
    color: "#ef4444",
    fontSize: "8px",
    fontWeight: "600",
    padding: "2px 6px",
    borderRadius: "4px",
    border: "1px solid rgba(239, 68, 68, 0.3)",
    letterSpacing: "1px",
    textTransform: "uppercase",
  },
  sosActionBtn: {
    background: "#ef4444",
    color: "#ffffff",
    border: "none",
    padding: "6px 12px",
    borderRadius: "99px",
    fontSize: "8px",
    fontWeight: "700",
    cursor: "pointer",
    letterSpacing: "1px",
    textTransform: "uppercase",
  },
  dispatchBtn: {
    background: "transparent",
    color: champagne,
    border: `1px solid ${champagne}`,
    padding: "6px 12px",
    borderRadius: "99px",
    fontSize: "8px",
    fontWeight: "600",
    cursor: "pointer",
    letterSpacing: "1px",
    textTransform: "uppercase",
  },
  typeTag: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
  },
  inlineIcon: {
    verticalAlign: "middle",
    color: champagne,
  },
  subBadge: {
    backgroundColor: "transparent",
    color: "#a1a1aa",
    fontSize: "8px",
    fontWeight: "500",
    letterSpacing: "1px",
    textTransform: "uppercase",
  },
  subBadgeBlue: {
    backgroundColor: "transparent",
    color: champagne,
    fontSize: "8px",
    fontWeight: "600",
    letterSpacing: "1px",
    textTransform: "uppercase",
  },
  categoryList: {
    display: "flex",
    flexDirection: "column",
    gap: "1px",
    backgroundColor: "#e7f5eb",
    borderRadius: "8px",
    overflow: "hidden",
  },
  categoryRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#ffffff",
    padding: "10px",
  },
  categoryCountBadge: {
    color: champagne,
    fontSize: "12px",
    fontFamily: editorialFont,
    fontWeight: "400",
  },
  fleetSubtext: {
    color: "#477257",
    fontSize: "10px",
    margin: 0,
    lineHeight: "1.5",
    fontWeight: "400",
    letterSpacing: "0.5px",
  },
  auditList: {
    listStyle: "none",
    padding: 0,
    margin: 0,
    display: "flex",
    flexDirection: "column",
    gap: "1px",
    backgroundColor: "#e7f5eb",
    borderRadius: "8px",
    overflow: "auto",
    flex: 1,
  },
  auditItem: {
    display: "flex",
    gap: "10px",
    backgroundColor: "#ffffff",
    padding: "10px",
  },
  auditContent: {
    flex: 1,
  },
  auditText: {
    margin: 0,
    color: "#111111",
    fontWeight: "400",
    lineHeight: "1.4",
    fontSize: "10px",
  },
  auditTime: {
    color: champagne,
    fontSize: "8px",
    fontWeight: "600",
    marginTop: "4px",
    display: "block",
    letterSpacing: "1px",
    textTransform: "uppercase",
  },
  mapOverlayPosition: {
    position: "absolute",
    top: "12px",
    right: "12px",
    zIndex: 1000,
    display: "flex",
    flexDirection: "column",
    gap: "10px",
    width: "clamp(200px, 18vw, 50px)",
    maxWidth: "calc(100% - 24px)",
  },
  mapStatusPanel: {
    width: "100%",
    minHeight: "120px",
    maxHeight: "min(260px, 50vh)",
    overflowY: "auto",
    padding: "14px",
    boxSizing: "border-box",
    backgroundColor: "rgba(255, 255, 255, 0.96)",
    border: "1px solid #b8d7c1",
    borderRadius: "10px",
    boxShadow: "0 8px 20px rgba(24, 95, 53, 0.12)",
  },
  mapStatusHeader: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    marginBottom: "9px",
  },
  mapStatusHeaderButton: {
    width: "100%",
    padding: 0,
    border: "none",
    backgroundColor: "transparent",
    cursor: "pointer",
    textAlign: "left",
  },
  mapStatusDot: {
    width: "10px",
    height: "10px",
    flexShrink: 0,
    borderRadius: "50%",
    backgroundColor: "#ef4444",
  },
  mapStatusTitle: {
    color: "#111111",
    fontSize: "13px",
    fontWeight: "800",
    letterSpacing: "0.4px",
  },
  mapStatusDivider: {
    width: "100%",
    height: "1px",
    backgroundColor: "#d7e5da",
  },
  mapStatusLabel: {
    marginTop: "10px",
    marginBottom: "7px",
    color: "#477257",
    fontSize: "10px",
    fontWeight: "700",
    letterSpacing: "0.7px",
  },
  mapStatusItem: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    minHeight: "28px",
    color: "#111111",
  },
  mapStatusTypeDot: {
    width: "10px",
    height: "10px",
    flexShrink: 0,
    borderRadius: "50%",
  },
  mapStatusType: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: "12px",
    textTransform: "capitalize",
  },
  mapStatusEmpty: {
    color: "#477257",
    fontSize: "12px",
    lineHeight: "1.4",
  },
  mapStatusCollapsed: {
    width: "42px",
    height: "42px",
    alignSelf: "flex-end",
    padding: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    border: "1px solid #f0b7b7",
    borderRadius: "50%",
    backgroundColor: "#ffffff",
    boxShadow: "0 8px 20px rgba(95, 24, 24, 0.16)",
    cursor: "pointer",
  },
};
export const darkStyles = dashboardStyles;

