export const generateResponderPinStyles = {
  container: {
    padding: "32px",
    background: "linear-gradient(-45deg, #090a0f, #10172a, #0b1120, #020617)",
    backgroundSize: "400% 400%",
    animation: "gradientBG 15s ease infinite",
    minHeight: "100vh",
    color: "#f8fafc",
    fontFamily: "'Inter', sans-serif",
    marginLeft: "260px",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "20px",
    borderBottom: "1px solid rgba(255, 255, 255, 0.1)",
    paddingBottom: "15px",
  },
  title: {
    fontSize: "24px",
    fontWeight: "700",
    color: "#e2e8f0",
    margin: 0,
  },
  card: {
    backgroundColor: "rgba(16, 23, 42, 0.6)",
    backdropFilter: "blur(24px) saturate(150%)",
    WebkitBackdropFilter: "blur(24px) saturate(150%)",
    border: "1px solid rgba(255, 255, 255, 0.08)",
    borderRadius: "12px",
    padding: "20px",
    boxShadow: "0 15px 35px 0 rgba(0, 0, 0, 0.5)",
    marginBottom: "20px",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    marginTop: "10px",
  },
  th: {
    textAlign: "left",
    padding: "12px 15px",
    borderBottom: "1px solid rgba(255,255,255,0.1)",
    color: "#94a3b8",
    fontWeight: "600",
    fontSize: "14px",
    textTransform: "uppercase",
  },
  td: {
    padding: "15px",
    borderBottom: "1px solid rgba(255,255,255,0.05)",
    color: "#e2e8f0",
    fontSize: "14px",
    verticalAlign: "middle",
  },
  buttonPrimary: {
    background: "linear-gradient(135deg, #06b6d4 0%, #3b82f6 100%)",
    color: "#fff",
    border: "none",
    padding: "8px 16px",
    borderRadius: "6px",
    cursor: "pointer",
    fontWeight: "600",
    fontSize: "13px",
    transition: "background 0.2s",
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  buttonPrimaryDisabled: {
    background: "rgba(100, 116, 139, 0.5)",
    color: "#cbd5e1",
    border: "none",
    padding: "8px 16px",
    borderRadius: "6px",
    cursor: "not-allowed",
    fontWeight: "600",
    fontSize: "13px",
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  pinText: {
    fontFamily: "monospace",
    fontSize: "20px",
    letterSpacing: "2px",
    fontWeight: "bold",
    color: "#38bdf8",
    backgroundColor: "rgba(56, 189, 248, 0.1)",
    padding: "6px 12px",
    borderRadius: "6px",
    display: "inline-block",
  },
  badgeActive: {
    backgroundColor: "rgba(16, 185, 129, 0.2)",
    color: "#34d399",
    padding: "4px 8px",
    borderRadius: "12px",
    fontSize: "12px",
    fontWeight: "600",
    display: "inline-block",
  },
  badgeInactive: {
    backgroundColor: "rgba(239, 68, 68, 0.2)",
    color: "#f87171",
    padding: "4px 8px",
    borderRadius: "12px",
    fontSize: "12px",
    fontWeight: "600",
    display: "inline-block",
  },
  actionCell: {
    display: "flex",
    gap: "10px",
  }
};
