export const generateResponderPinStyles = {
  container: {
    padding: "28px 24px 40px",
    background: "radial-gradient(circle at 50% -20%, #ffffff 0%, #f6faf7 80%)",
    minHeight: "100vh",
    color: "#111111",
    fontFamily: "Inter, Arial, sans-serif",
    marginLeft: "216px",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "20px",
    borderBottom: "1px solid #d7e5da",
    paddingBottom: "15px",
  },
  title: {
    fontSize: "24px",
    fontWeight: "700",
    color: "#111111",
    margin: 0,
  },
  card: {
    backgroundColor: "#ffffff",
    border: "1px solid #d7e5da",
    borderRadius: "12px",
    padding: "20px",
    boxShadow: "0 8px 24px rgba(24, 95, 53, 0.06)",
    marginBottom: "20px",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    marginTop: "10px",
  },
  th: {
    textAlign: "left",
    padding: "24px 32px",
    fontSize: "9px",
    fontWeight: "700",
    color: "#477257",
    letterSpacing: "2px",
    textTransform: "uppercase",
    borderBottom: "1px solid #d7e5da",
    backgroundColor: "transparent",
  },
  td: {
    padding: "24px 32px",
    verticalAlign: "middle",
    borderBottom: "1px solid rgba(255, 255, 255, 0.02)",
    color: "#111111",
    fontWeight: "500",
    fontSize: "13px",
  },
  buttonPrimary: {
    background: "#18864b",
    color: "#fff",
    border: "none",
    padding: "8px 16px",
    borderRadius: "6px",
    cursor: "pointer",
    fontWeight: "600",
    fontSize: "13px",
    transition: "background 0.2s",
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  buttonPrimaryDisabled: {
    background: "rgba(100, 116, 139, 0.5)",
    color: "#cbd5e1",
    border: "none",
    padding: "8px 16px",
    borderRadius: "6px",
    cursor: "not-allowed",
    fontWeight: "600",
    fontSize: "13px",
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  pinText: {
    fontFamily: "monospace",
    fontSize: "20px",
    letterSpacing: "2px",
    fontWeight: "bold",
    color: "#38bdf8",
    backgroundColor: "rgba(56, 189, 248, 0.1)",
    padding: "6px 12px",
    borderRadius: "6px",
    display: "inline-block",
  },
  badgeActive: {
    backgroundColor: "rgba(16, 185, 129, 0.2)",
    color: "#34d399",
    padding: "4px 8px",
    borderRadius: "32px",
    fontSize: "12px",
    fontWeight: "600",
    display: "inline-block",
  },
  badgeInactive: {
    backgroundColor: "rgba(239, 68, 68, 0.2)",
    color: "#f87171",
    padding: "4px 8px",
    borderRadius: "32px",
    fontSize: "12px",
    fontWeight: "600",
    display: "inline-block",
  },
  actionCell: {
    display: "flex",
    gap: "10px",
  }
};
