// src/themes/generateResponderPinStyles.js

export function getGenerateResponderPinStyles(isDark = false) {
  return {
    container: {
      padding: "32px 36px",
      background: isDark ? "#090d16" : "#f8fafc",
      minHeight: "100vh",
      color: isDark ? "#f8fafc" : "#0f172a",
      fontFamily: "'Plus Jakarta Sans', sans-serif",
      marginLeft: "216px",
      minWidth: 0,
      overflowY: "auto",
    },
    header: {
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: "28px",
      paddingBottom: "14px",
      borderBottom: isDark ? "1px solid rgba(255, 255, 255, 0.08)" : "1px solid #e2e8f0",
    },
    title: {
      fontSize: "clamp(22px, 3vw, 28px)",
      fontWeight: "800",
      color: isDark ? "#f8fafc" : "#14532d",
      margin: 0,
      letterSpacing: "-0.02em",
    },
    subtitle: {
      margin: "6px 0 0",
      color: isDark ? "#94a3b8" : "#64748b",
      fontSize: "14px",
    },
    card: {
      backgroundColor: isDark ? "#131c2e" : "#ffffff",
      border: isDark ? "1px solid rgba(255, 255, 255, 0.08)" : "1px solid #e2e8f0",
      borderRadius: "16px",
      padding: "24px",
      boxShadow: isDark
        ? "0 4px 20px -2px rgba(0, 0, 0, 0.5)"
        : "0 4px 20px -2px rgba(15, 23, 42, 0.06)",
      marginBottom: "24px",
    },
    securityNotice: {
      display: "flex",
      alignItems: "center",
      gap: "10px",
      padding: "12px 16px",
      backgroundColor: isDark ? "rgba(34, 197, 94, 0.12)" : "#f0fdf4",
      border: isDark ? "1px solid rgba(34, 197, 94, 0.3)" : "1px solid #bbf7d0",
      borderRadius: "10px",
      margin: "0 0 20px 0",
      fontSize: "13px",
      color: isDark ? "#86efac" : "#166534",
      lineHeight: "1.4",
    },
    table: {
      width: "100%",
      borderCollapse: "collapse",
      marginTop: "8px",
    },
    th: {
      textAlign: "left",
      padding: "12px 14px",
      fontSize: "11px",
      fontWeight: "800",
      color: isDark ? "#cbd5e1" : "#64748b",
      letterSpacing: "0.04em",
      textTransform: "uppercase",
      borderBottom: isDark ? "1px solid rgba(255, 255, 255, 0.08)" : "1px solid #e2e8f0",
      backgroundColor: isDark ? "#172338" : "#f8fafc",
    },
    td: {
      padding: "12px 14px",
      verticalAlign: "middle",
      borderBottom: isDark ? "1px solid rgba(255, 255, 255, 0.06)" : "1px solid #f1f5f9",
      color: isDark ? "#cbd5e1" : "#334155",
      fontWeight: "400",
      fontSize: "13px",
    },
    buttonPrimary: {
      background: "linear-gradient(135deg, #15803d 0%, #166534 100%)",
      color: "#fff",
      border: "none",
      padding: "8px 14px",
      borderRadius: "8px",
      cursor: "pointer",
      fontWeight: "700",
      fontSize: "12px",
      transition: "all 0.15s ease",
      display: "flex",
      alignItems: "center",
      gap: "6px",
    },
    buttonPrimaryDisabled: {
      background: isDark ? "#1e293b" : "#f1f5f9",
      color: isDark ? "#64748b" : "#94a3b8",
      border: "none",
      padding: "8px 14px",
      borderRadius: "8px",
      cursor: "not-allowed",
      fontWeight: "700",
      fontSize: "12px",
      display: "flex",
      alignItems: "center",
      gap: "6px",
    },
    pinText: {
      fontFamily: "monospace",
      fontSize: "16px",
      letterSpacing: "0.15em",
      fontWeight: "800",
      color: isDark ? "#4ade80" : "#15803d",
      backgroundColor: isDark ? "#172338" : "#f0fdf4",
      padding: "6px 12px",
      borderRadius: "8px",
      border: isDark ? "1px solid rgba(255, 255, 255, 0.12)" : "1px solid #dcfce7",
      display: "inline-block",
    },
    pinCell: {
      display: "flex",
      alignItems: "center",
      gap: "8px",
      flexWrap: "wrap",
    },
    copyButton: {
      display: "inline-flex",
      alignItems: "center",
      gap: "4px",
      padding: "6px 10px",
      border: isDark ? "1px solid rgba(255, 255, 255, 0.12)" : "1px solid #cbd5e1",
      borderRadius: "6px",
      backgroundColor: isDark ? "#172338" : "#ffffff",
      color: isDark ? "#cbd5e1" : "#475569",
      cursor: "pointer",
      fontSize: "12px",
      fontWeight: "600",
      transition: "all 0.15s ease",
    },
    copyButtonCopied: {
      display: "inline-flex",
      alignItems: "center",
      gap: "4px",
      padding: "6px 10px",
      border: isDark ? "1px solid rgba(34, 197, 94, 0.35)" : "1px solid #bbf7d0",
      borderRadius: "6px",
      backgroundColor: isDark ? "rgba(34, 197, 94, 0.25)" : "#f0fdf4",
      color: isDark ? "#4ade80" : "#15803d",
      cursor: "pointer",
      fontSize: "12px",
      fontWeight: "600",
      transition: "all 0.15s ease",
    },
    badgeActive: {
      backgroundColor: isDark ? "rgba(34, 197, 94, 0.18)" : "#f0fdf4",
      color: isDark ? "#4ade80" : "#15803d",
      padding: "3px 8px",
      borderRadius: "6px",
      fontSize: "11px",
      fontWeight: "800",
      border: isDark ? "1px solid rgba(34, 197, 94, 0.35)" : "1px solid #dcfce7",
      display: "inline-block",
    },
    badgeInactive: {
      backgroundColor: isDark ? "rgba(239, 68, 68, 0.18)" : "#fef2f2",
      color: isDark ? "#f87171" : "#b91c1c",
      padding: "3px 8px",
      borderRadius: "6px",
      fontSize: "11px",
      fontWeight: "800",
      border: isDark ? "1px solid rgba(239, 68, 68, 0.35)" : "1px solid #fee2e2",
      display: "inline-block",
    },
    actionCell: {
      display: "flex",
      gap: "8px",
    },
    infoText: {
      marginBottom: "12px",
      color: isDark ? "#94a3b8" : "#64748b",
      fontSize: "13px",
      lineHeight: 1.4,
    },
    loadingText: {
      minHeight: "120px",
      padding: "16px",
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      justifyContent: "center",
      gap: "8px",
      textAlign: "center",
      color: isDark ? "#4ade80" : "#15803d",
      fontSize: "13px",
      fontWeight: "500",
    }
  };
}

export const generateResponderPinStyles = getGenerateResponderPinStyles(false);

