// src/themes/loginStyles.js

export const getLoginStyles = (isDark = false) => ({
  container: {
    minHeight: "100vh",
    backgroundColor: isDark ? "#090d16" : "#f8fafc",
    backgroundImage: isDark
      ? "radial-gradient(circle at 50% 0%, #131c2e 0%, #090d16 85%)"
      : "none",
    color: isDark ? "#f1f5f9" : "#0f172a",
    fontFamily: "Inter, -apple-system, BlinkMacSystemFont, sans-serif",
    transition: "background-color 0.2s ease, color 0.2s ease",
  },
  header: {
    height: "64px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "0 32px",
    backgroundColor: isDark ? "#0f172a" : "#ffffff",
    borderBottom: isDark
      ? "1px solid rgba(255, 255, 255, 0.08)"
      : "1px solid #e2e8f0",
    boxSizing: "border-box",
    position: "sticky",
    top: 0,
    zIndex: 10,
    transition: "background-color 0.2s ease, border-color 0.2s ease",
  },
  headerBrand: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
  },
  headerLogo: {
    width: "32px",
    height: "32px",
    objectFit: "contain",
  },
  headerTitle: {
    color: isDark ? "#f8fafc" : "#000000",
    fontSize: "22px",
    fontWeight: "800",
    letterSpacing: "-0.025em",
  },
  headerActions: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
  },
  content: {
    minHeight: "calc(100vh - 64px)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "48px 24px",
    boxSizing: "border-box",
  },
  cardWrapper: {
    position: "relative",
    width: "100%",
    maxWidth: "560px",
  },
  card: {
    position: "relative",
    zIndex: 1,
    backgroundColor: isDark ? "#131c2e" : "#ffffff",
    borderRadius: "22px",
    padding: "52px 46px",
    border: isDark
      ? "1px solid rgba(255, 255, 255, 0.1)"
      : "1px solid #e2e8f0",
    boxShadow: isDark
      ? "0 25px 60px -10px rgba(0, 0, 0, 0.8), 0 12px 24px -5px rgba(0, 0, 0, 0.6)"
      : "0 20px 45px -10px rgba(0, 0, 0, 0.1), 0 8px 16px -4px rgba(0, 0, 0, 0.04)",
    width: "100%",
    boxSizing: "border-box",
    transition: "background-color 0.2s ease, border-color 0.2s ease, box-shadow 0.2s ease",
  },
  brandBox: {
    textAlign: "center",
    marginBottom: "32px",
    position: "relative",
    zIndex: 2,
  },
  brandLogo: {
    width: "90px",
    height: "90px",
    objectFit: "contain",
    margin: "0 auto 18px auto",
    display: "block",
  },
  badge: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    padding: "5px 12px",
    borderRadius: "8px",
    backgroundColor: isDark ? "rgba(34, 197, 94, 0.15)" : "#f0fdf4",
    border: isDark ? "1px solid rgba(34, 197, 94, 0.3)" : "1px solid #dcfce7",
    color: isDark ? "#4ade80" : "#15803d",
    fontSize: "13px",
    fontWeight: "700",
    marginBottom: "14px",
  },
  title: {
    margin: 0,
    fontSize: "30px",
    lineHeight: 1.2,
    fontWeight: "900",
    letterSpacing: "-0.03em",
    color: isDark ? "#f8fafc" : "#0f172a",
  },
  subtitle: {
    margin: "10px 0 0",
    color: isDark ? "#94a3b8" : "#64748b",
    fontSize: "15px",
    fontWeight: "400",
    lineHeight: 1.5,
  },
  bannerError: {
    display: "flex",
    alignItems: "flex-start",
    gap: "8px",
    padding: "10px 12px",
    borderRadius: "6px",
    backgroundColor: isDark ? "rgba(239, 68, 68, 0.15)" : "#fef2f2",
    border: isDark ? "1px solid rgba(239, 68, 68, 0.3)" : "1px solid #fee2e2",
    color: isDark ? "#f87171" : "#b91c1c",
    fontSize: "12px",
    fontWeight: "500",
    lineHeight: 1.4,
    marginBottom: "14px",
  },
  bannerSuccess: {
    display: "flex",
    alignItems: "flex-start",
    gap: "8px",
    padding: "10px 12px",
    borderRadius: "6px",
    backgroundColor: isDark ? "rgba(34, 197, 94, 0.15)" : "#f0fdf4",
    border: isDark ? "1px solid rgba(34, 197, 94, 0.3)" : "1px solid #dcfce7",
    color: isDark ? "#4ade80" : "#15803d",
    fontSize: "12px",
    fontWeight: "500",
    lineHeight: 1.4,
    marginBottom: "14px",
  },
  bannerClose: {
    background: "transparent",
    border: "none",
    padding: "0",
    marginLeft: "auto",
    color: "currentColor",
    opacity: 0.7,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  capsLockNotice: {
    display: "inline-flex",
    alignItems: "center",
    gap: "4px",
    marginTop: "4px",
    marginLeft: "2px",
    color: isDark ? "#fbbf24" : "#d97706",
    fontSize: "11px",
    fontWeight: "500",
  },
  form: {
    display: "flex",
    flexDirection: "column",
    gap: "20px",
    position: "relative",
    zIndex: 2,
  },
  inputGroup: {
    position: "relative",
    display: "flex",
    flexDirection: "column",
  },
  inputWrapper: {
    position: "relative",
    display: "flex",
    alignItems: "center",
    width: "100%",
  },
  inputIconLeft: {
    position: "absolute",
    left: "16px",
    color: isDark ? "#64748b" : "#94a3b8",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    pointerEvents: "none",
    zIndex: 2,
  },
  inputIconRight: {
    position: "absolute",
    right: "14px",
    background: "transparent",
    border: "none",
    color: isDark ? "#64748b" : "#94a3b8",
    cursor: "pointer",
    padding: "6px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "6px",
    zIndex: 2,
  },
  inputElement: {
    width: "100%",
    height: "54px",
    padding: "0 46px 0 50px",
    fontSize: "15px",
    fontWeight: "400",
    color: isDark ? "#f8fafc" : "#0f172a",
    backgroundColor: isDark ? "#172338" : "#ffffff",
    border: isDark ? "1px solid rgba(255, 255, 255, 0.12)" : "1px solid #cbd5e1",
    borderRadius: "12px",
    outline: "none",
    boxSizing: "border-box",
    transition: "border-color 0.15s ease, background-color 0.15s ease, box-shadow 0.15s ease",
  },
  floatingLabel: {
    position: "absolute",
    left: "48px",
    top: "50%",
    transform: "translateY(-50%)",
    fontSize: "15px",
    fontWeight: "400",
    color: isDark ? "#64748b" : "#94a3b8",
    pointerEvents: "none",
    transition: "all 0.15s ease",
    backgroundColor: "transparent",
    padding: "0 6px",
    zIndex: 3,
  },
  floatingLabelActive: {
    top: "0px",
    left: "14px",
    transform: "translateY(-50%)",
    fontSize: "12px",
    fontWeight: "700",
    color: isDark ? "#4ade80" : "#15803d",
    backgroundColor: isDark ? "#131c2e" : "#ffffff",
    borderRadius: "4px",
  },
  errorText: {
    display: "flex",
    alignItems: "center",
    gap: "4px",
    margin: "6px 0 0 2px",
    color: isDark ? "#f87171" : "#ef4444",
    fontSize: "12.5px",
    fontWeight: "500",
  },
  hintText: {
    margin: "4px 0 0 2px",
    color: isDark ? "#94a3b8" : "#64748b",
    fontSize: "12.5px",
    fontWeight: "400",
  },
  optionsRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: "2px",
  },
  rememberLabel: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    fontSize: "14px",
    fontWeight: "500",
    color: isDark ? "#cbd5e1" : "#475569",
    cursor: "pointer",
    userSelect: "none",
  },
  customCheckbox: {
    width: "18px",
    height: "18px",
    borderRadius: "5px",
    border: isDark ? "1px solid rgba(255, 255, 255, 0.25)" : "1px solid #cbd5e1",
    accentColor: "#15803d",
    cursor: "pointer",
    backgroundColor: isDark ? "#172338" : "#ffffff",
  },
  forgotLink: {
    fontSize: "14px",
    fontWeight: "600",
    color: isDark ? "#4ade80" : "#15803d",
    textDecoration: "none",
    cursor: "pointer",
    transition: "color 0.15s ease",
  },
  button: {
    width: "100%",
    height: "54px",
    marginTop: "8px",
    background: isDark ? "#16a34a" : "#15803d",
    color: "#ffffff",
    border: "none",
    borderRadius: "12px",
    fontSize: "16.5px",
    fontWeight: "800",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
    position: "relative",
    transition: "background-color 0.15s ease, transform 0.15s ease, box-shadow 0.15s ease",
  },
  buttonText: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
  },
  backButton: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    background: "transparent",
    border: "none",
    color: isDark ? "#4ade80" : "#15803d",
    fontSize: "14px",
    fontWeight: "600",
    cursor: "pointer",
    padding: "6px 0",
    marginTop: "6px",
    alignSelf: "center",
  },
  footer: {
    textAlign: "center",
    marginTop: "12px",
    position: "relative",
    zIndex: 2,
  },
  footerText: {
    margin: 0,
    fontSize: "14px",
    color: isDark ? "#94a3b8" : "#64748b",
    fontWeight: "400",
  },
  signUpLink: {
    color: isDark ? "#4ade80" : "#15803d",
    fontWeight: "600",
    cursor: "pointer",
    marginLeft: "4px",
    textDecoration: "none",
  },
  alertOverlay: {
    position: "fixed",
    inset: 0,
    zIndex: 20000,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "20px",
    backgroundColor: "rgba(15, 23, 42, 0.65)",
    backdropFilter: "blur(4px)",
  },
  alertDialog: {
    width: "100%",
    maxWidth: "360px",
    padding: "24px",
    borderRadius: "8px",
    backgroundColor: isDark ? "#131c2e" : "#ffffff",
    boxShadow: "0 20px 25px -5px rgba(0, 0, 0, 0.3)",
    textAlign: "center",
    boxSizing: "border-box",
    border: isDark ? "1px solid rgba(255, 255, 255, 0.12)" : "1px solid #e2e8f0",
  },
  alertIcon: {
    width: "40px",
    height: "40px",
    margin: "0 auto 12px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "50%",
    backgroundColor: isDark ? "rgba(239, 68, 68, 0.15)" : "#fef2f2",
    color: isDark ? "#f87171" : "#ef4444",
  },
  alertTitle: {
    margin: 0,
    color: isDark ? "#f8fafc" : "#0f172a",
    fontSize: "16px",
    fontWeight: "600",
  },
  alertMessage: {
    margin: "8px 0 16px",
    color: isDark ? "#94a3b8" : "#64748b",
    fontSize: "13px",
    lineHeight: 1.4,
  },
  alertButton: {
    width: "100%",
    height: "38px",
    border: "none",
    borderRadius: "6px",
    background: isDark ? "#16a34a" : "#15803d",
    color: "#ffffff",
    cursor: "pointer",
    fontSize: "13px",
    fontWeight: "600",
  },
});

export const loginStyles = getLoginStyles(false);
