// src/themes/loginStyles.js

export const getLoginStyles = (isDark = false) => ({
  container: {
    minHeight: "100vh",
    backgroundColor: isDark ? "#090d16" : "#f8fafc",
    backgroundImage: isDark
      ? "radial-gradient(circle at 50% 0%, #131c2e 0%, #090d16 85%)"
      : "none",
    color: isDark ? "#f1f5f9" : "#0f172a",
    fontFamily: "Inter, -apple-system, BlinkMacSystemFont, sans-serif",
    transition: "background-color 0.2s ease, color 0.2s ease",
  },
  header: {
    height: "56px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "0 24px",
    backgroundColor: isDark ? "#0f172a" : "#ffffff",
    borderBottom: isDark
      ? "1px solid rgba(255, 255, 255, 0.08)"
      : "1px solid #e2e8f0",
    boxSizing: "border-box",
    position: "sticky",
    top: 0,
    zIndex: 10,
    transition: "background-color 0.2s ease, border-color 0.2s ease",
  },
  headerBrand: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
  },
  headerLogo: {
    width: "28px",
    height: "28px",
    objectFit: "contain",
  },
  headerTitle: {
    color: isDark ? "#f8fafc" : "#0f172a",
    fontSize: "15px",
    fontWeight: "600",
    letterSpacing: "-0.01em",
  },
  headerActions: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  content: {
    minHeight: "calc(100vh - 56px)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "32px 20px",
    boxSizing: "border-box",
  },
  cardWrapper: {
    position: "relative",
    width: "100%",
    maxWidth: "400px",
  },
  card: {
    position: "relative",
    zIndex: 1,
    backgroundColor: isDark ? "#131c2e" : "#ffffff",
    borderRadius: "10px",
    padding: "32px 28px",
    border: isDark
      ? "1px solid rgba(255, 255, 255, 0.09)"
      : "1px solid #e2e8f0",
    boxShadow: isDark
      ? "0 20px 30px -10px rgba(0, 0, 0, 0.6), 0 8px 10px -6px rgba(0, 0, 0, 0.4)"
      : "0 1px 3px rgba(0, 0, 0, 0.04)",
    width: "100%",
    boxSizing: "border-box",
    transition: "background-color 0.2s ease, border-color 0.2s ease, box-shadow 0.2s ease",
  },
  brandBox: {
    textAlign: "center",
    marginBottom: "20px",
    position: "relative",
    zIndex: 2,
  },
  brandLogo: {
    width: "56px",
    height: "56px",
    objectFit: "contain",
    margin: "0 auto 12px auto",
    display: "block",
  },
  badge: {
    display: "inline-flex",
    alignItems: "center",
    gap: "4px",
    padding: "3px 8px",
    borderRadius: "4px",
    backgroundColor: isDark ? "rgba(34, 197, 94, 0.15)" : "#f0fdf4",
    border: isDark ? "1px solid rgba(34, 197, 94, 0.3)" : "1px solid #dcfce7",
    color: isDark ? "#4ade80" : "#15803d",
    fontSize: "11px",
    fontWeight: "600",
    marginBottom: "10px",
  },
  title: {
    margin: 0,
    fontSize: "20px",
    lineHeight: 1.25,
    fontWeight: "600",
    letterSpacing: "-0.02em",
    color: isDark ? "#f8fafc" : "#0f172a",
  },
  subtitle: {
    margin: "4px 0 0",
    color: isDark ? "#94a3b8" : "#64748b",
    fontSize: "13px",
    fontWeight: "400",
    lineHeight: 1.4,
  },
  bannerError: {
    display: "flex",
    alignItems: "flex-start",
    gap: "8px",
    padding: "10px 12px",
    borderRadius: "6px",
    backgroundColor: isDark ? "rgba(239, 68, 68, 0.15)" : "#fef2f2",
    border: isDark ? "1px solid rgba(239, 68, 68, 0.3)" : "1px solid #fee2e2",
    color: isDark ? "#f87171" : "#b91c1c",
    fontSize: "12px",
    fontWeight: "500",
    lineHeight: 1.4,
    marginBottom: "14px",
  },
  bannerSuccess: {
    display: "flex",
    alignItems: "flex-start",
    gap: "8px",
    padding: "10px 12px",
    borderRadius: "6px",
    backgroundColor: isDark ? "rgba(34, 197, 94, 0.15)" : "#f0fdf4",
    border: isDark ? "1px solid rgba(34, 197, 94, 0.3)" : "1px solid #dcfce7",
    color: isDark ? "#4ade80" : "#15803d",
    fontSize: "12px",
    fontWeight: "500",
    lineHeight: 1.4,
    marginBottom: "14px",
  },
  bannerClose: {
    background: "transparent",
    border: "none",
    padding: "0",
    marginLeft: "auto",
    color: "currentColor",
    opacity: 0.7,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  capsLockNotice: {
    display: "inline-flex",
    alignItems: "center",
    gap: "4px",
    marginTop: "4px",
    marginLeft: "2px",
    color: isDark ? "#fbbf24" : "#d97706",
    fontSize: "11px",
    fontWeight: "500",
  },
  form: {
    display: "flex",
    flexDirection: "column",
    gap: "14px",
    position: "relative",
    zIndex: 2,
  },
  inputGroup: {
    position: "relative",
    display: "flex",
    flexDirection: "column",
  },
  inputWrapper: {
    position: "relative",
    display: "flex",
    alignItems: "center",
    width: "100%",
  },
  inputIconLeft: {
    position: "absolute",
    left: "12px",
    color: isDark ? "#64748b" : "#94a3b8",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    pointerEvents: "none",
    zIndex: 2,
  },
  inputIconRight: {
    position: "absolute",
    right: "10px",
    background: "transparent",
    border: "none",
    color: isDark ? "#64748b" : "#94a3b8",
    cursor: "pointer",
    padding: "4px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "4px",
    zIndex: 2,
  },
  inputElement: {
    width: "100%",
    height: "42px",
    padding: "0 36px 0 38px",
    fontSize: "13px",
    fontWeight: "400",
    color: isDark ? "#f8fafc" : "#0f172a",
    backgroundColor: isDark ? "#172338" : "#ffffff",
    border: isDark ? "1px solid rgba(255, 255, 255, 0.12)" : "1px solid #e2e8f0",
    borderRadius: "6px",
    outline: "none",
    boxSizing: "border-box",
    transition: "border-color 0.15s ease, background-color 0.15s ease, box-shadow 0.15s ease",
  },
  floatingLabel: {
    position: "absolute",
    left: "38px",
    top: "50%",
    transform: "translateY(-50%)",
    fontSize: "13px",
    fontWeight: "400",
    color: isDark ? "#64748b" : "#94a3b8",
    pointerEvents: "none",
    transition: "all 0.15s ease",
    backgroundColor: "transparent",
    padding: "0 4px",
    zIndex: 3,
  },
  floatingLabelActive: {
    top: "0px",
    left: "10px",
    transform: "translateY(-50%)",
    fontSize: "11px",
    fontWeight: "500",
    color: isDark ? "#4ade80" : "#15803d",
    backgroundColor: isDark ? "#131c2e" : "#ffffff",
    borderRadius: "2px",
  },
  errorText: {
    display: "flex",
    alignItems: "center",
    gap: "4px",
    margin: "4px 0 0 2px",
    color: isDark ? "#f87171" : "#ef4444",
    fontSize: "11px",
    fontWeight: "400",
  },
  hintText: {
    margin: "4px 0 0 2px",
    color: isDark ? "#94a3b8" : "#64748b",
    fontSize: "11px",
    fontWeight: "400",
  },
  optionsRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: "2px",
  },
  rememberLabel: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    fontSize: "12px",
    fontWeight: "400",
    color: isDark ? "#cbd5e1" : "#475569",
    cursor: "pointer",
    userSelect: "none",
  },
  customCheckbox: {
    width: "15px",
    height: "15px",
    borderRadius: "3px",
    border: isDark ? "1px solid rgba(255, 255, 255, 0.2)" : "1px solid #cbd5e1",
    accentColor: "#15803d",
    cursor: "pointer",
    backgroundColor: isDark ? "#172338" : "#ffffff",
  },
  forgotLink: {
    fontSize: "12px",
    fontWeight: "500",
    color: isDark ? "#4ade80" : "#15803d",
    textDecoration: "none",
    cursor: "pointer",
    transition: "color 0.15s ease",
  },
  button: {
    width: "100%",
    height: "42px",
    marginTop: "4px",
    background: isDark ? "#16a34a" : "#15803d",
    color: "#ffffff",
    border: "none",
    borderRadius: "6px",
    fontSize: "14px",
    fontWeight: "600",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "6px",
    position: "relative",
    transition: "background-color 0.15s ease, transform 0.15s ease, box-shadow 0.15s ease",
  },
  buttonText: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
  },
  backButton: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    background: "transparent",
    border: "none",
    color: isDark ? "#4ade80" : "#15803d",
    fontSize: "12px",
    fontWeight: "500",
    cursor: "pointer",
    padding: "4px 0",
    marginTop: "4px",
    alignSelf: "center",
  },
  footer: {
    textAlign: "center",
    marginTop: "8px",
    position: "relative",
    zIndex: 2,
  },
  footerText: {
    margin: 0,
    fontSize: "12px",
    color: isDark ? "#94a3b8" : "#64748b",
    fontWeight: "400",
  },
  signUpLink: {
    color: isDark ? "#4ade80" : "#15803d",
    fontWeight: "500",
    cursor: "pointer",
    marginLeft: "4px",
    textDecoration: "none",
  },
  alertOverlay: {
    position: "fixed",
    inset: 0,
    zIndex: 20000,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "20px",
    backgroundColor: "rgba(15, 23, 42, 0.65)",
    backdropFilter: "blur(4px)",
  },
  alertDialog: {
    width: "100%",
    maxWidth: "360px",
    padding: "24px",
    borderRadius: "8px",
    backgroundColor: isDark ? "#131c2e" : "#ffffff",
    boxShadow: "0 20px 25px -5px rgba(0, 0, 0, 0.3)",
    textAlign: "center",
    boxSizing: "border-box",
    border: isDark ? "1px solid rgba(255, 255, 255, 0.12)" : "1px solid #e2e8f0",
  },
  alertIcon: {
    width: "40px",
    height: "40px",
    margin: "0 auto 12px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "50%",
    backgroundColor: isDark ? "rgba(239, 68, 68, 0.15)" : "#fef2f2",
    color: isDark ? "#f87171" : "#ef4444",
  },
  alertTitle: {
    margin: 0,
    color: isDark ? "#f8fafc" : "#0f172a",
    fontSize: "16px",
    fontWeight: "600",
  },
  alertMessage: {
    margin: "8px 0 16px",
    color: isDark ? "#94a3b8" : "#64748b",
    fontSize: "13px",
    lineHeight: 1.4,
  },
  alertButton: {
    width: "100%",
    height: "38px",
    border: "none",
    borderRadius: "6px",
    background: isDark ? "#16a34a" : "#15803d",
    color: "#ffffff",
    cursor: "pointer",
    fontSize: "13px",
    fontWeight: "600",
  },
});

export const loginStyles = getLoginStyles(false);
