// src/themes/loginStyles.js

export const loginStyles = {
  container: {
    minHeight: "100vh",
    background: "radial-gradient(ellipse at 50% 0%, #f0fdf4 0%, #f6faf7 60%, #f8fafc 100%)",
    color: "#0f172a",
    fontFamily: "'Plus Jakarta Sans', 'Inter', -apple-system, BlinkMacSystemFont, sans-serif",
  },
  header: {
    height: "64px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "10px",
    backgroundColor: "rgba(255, 255, 255, 0.92)",
    backdropFilter: "blur(12px)",
    borderBottom: "1px solid #e2e8f0",
    boxSizing: "border-box",
    position: "sticky",
    top: 0,
    zIndex: 10,
  },
  headerLogo: {
    width: "36px",
    height: "36px",
    objectFit: "contain",
  },
  headerTitle: {
    color: "#1e293b",
    fontSize: "17px",
    fontWeight: "700",
    letterSpacing: "-0.01em",
  },
  content: {
    minHeight: "calc(100vh - 64px)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "36px 20px",
    boxSizing: "border-box",
  },
  cardWrapper: {
    position: "relative",
    width: "100%",
    maxWidth: "420px",
  },
  card: {
    position: "relative",
    zIndex: 1,
    backgroundColor: "#ffffff",
    borderRadius: "18px",
    padding: "clamp(24px, 6vw, 36px) clamp(18px, 5vw, 32px)",
    border: "1px solid #d1fae5",
    boxShadow: "0 14px 34px -4px rgba(21, 128, 61, 0.16), 0 6px 16px -2px rgba(21, 128, 61, 0.08)",
    width: "100%",
    boxSizing: "border-box",
  },
  brandBox: {
    textAlign: "center",
    marginBottom: "24px",
    position: "relative",
    zIndex: 2,
  },
  brandLogo: {
    width: "clamp(60px, 15vw, 78px)",
    height: "clamp(60px, 15vw, 78px)",
    objectFit: "contain",
    margin: "0 auto 14px auto",
    display: "block",
    filter: "drop-shadow(0 4px 10px rgba(21, 128, 61, 0.16))",
    transition: "transform 0.2s ease",
  },
  badge: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    padding: "4px 10px",
    borderRadius: "20px",
    backgroundColor: "#f0fdf4",
    border: "1px solid #bbf7d0",
    color: "#15803d",
    fontSize: "12px",
    fontWeight: "600",
    letterSpacing: "0.02em",
    marginBottom: "12px",
  },
  title: {
    margin: 0,
    fontSize: "clamp(20px, 5vw, 26px)",
    lineHeight: 1.25,
    fontWeight: "800",
    letterSpacing: "-0.02em",
    color: "#14532d",
  },
  subtitle: {
    margin: "6px 0 0",
    color: "#64748b",
    fontSize: "clamp(12px, 3.2vw, 13.5px)",
    fontWeight: "500",
    lineHeight: 1.4,
  },
  // In-form Feedback Banners
  bannerError: {
    display: "flex",
    alignItems: "flex-start",
    gap: "10px",
    padding: "10px 14px",
    borderRadius: "10px",
    backgroundColor: "#fef2f2",
    border: "1px solid #fecaca",
    color: "#991b1b",
    fontSize: "13px",
    fontWeight: "500",
    lineHeight: 1.4,
    marginBottom: "16px",
    animation: "fadeIn 0.2s ease-in-out",
  },
  bannerSuccess: {
    display: "flex",
    alignItems: "flex-start",
    gap: "10px",
    padding: "10px 14px",
    borderRadius: "10px",
    backgroundColor: "#f0fdf4",
    border: "1px solid #bbf7d0",
    color: "#166534",
    fontSize: "13px",
    fontWeight: "500",
    lineHeight: 1.4,
    marginBottom: "16px",
    animation: "fadeIn 0.2s ease-in-out",
  },
  bannerClose: {
    background: "transparent",
    border: "none",
    padding: "0",
    marginLeft: "auto",
    color: "currentColor",
    opacity: 0.7,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  capsLockNotice: {
    display: "inline-flex",
    alignItems: "center",
    gap: "5px",
    marginTop: "4px",
    marginLeft: "4px",
    color: "#d97706",
    fontSize: "11.5px",
    fontWeight: "600",
  },
  form: {
    display: "flex",
    flexDirection: "column",
    gap: "18px",
    position: "relative",
    zIndex: 2,
  },
  inputGroup: {
    position: "relative",
    display: "flex",
    flexDirection: "column",
  },
  inputWrapper: {
    position: "relative",
    display: "flex",
    alignItems: "center",
    width: "100%",
  },
  inputIconLeft: {
    position: "absolute",
    left: "14px",
    color: "#15803d",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    pointerEvents: "none",
    zIndex: 2,
  },
  inputIconRight: {
    position: "absolute",
    right: "12px",
    background: "transparent",
    border: "none",
    color: "#94a3b8",
    cursor: "pointer",
    padding: "6px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "6px",
    transition: "color 0.15s ease",
    zIndex: 2,
  },
  inputElement: {
    width: "100%",
    height: "48px",
    padding: "0 40px 0 42px",
    fontSize: "14px",
    fontWeight: "500",
    color: "#0f172a",
    backgroundColor: "#ffffff",
    border: "1.5px solid #e2e8f0",
    borderRadius: "12px",
    outline: "none",
    boxSizing: "border-box",
    transition: "border-color 0.18s ease, box-shadow 0.18s ease, background-color 0.18s ease",
  },
  floatingLabel: {
    position: "absolute",
    left: "42px",
    top: "50%",
    transform: "translateY(-50%)",
    fontSize: "14px",
    fontWeight: "500",
    color: "#94a3b8",
    pointerEvents: "none",
    transition: "all 0.18s cubic-bezier(0.4, 0, 0.2, 1)",
    backgroundColor: "transparent",
    padding: "0 4px",
    zIndex: 3,
  },
  floatingLabelActive: {
    top: "0px",
    left: "14px",
    transform: "translateY(-50%)",
    fontSize: "11.5px",
    fontWeight: "600",
    color: "#15803d",
    backgroundColor: "#ffffff",
  },
  errorText: {
    display: "flex",
    alignItems: "center",
    gap: "4px",
    margin: "5px 0 0 6px",
    color: "#ef4444",
    fontSize: "12px",
    fontWeight: "500",
  },
  hintText: {
    margin: "4px 0 0 6px",
    color: "#64748b",
    fontSize: "11.5px",
    fontWeight: "500",
  },
  optionsRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: "2px",
  },
  rememberLabel: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    fontSize: "13px",
    fontWeight: "500",
    color: "#475569",
    cursor: "pointer",
    userSelect: "none",
  },
  customCheckbox: {
    width: "16px",
    height: "16px",
    borderRadius: "4px",
    border: "1.5px solid #cbd5e1",
    accentColor: "#15803d",
    cursor: "pointer",
  },
  forgotLink: {
    fontSize: "13px",
    fontWeight: "600",
    color: "#15803d",
    textDecoration: "none",
    cursor: "pointer",
    transition: "color 0.15s ease",
  },
  button: {
    width: "100%",
    height: "48px",
    marginTop: "4px",
    background: "linear-gradient(135deg, #15803d 0%, #166534 100%)",
    color: "#ffffff",
    border: "none",
    borderRadius: "12px",
    fontSize: "15px",
    fontWeight: "600",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
    boxShadow: "0 2px 8px rgba(21, 128, 61, 0.22)",
    position: "relative",
    transition: "all 0.18s ease",
  },
  buttonText: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    letterSpacing: "0.01em",
  },
  backButton: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    background: "transparent",
    border: "none",
    color: "#15803d",
    fontSize: "13px",
    fontWeight: "600",
    cursor: "pointer",
    padding: "6px 0",
    marginTop: "4px",
    alignSelf: "center",
    transition: "color 0.15s ease",
  },
  footer: {
    textAlign: "center",
    marginTop: "8px",
    position: "relative",
    zIndex: 2,
  },
  footerText: {
    margin: 0,
    fontSize: "13px",
    color: "#64748b",
    fontWeight: "500",
  },
  signUpLink: {
    color: "#15803d",
    fontWeight: "600",
    cursor: "pointer",
    marginLeft: "4px",
    textDecoration: "none",
    transition: "color 0.15s ease",
  },
  alertOverlay: {
    position: "fixed",
    inset: 0,
    zIndex: 20000,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "20px",
    backgroundColor: "rgba(15, 23, 42, 0.45)",
    backdropFilter: "blur(6px)",
    transition: "opacity 220ms ease",
  },
  alertDialog: {
    width: "100%",
    maxWidth: "380px",
    padding: "28px",
    borderRadius: "16px",
    backgroundColor: "#ffffff",
    boxShadow: "0 10px 30px rgba(15, 23, 42, 0.12)",
    textAlign: "center",
    boxSizing: "border-box",
    border: "1px solid #e2e8f0",
    transition: "opacity 220ms ease, transform 220ms cubic-bezier(0.22, 1, 0.36, 1)",
  },
  alertIcon: {
    width: "48px",
    height: "48px",
    margin: "0 auto 14px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "50%",
    backgroundColor: "#fef2f2",
    color: "#ef4444",
  },
  alertTitle: {
    margin: 0,
    color: "#0f172a",
    fontSize: "18px",
    fontWeight: "700",
  },
  alertMessage: {
    margin: "10px 0 20px",
    color: "#64748b",
    fontSize: "14px",
    lineHeight: 1.5,
  },
  alertButton: {
    width: "100%",
    height: "42px",
    border: "none",
    borderRadius: "10px",
    background: "#15803d",
    color: "#ffffff",
    cursor: "pointer",
    fontSize: "14px",
    fontWeight: "600",
    boxShadow: "0 2px 6px rgba(21, 128, 61, 0.2)",
  },
};


