export const manageAdminsStyle = {
  container: {
    padding: "28px 24px 40px",
    background: "radial-gradient(circle at 50% -20%, #ffffff 0%, #f6faf7 80%)",
    minHeight: "100vh",
    color: "#111111",
    fontFamily: "Inter, Arial, sans-serif",
    marginLeft: "216px",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "20px",
    borderBottom: "1px solid #d7e5da",
    paddingBottom: "15px",
  },
  title: {
    fontSize: "24px",
    fontWeight: "700",
    color: "#111111",
    margin: 0,
  },
  card: {
    backgroundColor: "#ffffff",
    border: "1px solid #d7e5da",
    borderRadius: "12px",
    padding: "20px",
    boxShadow: "0 8px 24px rgba(24, 95, 53, 0.06)",
    marginBottom: "20px",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    marginTop: "10px",
  },
  th: {
    textAlign: "left",
    padding: "24px 32px",
    fontSize: "9px",
    fontWeight: "700",
    color: "#477257",
    letterSpacing: "2px",
    textTransform: "uppercase",
    borderBottom: "1px solid rgba(255, 255, 255, 0.05)",
    backgroundColor: "transparent",
  },
  td: {
    padding: "24px 32px",
    verticalAlign: "middle",
    borderBottom: "1px solid rgba(255, 255, 255, 0.02)",
    color: "#111111",
    fontWeight: "500",
    fontSize: "13px",
  },
  buttonPrimary: {
    background: "#18864b",
    color: "#fff",
    border: "none",
    padding: "10px 16px",
    borderRadius: "6px",
    cursor: "pointer",
    fontWeight: "600",
    transition: "background 0.2s",
  },
  buttonPromote: {
    backgroundColor: "#10b981",
    color: "#fff",
    border: "none",
    padding: "6px 12px",
    borderRadius: "6px",
    cursor: "pointer",
    fontWeight: "600",
    fontSize: "12px",
    marginRight: "8px",
    transition: "background 0.2s",
  },
  buttonSuspend: {
    backgroundColor: "#ef4444",
    color: "#fff",
    border: "none",
    padding: "6px 12px",
    borderRadius: "6px",
    cursor: "pointer",
    fontWeight: "600",
    fontSize: "12px",
    transition: "background 0.2s",
  },
  buttonUnsuspend: {
    backgroundColor: "#f59e0b",
    color: "#fff",
    border: "none",
    padding: "6px 12px",
    borderRadius: "6px",
    cursor: "pointer",
    fontWeight: "600",
    fontSize: "12px",
    transition: "background 0.2s",
  },
  formGroup: {
    marginBottom: "15px",
  },
  label: {
    display: "block",
    marginBottom: "5px",
    color: "#94a3b8",
    fontSize: "13px",
    fontWeight: "600",
  },
  input: {
    width: "100%",
    padding: "10px",
    borderRadius: "6px",
    border: "1px solid rgba(255,255,255,0.2)",
    backgroundColor: "rgba(15, 23, 42, 0.5)",
    color: "#fff",
    outline: "none",
    fontSize: "14px",
  },
  badgeSuper: {
    backgroundColor: "rgba(59, 130, 246, 0.2)",
    color: "#60a5fa",
    padding: "4px 8px",
    borderRadius: "32px",
    fontSize: "12px",
    fontWeight: "600",
  },
  badgeAdmin: {
    backgroundColor: "rgba(16, 185, 129, 0.2)",
    color: "#34d399",
    padding: "4px 8px",
    borderRadius: "32px",
    fontSize: "12px",
    fontWeight: "600",
  },
  badgeSuspended: {
    backgroundColor: "rgba(239, 68, 68, 0.2)",
    color: "#f87171",
    padding: "4px 8px",
    borderRadius: "32px",
    fontSize: "12px",
    fontWeight: "600",
    marginLeft: "8px",
  }
};
