export const manageAdminsStyle = {
  container: {
    padding: "16px 24px 40px",
    background: "radial-gradient(circle at 50% -20%, #ffffff 0%, #f6faf7 80%)",
    minHeight: "100vh",
    color: "#111827",
    fontFamily: "Inter, Arial, sans-serif",
    marginLeft: "216px",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "24px",
    borderBottom: "1px solid #d7e5da",
    paddingBottom: "12px",
  },
  title: {
    fontSize: "clamp(24px, 3vw, 32px)",
    fontWeight: "800",
    color: "#111111",
    margin: 0,
  },
  card: {
    backgroundColor: "#ffffff",
    border: "1px solid #dfeae3",
    borderRadius: "14px",
    padding: "20px",
    boxShadow: "0 8px 20px rgba(15, 23, 42, 0.04)",
    marginBottom: "20px",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    marginTop: "10px",
  },
  th: {
    textAlign: "left",
    padding: "14px 20px",
    fontSize: "9px",
    fontWeight: "700",
    color: "#477257",
    letterSpacing: "2px",
    textTransform: "uppercase",
    borderBottom: "1px solid #dfeae3",
    backgroundColor: "#f6faf7",
  },
  td: {
    padding: "18px 20px",
    verticalAlign: "middle",
    borderBottom: "1px solid #edf3ee",
    color: "#111827",
    fontWeight: "500",
    fontSize: "13px",
  },
  buttonPrimary: {
    background: "linear-gradient(135deg, #1a874f 0%, #0f6c3d 100%)",
    color: "#fff",
    border: "none",
    minHeight: "56px",
    padding: "0 20px",
    borderRadius: "6px",
    cursor: "pointer",
    fontWeight: "600",
    fontSize: "14px",
    whiteSpace: "nowrap",
    transition: "all 0.2s ease",
  },
  buttonPromote: {
    backgroundColor: "#1a874f",
    color: "#fff",
    border: "none",
    padding: "6px 12px",
    borderRadius: "6px",
    cursor: "pointer",
    fontWeight: "600",
    fontSize: "12px",
    marginRight: "8px",
    transition: "background 0.2s",
  },
  buttonSuspend: {
    backgroundColor: "#ef4444",
    color: "#fff",
    border: "none",
    padding: "6px 12px",
    borderRadius: "6px",
    cursor: "pointer",
    fontWeight: "600",
    fontSize: "12px",
    transition: "background 0.2s",
  },
  buttonUnsuspend: {
    backgroundColor: "#b45309",
    color: "#fff",
    border: "none",
    padding: "6px 12px",
    borderRadius: "6px",
    cursor: "pointer",
    fontWeight: "600",
    fontSize: "12px",
    transition: "background 0.2s",
  },
  formGroup: {
    marginBottom: "15px",
  },
  label: {
    display: "block",
    marginBottom: "5px",
    color: "#5f7b69",
    fontSize: "13px",
    fontWeight: "600",
  },
  input: {
    width: "100%",
    padding: "10px",
    borderRadius: "6px",
    border: "1px solid #dfeae3",
    backgroundColor: "#fbfdfb",
    color: "#111827",
    outline: "none",
    fontSize: "14px",
  },
  badgeSuper: {
    backgroundColor: "#e0f2fe",
    color: "#0369a1",
    padding: "4px 8px",
    borderRadius: "32px",
    fontSize: "12px",
    fontWeight: "600",
  },
  badgeAdmin: {
    backgroundColor: "#dcfce7",
    color: "#15803d",
    padding: "4px 8px",
    borderRadius: "32px",
    fontSize: "12px",
    fontWeight: "600",
  },
  badgeSuspended: {
    backgroundColor: "#fee2e2",
    color: "#b91c1c",
    padding: "4px 8px",
    borderRadius: "32px",
    fontSize: "12px",
    fontWeight: "600",
    marginLeft: "8px",
  },
  adminForm: {
    display: "flex",
    gap: "15px",
    alignItems: "flex-end",
  },
  textField: {
    "& .MuiFilledInput-root": {
      backgroundColor: "#f6faf7",
      borderRadius: "8px 8px 0 0",
      transition: "transform 180ms ease, background-color 180ms ease, box-shadow 180ms ease",
      "&:before": {
        borderBottom: "1px solid #b8d7c1",
      },
      "&:after": {
        borderBottomColor: "#18864b",
      },
      "&:hover": {
        backgroundColor: "#edf7f0",
        transform: "translateY(-1px)",
        "&:before": {
          borderBottomColor: "#72b889",
        },
      },
      "&:active": {
        transform: "translateY(0) scale(0.99)",
      },
      "&.Mui-focused": {
        backgroundColor: "#f6faf7",
        boxShadow: "0 0 0 2px rgba(24, 134, 75, 0.12)",
        transform: "translateY(-1px)",
      },
    },
    "& .MuiFilledInput-input": {
      color: "#18251d",
      fontSize: "14px",
      fontWeight: 600,
    },
    "& .MuiInputLabel-root": {
      color: "#71897a",
    },
    "&:hover .MuiInputLabel-root": {
      transform: "translate(12px, 7px) scale(0.75)",
      transformOrigin: "top left",
      color: "#177a4a",
    },
    "& .MuiInputLabel-root.Mui-focused": {
      color: "#177a4a",
    },
  },
  sectionTitle: {
    marginTop: 0,
    color: "#111827",
    fontSize: "18px",
    fontWeight: "800",
  },
  activeStatus: {
    color: "#15803d",
    fontSize: "12px",
    fontWeight: "700",
  },
  loadingTitle: {
    color: "#111827",
  },
  loadingScreen: {
    minHeight: "calc(100vh - 56px)",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: "14px",
    color: "#1d7a4d",
    fontSize: "16px",
    fontWeight: "800",
  }
};
