// src/pendingIncidentsStyles.js

const glassPanel = {
  backgroundColor: "rgba(16, 23, 42, 0.6)",
  backdropFilter: "blur(24px) saturate(150%)",
  WebkitBackdropFilter: "blur(24px) saturate(150%)",
  border: "1px solid rgba(255, 255, 255, 0.08)",
  boxShadow: "0 15px 35px 0 rgba(0, 0, 0, 0.5)",
  borderRadius: "24px",
};

export const pendingIncidentsStyles = {
  shell: {
    display: "flex",
    minHeight: "100vh",
    background: "linear-gradient(-45deg, #090a0f, #10172a, #0b1120, #020617)",
    backgroundSize: "400% 400%",
    animation: "gradientBG 15s ease infinite",
    color: "#f8fafc",
    fontFamily: "'Inter', sans-serif",
  },
  main: {
    marginLeft: "260px",
    flex: 1,
    padding: "32px",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "32px",
  },
  pageTitle: {
    fontSize: "32px",
    fontWeight: "900",
    letterSpacing: "-0.5px",
    background: "linear-gradient(90deg, #06b6d4, #3b82f6)",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
    margin: 0,
    textShadow: "0 4px 20px rgba(56,189,248,0.2)",
  },
  subtitle: {
    color: "#94a3b8",
    fontSize: "15px",
    margin: "8px 0 0 0",
    fontWeight: "500",
  },
  badgeTag: {
    backgroundColor: "rgba(56, 189, 248, 0.15)",
    color: "#7dd3fc",
    padding: "6px 14px",
    borderRadius: "12px",
    fontSize: "12px",
    fontWeight: "900",
    border: "1px solid rgba(6, 182, 212, 0.4)",
    boxShadow: "0 0 15px rgba(56,189,248,0.2)",
  },
  soundBtnActive: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    background: "rgba(99, 102, 241, 0.15)",
    border: "1px solid rgba(99, 102, 241, 0.4)",
    color: "#a5b4fc",
    padding: "10px 20px",
    borderRadius: "16px",
    fontSize: "13px",
    fontWeight: "900",
    cursor: "pointer",
    boxShadow: "0 0 20px rgba(99, 102, 241, 0.3)",
  },
  soundBtnMuted: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    background: "rgba(255, 255, 255, 0.05)",
    border: "1px solid rgba(255, 255, 255, 0.1)",
    color: "#94a3b8",
    padding: "10px 20px",
    borderRadius: "16px",
    fontSize: "13px",
    fontWeight: "900",
    cursor: "pointer",
  },
  filterBar: {
    display: "grid",
    gridTemplateColumns: "140px repeat(auto-fit, minmax(200px, 1fr))",
    gap: "16px",
    ...glassPanel,
    padding: "20px 24px",
    marginBottom: "32px",
  },
  filterLabel: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    fontSize: "13px",
    fontWeight: "900",
    color: "#f8fafc",
    textTransform: "uppercase",
    letterSpacing: "0.5px",
  },
  filterSelect: {
    backgroundColor: "rgba(15, 23, 42, 0.8)",
    border: "1px solid rgba(255, 255, 255, 0.1)",
    color: "#ffffff",
    padding: "14px 16px",
    borderRadius: "12px",
    fontSize: "14px",
    fontWeight: "800",
    outline: "none",
  },
  filterInput: {
    backgroundColor: "rgba(15, 23, 42, 0.8)",
    border: "1px solid rgba(255, 255, 255, 0.1)",
    color: "#ffffff",
    padding: "14px 16px",
    borderRadius: "12px",
    fontSize: "14px",
    fontWeight: "800",
    outline: "none",
  },
  cardGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(400px, 1fr))",
    gap: "32px",
  },
  card: {
    ...glassPanel,
    display: "flex",
    flexDirection: "column",
    transition: "transform 0.3s ease",
  },
  cardTopBar: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    padding: "18px 24px",
    borderBottom: "1px solid rgba(255, 255, 255, 0.05)",
  },
  incidentTitle: {
    fontSize: "16px",
    fontWeight: "900",
    color: "#ffffff",
    letterSpacing: "0.5px",
  },
  timeText: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    fontSize: "13px",
    color: "#94a3b8",
    fontWeight: "800",
  },
  cardContent: {
    padding: "24px",
    display: "flex",
    flexDirection: "column",
    gap: "20px",
    flex: 1,
  },
  newBadge: {
    backgroundColor: "#ef4444",
    color: "white",
    padding: "4px 10px",
    borderRadius: "8px",
    fontSize: "11px",
    fontWeight: "900",
    boxShadow: "0 0 15px rgba(239,68,68,0.5)",
    animation: "pulseGlowRed 2s infinite",
  },
  priorityTag: {
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    color: "#f8fafc",
    padding: "6px 12px",
    borderRadius: "8px",
    fontSize: "12px",
    fontWeight: "900",
    border: "1px solid rgba(255, 255, 255, 0.1)",
  },
  verifiedTag: {
    backgroundColor: "rgba(16, 185, 129, 0.15)",
    color: "#34d399",
    padding: "6px 12px",
    borderRadius: "8px",
    fontSize: "12px",
    fontWeight: "900",
    border: "1px solid rgba(16,185,129,0.3)",
    boxShadow: "0 0 15px rgba(16,185,129,0.2)",
  },
  reporterStrip: {
    display: "flex",
    alignItems: "center",
    gap: "14px",
    backgroundColor: "rgba(0,0,0,0.2)",
    padding: "16px",
    borderRadius: "16px",
    border: "1px solid rgba(255, 255, 255, 0.05)",
  },
  reporterName: {
    display: "block",
    fontSize: "16px",
    fontWeight: "900",
    color: "#ffffff",
  },
  reporterSub: {
    fontSize: "13px",
    color: "#94a3b8",
    display: "flex",
    alignItems: "center",
    gap: "8px",
    fontWeight: "700",
  },
  mediaRow: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "16px",
  },
  mediaTile: {
    height: "120px",
    backgroundColor: "rgba(0,0,0,0.3)",
    borderRadius: "16px",
    border: "1px solid rgba(255, 255, 255, 0.05)",
    overflow: "hidden",
    cursor: "pointer",
    position: "relative",
  },
  tileImg: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
  },
  noMediaText: {
    height: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    color: "#64748b",
    fontSize: "12px",
    fontWeight: "800",
    gap: "8px",
  },
  playOverlay: {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    opacity: 0.9,
    filter: "drop-shadow(0 0 10px rgba(0,0,0,0.5))",
  },
  locationBox: {
    display: "flex",
    flexDirection: "column",
    gap: "12px",
  },
  addressText: {
    fontSize: "14px",
    color: "#cbd5e1",
    margin: 0,
    fontWeight: "800",
    display: "flex",
    alignItems: "center",
    gap: "10px",
  },
  miniMapContainer: {
    height: "120px",
    borderRadius: "16px",
    overflow: "hidden",
    position: "relative",
    cursor: "pointer",
    border: "1px solid rgba(255, 255, 255, 0.08)",
  },
  mapHoverTag: {
    position: "absolute",
    bottom: "10px",
    right: "10px",
    backgroundColor: "rgba(15, 23, 42, 0.8)",
    backdropFilter: "blur(8px)",
    color: "#06b6d4",
    padding: "6px 12px",
    borderRadius: "10px",
    fontSize: "11px",
    fontWeight: "900",
    border: "1px solid rgba(6, 182, 212, 0.3)",
  },
  dispatchBox: {
    backgroundColor: "rgba(0,0,0,0.2)",
    border: "1px solid rgba(255, 255, 255, 0.05)",
    padding: "16px",
    borderRadius: "16px",
    display: "flex",
    flexDirection: "column",
    gap: "12px",
  },
  dispatchLabel: {
    fontSize: "12px",
    color: "#94a3b8",
    fontWeight: "900",
    textTransform: "uppercase",
    letterSpacing: "0.5px",
  },
  dispatchSelect: {
    backgroundColor: "rgba(15, 23, 42, 0.8)",
    border: "1px solid rgba(255, 255, 255, 0.1)",
    color: "#ffffff",
    padding: "14px",
    borderRadius: "12px",
    fontSize: "14px",
    fontWeight: "800",
    outline: "none",
  },
  actionRow: {
    display: "flex",
    gap: "16px",
    marginTop: "auto",
  },
  deployBtn: {
    flex: 2,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "10px",
    padding: "16px",
    background: "linear-gradient(135deg, #06b6d4 0%, #0284c7 100%)",
    color: "#ffffff",
    border: "none",
    borderRadius: "16px",
    fontSize: "14px",
    fontWeight: "900",
    cursor: "pointer",
    boxShadow: "0 8px 25px rgba(6, 182, 212, 0.4)",
    transition: "all 0.3s",
  },
  rejectBtn: {
    flex: 1,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "10px",
    padding: "16px",
    background: "linear-gradient(135deg, #f43f5e 0%, #be123c 100%)",
    color: "#ffffff",
    border: "none",
    borderRadius: "16px",
    fontSize: "14px",
    fontWeight: "900",
    cursor: "pointer",
    boxShadow: "0 8px 25px rgba(225, 29, 72, 0.4)",
    transition: "all 0.3s",
  },
  modalBackdrop: {
    position: "fixed",
    inset: 0,
    backgroundColor: "rgba(2, 6, 23, 0.85)",
    zIndex: 9999,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    padding: "40px",
    backdropFilter: "blur(20px)",
  },
  modalWindow: {
    width: "100%",
    maxWidth: "900px",
    ...glassPanel,
  },
  modalHead: {
    padding: "24px 32px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    borderBottom: "1px solid rgba(255, 255, 255, 0.05)",
    backgroundColor: "rgba(255, 255, 255, 0.02)",
  },
  closeBtn: {
    background: "rgba(255, 255, 255, 0.1)",
    border: "1px solid rgba(255,255,255,0.2)",
    color: "#ffffff",
    cursor: "pointer",
    padding: "12px",
    borderRadius: "16px",
    transition: "background 0.3s",
  },
  closeFloatBtn: {
    position: "absolute",
    top: "-20px",
    right: "-20px",
    background: "linear-gradient(135deg, #ef4444 0%, #b91c1c 100%)",
    color: "white",
    border: "none",
    width: "48px",
    height: "48px",
    borderRadius: "50%",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    boxShadow: "0 12px 25px rgba(239, 68, 68, 0.5)",
  },
};
