// src/pendingUsersStyle.js
const glassPanel = {
  backgroundColor: "rgba(16, 23, 42, 0.6)",
  backdropFilter: "blur(24px) saturate(150%)",
  WebkitBackdropFilter: "blur(24px) saturate(150%)",
  border: "1px solid rgba(255, 255, 255, 0.08)",
  boxShadow: "0 15px 35px 0 rgba(0, 0, 0, 0.5)",
  borderRadius: "24px",
};

export const pendingUsersStyle = {
  container: {
    display: "flex",
    minHeight: "100vh",
    background: "linear-gradient(-45deg, #090a0f, #10172a, #0b1120, #020617)",
    backgroundSize: "400% 400%",
    animation: "gradientBG 15s ease infinite",
    color: "#f8fafc",
    fontFamily: "'Inter', sans-serif",
  },
  main: {
    flex: 1,
    padding: "32px",
    marginLeft: "260px",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "32px",
    paddingBottom: "24px",
    borderBottom: "1px solid rgba(255, 255, 255, 0.05)",
  },
  headerTitleGroup: {
    display: "flex",
    alignItems: "center",
    gap: "14px",
  },
  statusDot: {
    width: "12px",
    height: "12px",
    borderRadius: "50%",
    backgroundColor: "#06b6d4",
    boxShadow: "0 0 15px rgba(56, 189, 248, 0.8)",
    animation: "pulseGlowRed 2s infinite",
  },
  title: {
    fontSize: "32px",
    fontWeight: "900",
    letterSpacing: "-0.5px",
    background: "linear-gradient(90deg, #06b6d4, #3b82f6)",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
    margin: 0,
    textShadow: "0 4px 20px rgba(56,189,248,0.2)",
  },
  subtitle: {
    color: "#94a3b8",
    fontSize: "15px",
    margin: "8px 0 0 26px",
    fontWeight: "500",
  },
  headerActions: {
    display: "flex",
    gap: "16px",
  },
  btnSecondary: {
    background: "rgba(255, 255, 255, 0.05)",
    border: "1px solid rgba(255, 255, 255, 0.1)",
    color: "#ffffff",
    padding: "12px 24px",
    borderRadius: "16px",
    cursor: "pointer",
    fontWeight: "900",
    fontSize: "13px",
    transition: "all 0.3s",
  },
  btnBatchApprove: (isDisabled) => ({
    background: isDisabled ? "rgba(255, 255, 255, 0.05)" : "linear-gradient(135deg, #10b981 0%, #047857 100%)",
    color: isDisabled ? "#64748b" : "#ffffff",
    border: isDisabled ? "1px solid rgba(255, 255, 255, 0.1)" : "none",
    padding: "12px 24px",
    borderRadius: "16px",
    cursor: isDisabled ? "not-allowed" : "pointer",
    fontWeight: "900",
    fontSize: "13px",
    display: "flex",
    alignItems: "center",
    gap: "10px",
    opacity: isDisabled ? 0.7 : 1,
    boxShadow: isDisabled ? "none" : "0 8px 25px rgba(16, 185, 129, 0.4)",
    transition: "all 0.3s",
  }),
  emptyState: {
    textAlign: "center",
    padding: "100px 20px",
    ...glassPanel,
    border: "2px dashed rgba(255, 255, 255, 0.1)",
    color: "#94a3b8",
    fontWeight: "700",
    fontSize: "15px",
  },
  cardsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(380px, 1fr))",
    gap: "32px",
  },
  card: (isSelected) => ({
    ...glassPanel,
    border: isSelected ? "2px solid #34d399" : "1px solid rgba(255, 255, 255, 0.08)",
    boxShadow: isSelected ? "0 0 30px rgba(52, 211, 153, 0.2)" : "0 15px 35px 0 rgba(0, 0, 0, 0.5)",
    display: "flex",
    flexDirection: "column",
    position: "relative",
    transition: "all 0.3s ease",
  }),
  cardHeaderStrip: {
    backgroundColor: "rgba(56, 189, 248, 0.1)",
    padding: "20px 24px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    borderBottom: "1px solid rgba(56, 189, 248, 0.2)",
  },
  cardHeaderUser: {
    display: "flex",
    alignItems: "center",
    gap: "14px",
  },
  userName: {
    fontWeight: "900",
    fontSize: "17px",
    color: "#ffffff",
  },
  pendingBadge: {
    fontSize: "12px",
    fontWeight: "900",
    backgroundColor: "rgba(56, 189, 248, 0.2)",
    color: "#7dd3fc",
    padding: "6px 14px",
    borderRadius: "12px",
    border: "1px solid rgba(6, 182, 212, 0.4)",
  },
  cardBody: {
    padding: "24px",
    flex: 1,
    display: "flex",
    flexDirection: "column",
  },
  detailsBox: {
    backgroundColor: "rgba(0,0,0,0.2)",
    padding: "20px",
    borderRadius: "16px",
    border: "1px solid rgba(255, 255, 255, 0.05)",
    marginBottom: "20px",
    display: "grid",
    gap: "12px",
  },
  detailRow: {
    display: "flex",
    justifyContent: "space-between",
    fontSize: "14px",
  },
  detailLabel: {
    color: "#94a3b8",
    fontWeight: "900",
  },
  detailValue: {
    color: "#f8fafc",
    fontWeight: "800",
    textAlign: "right",
  },
  imageGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "16px",
    marginBottom: "24px",
  },
  imageThumb: {
    height: "140px",
    borderRadius: "16px",
    overflow: "hidden",
    border: "1px solid rgba(255, 255, 255, 0.08)",
    position: "relative",
    cursor: "zoom-in",
    backgroundColor: "rgba(0,0,0,0.3)",
  },
  imgCover: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
  },
  imageLabel: {
    position: "absolute",
    bottom: "10px",
    left: "10px",
    backgroundColor: "rgba(15, 23, 42, 0.8)",
    backdropFilter: "blur(8px)",
    color: "#06b6d4",
    padding: "6px 12px",
    borderRadius: "10px",
    fontSize: "11px",
    fontWeight: "900",
    border: "1px solid rgba(6, 182, 212, 0.3)",
  },
  cardActionGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "16px",
    marginTop: "auto",
  },
  btnReject: {
    background: "linear-gradient(135deg, #f43f5e 0%, #be123c 100%)",
    color: "white",
    border: "none",
    padding: "16px",
    borderRadius: "16px",
    fontWeight: "900",
    fontSize: "14px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "10px",
    boxShadow: "0 8px 25px rgba(225, 29, 72, 0.4)",
    transition: "all 0.3s",
  },
  btnApprove: {
    background: "linear-gradient(135deg, #10b981 0%, #047857 100%)",
    color: "white",
    border: "none",
    padding: "16px",
    borderRadius: "16px",
    fontWeight: "900",
    fontSize: "14px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "10px",
    boxShadow: "0 8px 25px rgba(16, 185, 129, 0.4)",
    transition: "all 0.3s",
  },
  modalBackdrop: {
    position: "fixed",
    inset: 0,
    backgroundColor: "rgba(2, 6, 23, 0.85)",
    zIndex: 9999,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    padding: "32px",
    backdropFilter: "blur(20px)",
  },
  rejectionModalCard: {
    ...glassPanel,
    width: "100%",
    maxWidth: "520px",
    padding: "40px",
  },
  rejectionHeader: {
    display: "flex",
    alignItems: "center",
    gap: "14px",
    marginBottom: "24px",
    fontSize: "20px",
    fontWeight: "900",
    color: "#fca5a5",
  },
  textarea: {
    width: "100%",
    height: "140px",
    padding: "20px",
    borderRadius: "16px",
    border: "1px solid rgba(255, 255, 255, 0.1)",
    backgroundColor: "rgba(15, 23, 42, 0.8)",
    color: "#ffffff",
    fontSize: "15px",
    marginBottom: "32px",
    outline: "none",
    boxSizing: "border-box",
    fontWeight: "600",
  },
  modalActionRow: {
    display: "flex",
    gap: "16px",
  },
  btnModalCancel: {
    flex: 1,
    padding: "16px",
    borderRadius: "16px",
    border: "1px solid rgba(255,255,255,0.2)",
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    color: "#f8fafc",
    fontWeight: "900",
    cursor: "pointer",
    transition: "all 0.3s",
  },
  btnModalConfirmReject: {
    flex: 1,
    padding: "16px",
    borderRadius: "16px",
    border: "none",
    background: "linear-gradient(135deg, #ef4444 0%, #b91c1c 100%)",
    color: "white",
    fontWeight: "900",
    cursor: "pointer",
    boxShadow: "0 8px 25px rgba(239, 68, 68, 0.4)",
    transition: "all 0.3s",
  },
  previewModalCard: {
    width: "min(1200px, 95vw)",
    maxHeight: "90vh",
    overflow: "auto",
    ...glassPanel,
    padding: "40px",
  },
  previewHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: "32px",
  },
  btnCloseIcon: {
    background: "rgba(255, 255, 255, 0.1)",
    border: "1px solid rgba(255,255,255,0.2)",
    color: "#ffffff",
    width: "48px",
    height: "48px",
    borderRadius: "16px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    transition: "all 0.3s",
  },
  previewPhotoGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "24px",
    marginBottom: "32px",
  },
  photoBox: {
    backgroundColor: "rgba(0,0,0,0.2)",
    padding: "20px",
    borderRadius: "24px",
    border: "1px solid rgba(255, 255, 255, 0.05)",
  },
  photoBoxLabel: {
    fontSize: "13px",
    fontWeight: "900",
    color: "#06b6d4",
    display: "block",
    marginBottom: "16px",
    textTransform: "uppercase",
  },
  previewImg: {
    width: "100%",
    height: "360px",
    objectFit: "cover",
    borderRadius: "16px",
  },
  profileFieldsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(240px, 1fr))",
    gap: "20px",
    backgroundColor: "rgba(0,0,0,0.2)",
    padding: "24px",
    borderRadius: "24px",
    border: "1px solid rgba(255, 255, 255, 0.05)",
  },
  fieldLabel: {
    fontSize: "12px",
    color: "#94a3b8",
    fontWeight: "900",
    display: "block",
    textTransform: "uppercase",
    letterSpacing: "0.5px",
  },
  fieldValue: {
    fontSize: "15px",
    color: "#ffffff",
    fontWeight: "800",
    marginTop: "6px",
  },
  overlayBackdrop: {
    position: "fixed",
    inset: 0,
    zIndex: 1200,
    backgroundColor: "rgba(2, 6, 23, 0.85)",
    backdropFilter: "blur(20px)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "32px",
  },
  overlayCard: {
    width: "min(460px, 100%)",
    ...glassPanel,
    padding: "40px",
    display: "grid",
    justifyItems: "center",
    textAlign: "center",
    gap: "20px",
  },
  spinner: {
    width: "64px",
    height: "64px",
    borderRadius: "50%",
    border: "4px solid rgba(255, 255, 255, 0.1)",
    borderTopColor: "#34d399",
    animation: "spin 1s cubic-bezier(0.5,0,0.5,1) infinite",
  },
};
