// src/pendingUsersStyle.js
const glassPanel = {
  backgroundColor: "#ffffff",
  border: "1px solid #dfeae3",
  boxShadow: "0 8px 20px rgba(15, 23, 42, 0.04)",
  borderRadius: "14px",
};

export const pendingUsersStyle = {
  container: {
    display: "flex",
    minHeight: "100vh",
    background: "radial-gradient(circle at 50% -20%, #ffffff 0%, #f6faf7 80%)",
    color: "#111827",
    fontFamily: "Inter, Arial, sans-serif",
  },
  main: {
    flex: 1,
    padding: "28px 24px 40px",
    marginLeft: "216px",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "24px",
    paddingBottom: "14px",
    borderBottom: "1px solid #dfeae3",
  },
  headerTitleGroup: {
    display: "flex",
    alignItems: "center",
    gap: "14px",
  },
  statusDot: {
    width: "12px",
    height: "12px",
    borderRadius: "50%",
    backgroundColor: "#1d7a4d",
    boxShadow: "0 0 15px rgba(29, 122, 77, 0.28)",
    animation: "pulseGlowRed 2s infinite",
  },
  title: {
    fontSize: "clamp(24px, 3vw, 32px)",
    fontWeight: "800",
    letterSpacing: "-0.03em",
    color: "#111111",
    margin: 0,

  },
  subtitle: {
    fontSize: "15px",
    margin: "8px 0 0 0",
    fontWeight: "600",
    color: "#477257",
    textTransform: "none",
    letterSpacing: "0.3px",
  },
  headerActions: {
    display: "flex",
    gap: "16px",
  },
  btnSecondary: {
    background: "#ffffff",
    border: "1px solid #dfeae3",
    color: "#111827",
    padding: "12px 20px",
    borderRadius: "999px",
    cursor: "pointer",
    fontWeight: "800",
    fontSize: "13px",
    transition: "all 0.3s",
  },
  btnBatchApprove: (isDisabled) => ({
    background: isDisabled ? "linear-gradient(135deg, #dfe9e2 0%, #d2ddd5 100%)" : "linear-gradient(135deg, #1a874f 0%, #0f6c3d 100%)",
    color: isDisabled ? "#6d7d73" : "#ffffff",
    border: "none",
    padding: "12px 24px",
    borderRadius: "10px",
    cursor: isDisabled ? "not-allowed" : "pointer",
    fontWeight: "900",
    fontSize: "13px",
    display: "flex",
    alignItems: "center",
    gap: "10px",
    opacity: 1,
    boxShadow: isDisabled ? "none" : "0 8px 18px rgba(24, 95, 53, 0.16)",
    transition: "all 0.3s",
  }),
  emptyState: {
    textAlign: "center",
    padding: "100px 20px",
    ...glassPanel,
    border: "1px dashed #dfeae3",
    color: "#5f7b69",
    fontWeight: "700",
    fontSize: "15px",
  },
  loadingState: {
    minHeight: "260px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: "14px",
    color: "#1d7a4d",
    fontSize: "16px",
    fontWeight: "800",
  },
  cardsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(380px, 1fr))",
    gap: "24px",
  },
  card: (isSelected) => ({
    ...glassPanel,
    border: isSelected ? "2px solid #34d399" : "1px solid rgba(255, 255, 255, 0.08)",
    boxShadow: isSelected ? "0 0 30px rgba(52, 211, 153, 0.2)" : "0 15px 35px 0 rgba(0, 0, 0, 0.5)",
    display: "flex",
    flexDirection: "column",
    position: "relative",
    transition: "all 0.3s ease",
  }),
  cardHeaderStrip: {
    backgroundColor: "rgba(56, 189, 248, 0.1)",
    padding: "20px 24px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    borderBottom: "1px solid rgba(56, 189, 248, 0.2)",
  },
  cardHeaderUser: {
    display: "flex",
    alignItems: "center",
    gap: "14px",
  },
  userName: {
    fontWeight: "900",
    fontSize: "17px",
    color: "#ffffff",
  },
  pendingBadge: {
    fontSize: "12px",
    fontWeight: "900",
    backgroundColor: "rgba(56, 189, 248, 0.2)",
    color: "#7dd3fc",
    padding: "6px 14px",
    borderRadius: "32px",
    border: "1px solid rgba(6, 182, 212, 0.4)",
  },
  cardBody: {
    padding: "clamp(32px, 5vw, 64px)",
    flex: 1,
    display: "flex",
    flexDirection: "column",
  },
  detailsBox: {
    backgroundColor: "rgba(0,0,0,0.2)",
    padding: "20px",
    borderRadius: "32px",
    border: "1px solid rgba(255, 255, 255, 0.08)",
    marginBottom: "20px",
    display: "grid",
    gap: "12px",
  },
  detailRow: {
    display: "flex",
    justifyContent: "space-between",
    fontSize: "14px",
  },
  detailLabel: {
    color: "#94a3b8",
    fontWeight: "900",
  },
  detailValue: {
    color: "#f8fafc",
    fontWeight: "800",
    textAlign: "right",
  },
  imageGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "16px",
    marginBottom: "24px",
  },
  imageThumb: {
    height: "140px",
    borderRadius: "32px",
    overflow: "hidden",
    border: "1px solid rgba(255, 255, 255, 0.08)",
    position: "relative",
    cursor: "zoom-in",
    backgroundColor: "rgba(0,0,0,0.3)",
  },
  imgCover: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
  },
  imageLabel: {
    position: "absolute",
    bottom: "10px",
    left: "10px",
    backgroundColor: "rgba(15, 23, 42, 0.7)",
    backdropFilter: "blur(40px)",
    WebkitBackdropFilter: "blur(40px)",
    
    color: "#06b6d4",
    padding: "6px 12px",
    borderRadius: "10px",
    fontSize: "11px",
    fontWeight: "900",
    border: "1px solid rgba(6, 182, 212, 0.3)",
  },
  cardActionGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "16px",
    marginTop: "auto",
  },
  btnReject: {
    background: "radial-gradient(circle at 50% -20%, #1e293b 0%, #020617 80%)",
    color: "white",
    border: "none",
    padding: "16px",
    borderRadius: "32px",
    fontWeight: "900",
    fontSize: "14px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "10px",
    boxShadow: "0 15px 35px 0 rgba(0, 0, 0, 0.5)",
    transition: "all 0.3s",
  },
  btnApprove: {
    background: "radial-gradient(circle at 50% -20%, #1e293b 0%, #020617 80%)",
    color: "white",
    border: "none",
    padding: "16px",
    borderRadius: "32px",
    fontWeight: "900",
    fontSize: "14px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "10px",
    boxShadow: "0 15px 35px 0 rgba(0, 0, 0, 0.5)",
    transition: "all 0.3s",
  },
  modalBackdrop: {
    position: "fixed",
    inset: 0,
    backgroundColor: "rgba(2, 6, 23, 0.85)",
    zIndex: 9999,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    padding: "clamp(32px, 5vw, 64px)",
    
  },
  rejectionModalCard: {
    ...glassPanel,
    width: "100%",
    maxWidth: "520px",
    padding: "40px",
  },
  rejectionHeader: {
    display: "flex",
    alignItems: "center",
    gap: "14px",
    marginBottom: "24px",
    fontSize: "20px",
    fontWeight: "900",
    color: "#fca5a5",
  },
  textarea: {
    width: "100%",
    height: "140px",
    padding: "20px",
    borderRadius: "32px",
    border: "1px solid rgba(255, 255, 255, 0.1)",
    backgroundColor: "rgba(15, 23, 42, 0.7)",
    backdropFilter: "blur(40px)",
    WebkitBackdropFilter: "blur(40px)",
    color: "#ffffff",
    fontSize: "15px",
    marginBottom: "32px",
    outline: "none",
    boxSizing: "border-box",
    fontWeight: "600",
  },
  modalActionRow: {
    display: "flex",
    gap: "16px",
  },
  btnModalCancel: {
    flex: 1,
    padding: "16px",
    borderRadius: "32px",
    border: "1px solid rgba(255,255,255,0.2)",
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    color: "#f8fafc",
    fontWeight: "900",
    cursor: "pointer",
    transition: "all 0.3s",
  },
  btnModalConfirmReject: {
    flex: 1,
    padding: "16px",
    borderRadius: "32px",
    border: "none",
    background: "radial-gradient(circle at 50% -20%, #1e293b 0%, #020617 80%)",
    color: "white",
    fontWeight: "900",
    cursor: "pointer",
    boxShadow: "0 15px 35px 0 rgba(0, 0, 0, 0.5)",
    transition: "all 0.3s",
  },
  previewModalCard: {
    width: "min(1200px, 95vw)",
    maxHeight: "90vh",
    overflow: "auto",
    ...glassPanel,
    padding: "40px",
  },
  previewHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: "32px",
  },
  btnCloseIcon: {
    background: "rgba(255, 255, 255, 0.1)",
    border: "1px solid rgba(255,255,255,0.2)",
    color: "#ffffff",
    width: "48px",
    height: "48px",
    borderRadius: "32px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    transition: "all 0.3s",
  },
  previewPhotoGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "24px",
    marginBottom: "32px",
  },
  photoBox: {
    backgroundColor: "rgba(0,0,0,0.2)",
    padding: "20px",
    borderRadius: "32px",
    border: "1px solid rgba(255, 255, 255, 0.08)",
  },
  photoBoxLabel: {
    fontSize: "13px",
    fontWeight: "900",
    color: "#06b6d4",
    display: "block",
    marginBottom: "16px",
    textTransform: "uppercase",
  },
  previewImg: {
    width: "100%",
    height: "360px",
    objectFit: "cover",
    borderRadius: "32px",
  },
  profileFieldsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(240px, 1fr))",
    gap: "20px",
    backgroundColor: "rgba(0,0,0,0.2)",
    padding: "clamp(32px, 5vw, 64px)",
    borderRadius: "32px",
    border: "1px solid rgba(255, 255, 255, 0.08)",
  },
  fieldLabel: {
    fontSize: "12px",
    color: "#94a3b8",
    fontWeight: "900",
    display: "block",
    textTransform: "uppercase",
    letterSpacing: "0.5px",
  },
  fieldValue: {
    fontSize: "15px",
    color: "#ffffff",
    fontWeight: "800",
    marginTop: "6px",
  },
  overlayBackdrop: {
    position: "fixed",
    inset: 0,
    zIndex: 1200,
    backgroundColor: "rgba(2, 6, 23, 0.85)",
    
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "clamp(32px, 5vw, 64px)",
  },
  overlayCard: {
    width: "min(460px, 100%)",
    ...glassPanel,
    padding: "40px",
    display: "grid",
    justifyItems: "center",
    textAlign: "center",
    gap: "20px",
  },
  spinner: {
    width: "64px",
    height: "64px",
    borderRadius: "50%",
    border: "4px solid rgba(255, 255, 255, 0.1)",
    borderTopColor: "#34d399",
    animation: "spin 1s cubic-bezier(0.5,0,0.5,1) infinite",
  },
};
