// src/pendingIncidentsStyles.js

if (typeof document !== "undefined" && !document.getElementById("pending-report-motion")) {
  const style = document.createElement("style");
  style.id = "pending-report-motion";
  style.textContent = `
    .pending-report-action {
      transition: transform 180ms ease, box-shadow 180ms ease, background-color 180ms ease !important;
    }
    .pending-report-action:hover:not(:disabled) {
      transform: translateY(-2px);
      box-shadow: 0 8px 16px rgba(24, 95, 53, 0.16);
    }
    .pending-report-action:active:not(:disabled) {
      transform: translateY(1px) scale(0.98);
      box-shadow: 0 3px 8px rgba(24, 95, 53, 0.12);
    }
    .pending-report-action:focus-visible {
      outline: 3px solid rgba(24, 134, 75, 0.25);
      outline-offset: 2px;
    }
  `;
  document.head.appendChild(style);
}

const glassPanel = {
  backgroundColor: "#ffffff",
  border: "1px solid #d7e5da",
  boxShadow: "0 8px 24px rgba(24, 95, 53, 0.06)",
  borderRadius: "12px",
};

export const pendingIncidentsStyles = {
  shell: {
    display: "flex",
    minHeight: "100vh",
    background: "radial-gradient(circle at 50% -20%, #ffffff 0%, #f6faf7 80%)",
    color: "#111111",
    fontFamily: "Inter, Arial, sans-serif",
  },
  main: {
    marginLeft: "216px",
    flex: 1,
    padding: "28px 24px 40px",
    minWidth: 0,
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "20px",
  },
  pageTitle: {
    fontFamily: "Inter, Arial, sans-serif",
    fontSize: "32px",
    fontWeight: "800",
    color: "#111111",
    letterSpacing: "0",
    margin: 0,
    textTransform: "capitalize",
  },
  subtitle: {
    fontSize: "10px",
    margin: "8px 0 0 0",
    fontWeight: "600",
    color: "#477257",
    textTransform: "none",
    letterSpacing: "0.3px",
  },
  badgeTag: {
    backgroundColor: "#e7f5eb",
    color: "#18864b",
    padding: "5px 10px",
    borderRadius: "7px",
    fontSize: "12px",
    fontWeight: "900",
    border: "1px solid #b8d7c1",
    boxShadow: "none",
  },
  soundBtnActive: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    background: "rgba(99, 102, 241, 0.15)",
    border: "1px solid rgba(99, 102, 241, 0.4)",
    color: "#a5b4fc",
    padding: "10px 20px",
    borderRadius: "32px",
    fontSize: "13px",
    fontWeight: "900",
    cursor: "pointer",
    boxShadow: "0 0 20px rgba(99, 102, 241, 0.3)",
  },
  soundBtnMuted: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    background: "rgba(255, 255, 255, 0.05)",
    border: "1px solid rgba(255, 255, 255, 0.1)",
    color: "#94a3b8",
    padding: "10px 20px",
    borderRadius: "32px",
    fontSize: "13px",
    fontWeight: "900",
    cursor: "pointer",
  },
  filterBar: {
    display: "grid",
    gridTemplateColumns: "140px repeat(auto-fit, minmax(180px, 1fr))",
    gap: "10px",
    ...glassPanel,
    padding: "12px 14px",
    marginBottom: "20px",
  },
  filterLabel: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    fontSize: "13px",
    fontWeight: "900",
    color: "#111111",
    textTransform: "uppercase",
    letterSpacing: "0.5px",
  },
  filterSelect: {
    backgroundColor: "#fbfefc",
    border: "1px solid #c8ddce",
    color: "#111111",
    padding: "11px 12px",
    borderRadius: "7px",
    fontSize: "14px",
    fontWeight: "800",
    outline: "none",
  },
  filterInput: {
    backgroundColor: "#fbfefc",
    border: "1px solid #c8ddce",
    color: "#111111",
    padding: "11px 12px",
    borderRadius: "7px",
    fontSize: "14px",
    fontWeight: "800",
    outline: "none",
  },
  cardGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(360px, 1fr))",
    gap: "16px",
  },
  emptyReportsState: {
    gridColumn: "1 / -1",
    minHeight: "220px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
    padding: "32px",
    border: "1px solid #d7e5da",
    borderRadius: "12px",
    backgroundColor: "#ffffff",
    color: "#18864b",
    boxShadow: "0 8px 24px rgba(24, 95, 53, 0.06)",
    textAlign: "center",
    boxSizing: "border-box",
  },
  card: {
    ...glassPanel,
    borderRadius: "14px",
    overflow: "hidden",
    display: "flex",
    flexDirection: "column",
    transition: "transform 0.2s ease, box-shadow 0.2s ease, border-color 0.2s ease",
  },
  cardTopBar: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#f6faf7",
    padding: "14px 18px",
    borderBottom: "1px solid #d7e5da",
    borderTopLeftRadius: "12px",
    borderTopRightRadius: "12px",
  },
  incidentTitle: {
    fontSize: "16px",
    fontWeight: "900",
    color: "#111111",
    letterSpacing: "0.5px",
  },
  timeText: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    fontSize: "13px",
    color: "#477257",
    fontWeight: "800",
  },
  cardContent: {
    padding: "20px",
    display: "flex",
    flexDirection: "column",
    gap: "20px",
    flex: 1,
  },
  newBadge: {
    backgroundColor: "#ef4444",
    color: "white",
    padding: "4px 10px",
    borderRadius: "8px",
    fontSize: "11px",
    fontWeight: "900",
    boxShadow: "0 0 15px rgba(239,68,68,0.5)",
    animation: "pulseGlowRed 2s infinite",
  },
  priorityTag: {
    backgroundColor: "#f6faf7",
    color: "#111111",
    padding: "5px 10px",
    borderRadius: "6px",
    fontSize: "12px",
    fontWeight: "900",
    border: "1px solid rgba(255, 255, 255, 0.1)",
  },
  verifiedTag: {
    backgroundColor: "#e7f5eb",
    color: "#18864b",
    padding: "5px 10px",
    borderRadius: "6px",
    fontSize: "12px",
    fontWeight: "900",
    border: "1px solid #b8d7c1",
    boxShadow: "none",
  },
  reporterStrip: {
    display: "flex",
    alignItems: "center",
    gap: "14px",
    backgroundColor: "#f6faf7",
    padding: "12px",
    borderRadius: "8px",
    border: "1px solid #d7e5da",
  },
  reporterName: {
    display: "block",
    fontSize: "16px",
    fontWeight: "900",
    color: "#111111",
  },
  reporterSub: {
    fontSize: "13px",
    color: "#477257",
    display: "flex",
    alignItems: "center",
    gap: "8px",
    fontWeight: "700",
  },
  mediaRow: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "16px",
  },
  mediaTile: {
    height: "120px",
    backgroundColor: "#eef6f0",
    borderRadius: "8px",
    border: "1px solid #d7e5da",
    overflow: "hidden",
    cursor: "pointer",
    position: "relative",
  },
  tileImg: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
  },
  noMediaText: {
    height: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    color: "#477257",
    fontSize: "12px",
    fontWeight: "800",
    gap: "8px",
  },
  playOverlay: {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    opacity: 0.9,
    filter: "drop-shadow(0 0 10px rgba(0,0,0,0.5))",
  },
  locationBox: {
    display: "flex",
    flexDirection: "column",
    gap: "12px",
  },
  addressText: {
    fontSize: "14px",
    color: "#111111",
    margin: 0,
    fontWeight: "800",
    display: "flex",
    alignItems: "center",
    gap: "10px",
  },
  miniMapContainer: {
    height: "120px",
    borderRadius: "8px",
    overflow: "hidden",
    position: "relative",
    cursor: "pointer",
    border: "1px solid #d7e5da",
  },
  mapHoverTag: {
    position: "absolute",
    bottom: "10px",
    right: "10px",
    backgroundColor: "#ffffff",
    color: "#18864b",
    padding: "6px 12px",
    borderRadius: "10px",
    fontSize: "11px",
    fontWeight: "900",
    border: "1px solid #b8d7c1",
  },
  dispatchBox: {
    backgroundColor: "#f6faf7",
    border: "1px solid #d7e5da",
    padding: "12px",
    borderRadius: "8px",
    display: "flex",
    flexDirection: "column",
    gap: "12px",
  },
  dispatchLabel: {
    fontSize: "12px",
    color: "#477257",
    fontWeight: "900",
    textTransform: "uppercase",
    letterSpacing: "0.5px",
  },
  dispatchSelect: {
    backgroundColor: "#ffffff",
    border: "1px solid #c8ddce",
    color: "#111111",
    padding: "11px 12px",
    borderRadius: "7px",
    fontSize: "14px",
    fontWeight: "800",
    outline: "none",
  },
  responderList: {
    maxHeight: "120px",
    overflowY: "auto",
    border: "1px solid #d7e5da",
    borderRadius: "6px",
    padding: "4px",
    backgroundColor: "#ffffff",
  },
  responderEmpty: {
    padding: "8px",
    fontSize: "12px",
    color: "#477257",
  },
  responderOption: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "6px 8px",
    cursor: "pointer",
    backgroundColor: "transparent",
    borderRadius: "4px",
    marginBottom: "2px",
  },
  responderOptionSelected: {
    backgroundColor: "#e7f5eb",
  },
  responderName: {
    fontSize: "12px",
    color: "#111111",
    fontWeight: "400",
  },
  responderNameSelected: {
    color: "#18864b",
    fontWeight: "600",
  },
  actionRow: {
    display: "flex",
    gap: "16px",
    marginTop: "auto",
  },
  actionButtonContent: {
    position: "relative",
    zIndex: 1,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "10px",
  },
  actionButtonReveal: {
    position: "absolute",
    inset: 0,
    zIndex: 2,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "10px",
    backgroundColor: "#0d5f35",
    color: "#ffffff",
    transition: "clip-path 450ms ease-in-out, -webkit-clip-path 450ms ease-in-out",
    pointerEvents: "none",
  },
  deployBtn: {
    flex: 2,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "10px",
    padding: "16px",
    background: "#18864b",
    color: "#ffffff",
    border: "none",
    borderRadius: "7px",
    fontSize: "14px",
    fontWeight: "900",
    cursor: "pointer",
    boxShadow: "0 8px 18px rgba(24, 95, 53, 0.14)",
    transition: "all 0.3s",
  },
  rejectBtn: {
    flex: 1,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "10px",
    padding: "16px",
    background: "#111111",
    color: "#ffffff",
    border: "none",
    borderRadius: "7px",
    fontSize: "14px",
    fontWeight: "900",
    cursor: "pointer",
    boxShadow: "0 8px 18px rgba(0, 0, 0, 0.14)",
    transition: "all 0.3s",
  },
  modalBackdrop: {
    position: "fixed",
    inset: 0,
    backgroundColor: "rgba(0, 0, 0, 0.48)",
    zIndex: 9999,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    padding: "24px",
  },
  modalWindow: {
    width: "100%",
    maxWidth: "900px",
    ...glassPanel,
  },
  modalHead: {
    padding: "18px 22px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    borderBottom: "1px solid #d7e5da",
    backgroundColor: "#f6faf7",
  },
  closeBtn: {
    background: "#ffffff",
    border: "1px solid #b8d7c1",
    color: "#18864b",
    cursor: "pointer",
    padding: "12px",
    borderRadius: "7px",
    transition: "background 0.3s",
  },
  closeFloatBtn: {
    position: "absolute",
    top: "-20px",
    right: "-20px",
    background: "#18864b",
    color: "white",
    border: "none",
    width: "48px",
    height: "48px",
    borderRadius: "50%",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    boxShadow: "0 8px 18px rgba(24, 95, 53, 0.14)",
  },
  detailBackdrop: {
    position: "fixed",
    inset: 0,
    zIndex: 9000,
    overflowY: "auto",
    padding: "24px",
    backgroundColor: "rgba(0, 0, 0, 0.48)",
  },
  detailWindow: {
    width: "100%",
    maxWidth: "1100px",
    margin: "0 auto",
    overflow: "hidden",
    border: "1px solid #d7e5da",
    borderRadius: "12px",
    backgroundColor: "#f6faf7",
    boxShadow: "0 20px 50px rgba(0, 0, 0, 0.18)",
  },
  detailHeader: {
    display: "flex",
    alignItems: "center",
    gap: "20px",
    minHeight: "58px",
    padding: "0 20px",
    borderBottom: "1px solid #d7e5da",
    backgroundColor: "#ffffff",
  },
  backButton: {
    display: "flex",
    alignItems: "center",
    gap: "5px",
    padding: "7px 0",
    border: "none",
    backgroundColor: "transparent",
    color: "#477257",
    cursor: "pointer",
    fontSize: "12px",
  },
  detailHeaderTitle: {
    display: "flex",
    alignItems: "baseline",
    gap: "6px",
    flex: 1,
    color: "#111111",
    fontSize: "16px",
    fontWeight: "800",
  },
  detailStatus: {
    padding: "5px 10px",
    borderRadius: "99px",
    backgroundColor: "#e7f5eb",
    color: "#18864b",
    fontSize: "10px",
    fontWeight: "700",
  },
  detailBody: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) 280px",
    gap: "16px",
    padding: "16px",
  },
  detailMainColumn: {
    display: "flex",
    flexDirection: "column",
    gap: "16px",
    minWidth: 0,
  },
  detailSideColumn: {
    minWidth: 0,
  },
  detailPanel: {
    padding: "16px",
    border: "1px solid #d7e5da",
    borderRadius: "10px",
    backgroundColor: "#ffffff",
  },
  detailSectionHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "12px",
  },
  detailSectionTitle: {
    margin: "0 0 14px",
    color: "#477257",
    fontSize: "11px",
    fontWeight: "800",
    letterSpacing: "0.3px",
    textTransform: "uppercase",
  },
  reporterDetail: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
  },
  reporterAvatar: {
    width: "42px",
    height: "42px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "50%",
    backgroundColor: "#e7f5eb",
    color: "#18864b",
  },
  detailContactRow: {
    display: "flex",
    gap: "28px",
    marginTop: "16px",
    paddingTop: "12px",
    borderTop: "1px solid #edf3ee",
    color: "#111111",
    fontSize: "12px",
  },
  detailContactLabel: {
    display: "block",
    marginBottom: "3px",
    color: "#477257",
    fontSize: "9px",
    fontWeight: "700",
    textTransform: "uppercase",
  },
  metadataGrid: {
    display: "grid",
    gridTemplateColumns: "80px minmax(0, 1fr)",
    gap: "10px 12px",
    color: "#111111",
    fontSize: "12px",
  },
  metadataLabel: {
    color: "#477257",
  },
  detailMediaGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "12px",
  },
  detailMedia: {
    width: "100%",
    height: "170px",
    display: "block",
    objectFit: "cover",
    borderRadius: "7px",
    backgroundColor: "#eef6f0",
  },
  detailMediaEmpty: {
    height: "170px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
    borderRadius: "7px",
    backgroundColor: "#eef6f0",
    color: "#477257",
    fontSize: "11px",
  },
  detailMapButton: {
    marginBottom: "14px",
    padding: "0",
    border: "none",
    backgroundColor: "transparent",
    color: "#18864b",
    cursor: "pointer",
    fontSize: "10px",
    fontWeight: "700",
  },
  detailMapPreview: {
    height: "180px",
    overflow: "hidden",
    border: "1px solid #d7e5da",
    borderRadius: "7px",
  },
  detailMapFrame: {
    width: "100%",
    height: "100%",
    border: 0,
  },
  detailActionPanel: {
    position: "sticky",
    top: "0",
    paddingBottom: "16px",
    border: "1px solid #d7e5da",
    borderRadius: "10px",
    backgroundColor: "#ffffff",
    overflow: "hidden",
  },
  detailActionTitle: {
    margin: 0,
    padding: "14px 16px 2px",
    backgroundColor: "#18864b",
    color: "#ffffff",
    fontSize: "15px",
  },
  detailActionSubtitle: {
    margin: 0,
    padding: "0 16px 14px",
    backgroundColor: "#18864b",
    color: "#dff4e5",
    fontSize: "10px",
  },
  detailFieldLabel: {
    margin: "16px 16px 8px",
    color: "#477257",
    fontSize: "10px",
    textTransform: "uppercase",
  },
  detailResponderList: {
    maxHeight: "350px",
    margin: "0 16px 16px",
    overflowY: "auto",
    border: "1px solid #d7e5da",
    borderRadius: "7px",
  },
  detailResponderOption: {
    display: "flex",
    alignItems: "flex-start",
    gap: "8px",
    padding: "9px 10px",
    borderBottom: "1px solid #edf3ee",
    color: "#111111",
    cursor: "pointer",
    fontSize: "11px",
  },
};
