// src/pendingIncidentsStyles.js

export const pendingIncidentsStyles = {
  shell: {
    display: "flex",
    minHeight: "100vh",
    backgroundColor: "#080c14",
    color: "#f8fafc",
    fontFamily: "Inter, system-ui, sans-serif",
  },
  main: {
    marginLeft: "260px",
    flex: 1,
    padding: "28px",
    backgroundColor: "#080c14",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "20px",
  },
  pageTitle: {
    fontSize: "24px",
    fontWeight: 800,
    margin: 0,
    color: "#f8fafc",
    letterSpacing: "-0.5px",
  },
  subtitle: {
    color: "#94a3b8",
    fontSize: "12px",
    margin: "4px 0 0 0",
  },
  badgeTag: {
    backgroundColor: "#1e293b",
    color: "#38bdf8",
    padding: "3px 8px",
    borderRadius: "4px",
    fontSize: "10px",
    fontWeight: 800,
    border: "1px solid #0284c7",
  },
  soundBtnActive: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    backgroundColor: "#1e1b4b",
    border: "1px solid #4338ca",
    color: "#a5b4fc",
    padding: "6px 12px",
    borderRadius: "6px",
    fontSize: "11px",
    fontWeight: 700,
    cursor: "pointer",
  },
  soundBtnMuted: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    backgroundColor: "#1f2937",
    border: "1px solid #374151",
    color: "#9ca3af",
    padding: "6px 12px",
    borderRadius: "6px",
    fontSize: "11px",
    fontWeight: 700,
    cursor: "pointer",
  },
  filterBar: {
    display: "grid",
    gridTemplateColumns: "130px repeat(auto-fit, minmax(160px, 1fr))",
    gap: "10px",
    backgroundColor: "#0f172a",
    padding: "10px 14px",
    borderRadius: "8px",
    border: "1px solid #1e293b",
    marginBottom: "24px",
  },
  filterLabel: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    fontSize: "11px",
    fontWeight: 800,
    color: "#94a3b8",
  },
  filterSelect: {
    backgroundColor: "#1e293b",
    border: "1px solid #334155",
    color: "#f8fafc",
    padding: "6px 10px",
    borderRadius: "6px",
    fontSize: "12px",
  },
  filterInput: {
    backgroundColor: "#1e293b",
    border: "1px solid #334155",
    color: "#f8fafc",
    padding: "6px 10px",
    borderRadius: "6px",
    fontSize: "12px",
  },
  cardGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(360px, 1fr))",
    gap: "20px",
  },
  card: {
    backgroundColor: "#0f172a",
    borderRadius: "10px",
    border: "1px solid #1e293b",
    overflow: "hidden",
    display: "flex",
    flexDirection: "column",
  },
  cardTopBar: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#1e293b",
    padding: "10px 14px",
    borderBottom: "1px solid #334155",
  },
  incidentTitle: {
    fontSize: "14px",
    fontWeight: 800,
    color: "#f8fafc",
  },
  timeText: {
    display: "flex",
    alignItems: "center",
    gap: "4px",
    fontSize: "11px",
    color: "#94a3b8",
    fontWeight: 700,
  },
  cardContent: {
    padding: "14px",
    display: "flex",
    flexDirection: "column",
    gap: "12px",
    flex: 1,
  },
  newBadge: {
    backgroundColor: "#dc2626",
    color: "#fff",
    padding: "2px 6px",
    borderRadius: "4px",
    fontSize: "9px",
    fontWeight: 900,
  },
  priorityTag: {
    backgroundColor: "#334155",
    color: "#f8fafc",
    padding: "2px 8px",
    borderRadius: "4px",
    fontSize: "10px",
    fontWeight: 700,
  },
  verifiedTag: {
    backgroundColor: "#065f46",
    color: "#34d399",
    padding: "2px 8px",
    borderRadius: "4px",
    fontSize: "10px",
    fontWeight: 800,
  },
  reporterStrip: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    backgroundColor: "#1e293b",
    padding: "8px 12px",
    borderRadius: "6px",
    border: "1px solid #334155",
  },
  reporterName: {
    display: "block",
    fontSize: "13px",
    fontWeight: 700,
    color: "#f8fafc",
  },
  reporterSub: {
    fontSize: "11px",
    color: "#94a3b8",
    display: "flex",
    alignItems: "center",
    gap: "4px",
  },
  mediaRow: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "8px",
  },
  mediaTile: {
    height: "90px",
    backgroundColor: "#1e293b",
    borderRadius: "6px",
    border: "1px solid #334155",
    overflow: "hidden",
    cursor: "pointer",
    position: "relative",
  },
  tileImg: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
  },
  noMediaText: {
    height: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    color: "#94a3b8",
    fontSize: "10px",
    fontWeight: 700,
    gap: "4px",
  },
  playOverlay: {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    opacity: 0.8,
  },
  locationBox: {
    display: "flex",
    flexDirection: "column",
    gap: "6px",
  },
  addressText: {
    fontSize: "12px",
    color: "#cbd5e1",
    margin: 0,
    fontWeight: 600,
    display: "flex",
    alignItems: "center",
    gap: "4px",
  },
  miniMapContainer: {
    height: "80px",
    borderRadius: "6px",
    overflow: "hidden",
    position: "relative",
    cursor: "pointer",
    border: "1px solid #334155",
  },
  mapHoverTag: {
    position: "absolute",
    bottom: "4px",
    right: "4px",
    backgroundColor: "rgba(8, 12, 20, 0.85)",
    color: "#38bdf8",
    padding: "2px 6px",
    borderRadius: "4px",
    fontSize: "9px",
    fontWeight: 800,
  },
  dispatchBox: {
    backgroundColor: "#1e1b4b",
    border: "1px solid #4338ca",
    padding: "8px 10px",
    borderRadius: "6px",
    display: "flex",
    flexDirection: "column",
    gap: "4px",
  },
  dispatchLabel: {
    fontSize: "10px",
    color: "#a5b4fc",
    fontWeight: 800,
  },
  dispatchSelect: {
    backgroundColor: "#0f172a",
    border: "1px solid #4338ca",
    color: "#f8fafc",
    padding: "6px",
    borderRadius: "4px",
    fontSize: "12px",
    outline: "none",
  },
  actionRow: {
    display: "flex",
    gap: "8px",
    marginTop: "auto",
  },
  deployBtn: {
    flex: 2,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "6px",
    padding: "8px",
    backgroundColor: "#38bdf8",
    color: "#080c14",
    border: "none",
    borderRadius: "6px",
    fontSize: "12px",
    fontWeight: 800,
    cursor: "pointer",
  },
  rejectBtn: {
    flex: 1,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "6px",
    padding: "8px",
    backgroundColor: "#ef4444",
    color: "#ffffff",
    border: "none",
    borderRadius: "6px",
    fontSize: "12px",
    fontWeight: 800,
    cursor: "pointer",
  },
  modalBackdrop: {
    position: "fixed",
    inset: 0,
    backgroundColor: "rgba(8, 12, 20, 0.9)",
    zIndex: 9999,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    padding: "20px",
  },
  modalWindow: {
    width: "100%",
    maxWidth: "800px",
    backgroundColor: "#0f172a",
    border: "1px solid #334155",
    borderRadius: "8px",
    overflow: "hidden",
  },
  modalHead: {
    padding: "12px 16px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    borderBottom: "1px solid #334155",
  },
  closeBtn: {
    backgroundColor: "transparent",
    border: "none",
    color: "#f8fafc",
    cursor: "pointer",
  },
  closeFloatBtn: {
    position: "absolute",
    top: "-10px",
    right: "-10px",
    backgroundColor: "#ef4444",
    color: "#fff",
    border: "none",
    width: "32px",
    height: "32px",
    borderRadius: "50%",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
};