export const pendingUsersStyle = {
  container: {
    display: "flex",
    minHeight: "100vh",
    backgroundColor: "#0b0f19",
    color: "#f8fafc",
    fontFamily: "'Inter', sans-serif",
  },
  main: {
    flex: 1,
    padding: "32px",
    marginLeft: "260px",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "28px",
    paddingBottom: "20px",
    borderBottom: "1px solid #1e293b",
  },
  headerTitleGroup: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
  },
  statusDot: {
    width: "12px",
    height: "12px",
    borderRadius: "50%",
    backgroundColor: "#38bdf8",
    boxShadow: "0 0 12px #38bdf8",
  },
  title: {
    fontSize: "28px",
    fontWeight: "900",
    letterSpacing: "-0.5px",
    color: "#ffffff",
    margin: 0,
  },
  subtitle: {
    color: "#94a3b8",
    fontSize: "14px",
    margin: "6px 0 0 24px",
    fontWeight: "500",
  },
  headerActions: {
    display: "flex",
    gap: "12px",
  },
  btnSecondary: {
    backgroundColor: "#1e293b",
    color: "#f8fafc",
    padding: "10px 16px",
    borderRadius: "10px",
    border: "1px solid #334155",
    cursor: "pointer",
    fontWeight: "700",
    fontSize: "13px",
  },
  btnBatchApprove: (isDisabled) => ({
    backgroundColor: "#10b981",
    color: "#0f172a",
    padding: "10px 18px",
    borderRadius: "10px",
    border: "none",
    cursor: isDisabled ? "not-allowed" : "pointer",
    fontWeight: "900",
    fontSize: "13px",
    display: "flex",
    alignItems: "center",
    gap: "8px",
    opacity: isDisabled ? 0.5 : 1,
  }),
  emptyState: {
    textAlign: "center",
    padding: "80px 20px",
    backgroundColor: "#1e293b",
    borderRadius: "20px",
    border: "1px dashed #334155",
    color: "#94a3b8",
  },
  cardsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(360px, 1fr))",
    gap: "24px",
  },
  card: (isSelected) => ({
    backgroundColor: "#1e293b",
    border: isSelected ? "2px solid #10b981" : "1px solid #334155",
    borderRadius: "20px",
    overflow: "hidden",
    boxShadow: "0 10px 25px -5px rgba(0, 0, 0, 0.3)",
    display: "flex",
    flexDirection: "column",
    position: "relative",
  }),
  cardHeaderStrip: {
    backgroundColor: "rgba(56, 189, 248, 0.1)",
    padding: "14px 20px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    borderBottom: "1px solid rgba(255, 255, 255, 0.05)",
  },
  cardHeaderUser: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
  },
  userName: {
    fontWeight: "800",
    fontSize: "15px",
    color: "#f8fafc",
  },
  pendingBadge: {
    fontSize: "11px",
    fontWeight: "800",
    backgroundColor: "#0f172a",
    color: "#38bdf8",
    padding: "4px 10px",
    borderRadius: "8px",
    border: "1px solid #334155",
  },
  cardBody: {
    padding: "20px",
    flex: 1,
    display: "flex",
    flexDirection: "column",
  },
  detailsBox: {
    backgroundColor: "#0f172a",
    padding: "14px",
    borderRadius: "14px",
    border: "1px solid #334155",
    marginBottom: "16px",
    display: "grid",
    gap: "8px",
  },
  detailRow: {
    display: "flex",
    justifyContent: "space-between",
    fontSize: "12px",
  },
  detailLabel: {
    color: "#94a3b8",
    fontWeight: "700",
  },
  detailValue: {
    color: "#f8fafc",
    fontWeight: "600",
    textAlign: "right",
  },
  imageGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "10px",
    marginBottom: "20px",
  },
  imageThumb: {
    height: "110px",
    borderRadius: "12px",
    overflow: "hidden",
    border: "1px solid #334155",
    position: "relative",
    cursor: "zoom-in",
    backgroundColor: "#0f172a",
  },
  imgCover: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
  },
  imageLabel: {
    position: "absolute",
    bottom: "6px",
    left: "6px",
    backgroundColor: "rgba(15, 23, 42, 0.8)",
    color: "#f8fafc",
    padding: "2px 6px",
    borderRadius: "4px",
    fontSize: "9px",
    fontWeight: "800",
  },
  cardActionGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "10px",
    marginTop: "auto",
  },
  btnReject: {
    backgroundColor: "#ef4444",
    color: "white",
    border: "none",
    padding: "10px",
    borderRadius: "10px",
    fontWeight: "800",
    fontSize: "12px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "6px",
  },
  btnApprove: {
    backgroundColor: "#10b981",
    color: "#0f172a",
    border: "none",
    padding: "10px",
    borderRadius: "10px",
    fontWeight: "900",
    fontSize: "12px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "6px",
  },
  modalBackdrop: {
    position: "fixed",
    inset: 0,
    backgroundColor: "rgba(11, 15, 25, 0.95)",
    zIndex: 9999,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    padding: "24px",
    backdropFilter: "blur(10px)",
  },
  rejectionModalCard: {
    backgroundColor: "#1e293b",
    borderRadius: "20px",
    width: "100%",
    maxWidth: "460px",
    padding: "28px",
    border: "1px solid #334155",
  },
  rejectionHeader: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    marginBottom: "16px",
  },
  textarea: {
    width: "100%",
    height: "100px",
    padding: "12px",
    borderRadius: "10px",
    border: "1px solid #334155",
    backgroundColor: "#0f172a",
    color: "#f8fafc",
    fontSize: "13px",
    marginBottom: "20px",
    outline: "none",
    boxSizing: "border-box",
  },
  modalActionRow: {
    display: "flex",
    gap: "10px",
  },
  btnModalCancel: {
    flex: 1,
    padding: "10px",
    borderRadius: "10px",
    border: "1px solid #334155",
    backgroundColor: "#0f172a",
    color: "#94a3b8",
    fontWeight: "700",
    cursor: "pointer",
  },
  btnModalConfirmReject: {
    flex: 1,
    padding: "10px",
    borderRadius: "10px",
    border: "none",
    backgroundColor: "#ef4444",
    color: "white",
    fontWeight: "800",
    cursor: "pointer",
  },
  previewModalCard: {
    width: "min(1000px, 95vw)",
    maxHeight: "90vh",
    overflow: "auto",
    backgroundColor: "#1e293b",
    borderRadius: "24px",
    border: "1px solid #334155",
    padding: "28px",
  },
  previewHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: "20px",
  },
  btnCloseIcon: {
    backgroundColor: "#0f172a",
    border: "1px solid #334155",
    color: "#94a3b8",
    width: "36px",
    height: "36px",
    borderRadius: "10px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  previewPhotoGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "16px",
    marginBottom: "20px",
  },
  photoBox: {
    backgroundColor: "#0f172a",
    padding: "12px",
    borderRadius: "16px",
    border: "1px solid #334155",
  },
  photoBoxLabel: {
    fontSize: "11px",
    fontWeight: "800",
    color: "#38bdf8",
    display: "block",
    marginBottom: "8px",
  },
  previewImg: {
    width: "100%",
    height: "300px",
    objectFit: "cover",
    borderRadius: "10px",
  },
  profileFieldsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(200px, 1fr))",
    gap: "12px",
    backgroundColor: "#0f172a",
    padding: "16px",
    borderRadius: "16px",
    border: "1px solid #334155",
  },
  fieldLabel: {
    fontSize: "10px",
    color: "#94a3b8",
    fontWeight: "800",
    display: "block",
  },
  fieldValue: {
    fontSize: "13px",
    color: "#f8fafc",
    fontWeight: "700",
  },
  overlayBackdrop: {
    position: "fixed",
    inset: 0,
    zIndex: 1200,
    backgroundColor: "rgba(11, 15, 25, 0.8)",
    backdropFilter: "blur(8px)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "24px",
  },
  overlayCard: {
    width: "min(400px, 100%)",
    backgroundColor: "#1e293b",
    borderRadius: "20px",
    padding: "28px",
    border: "1px solid #334155",
    display: "grid",
    justifyItems: "center",
    textAlign: "center",
    gap: "14px",
  },
  spinner: {
    width: "48px",
    height: "48px",
    borderRadius: "50%",
    border: "4px solid #334155",
    borderTopColor: "#10b981",
    animation: "spin 0.9s linear infinite",
  },
};