export const AVAILABLE_MODULES = [
  {
    id: "incidents",
    label: "Incidents Management",
    description: "Manage incoming emergency reports, assign units, and update case statuses.",
  },
  {
    id: "sos",
    label: "SOS Tracking",
    description: "Live spatial tracking of active emergency SOS signals and dispatch telemetry.",
  },
  {
    id: "users",
    label: "User Registration Management",
    description: "Audit and verify civilian account registrations and submitted credentials.",
  },
  {
    id: "reports",
    label: "Data & Reports Analytics",
    description: "Access system analytics, generate telemetry graphs, and export official PDF logs.",
  },
  {
    id: "pins",
    label: "Responder PIN Generation",
    description: "Generate and manage responder registration access PINs for the emergency system.",
  },
];

const glassPanel = {
  backgroundColor: "#ffffff",
  border: "1px solid #d7e5da",
  boxShadow: "0 8px 24px rgba(24, 95, 53, 0.06)",
  borderRadius: "14px",
};

export const rbacStyles = {
  shell: {
    display: "flex",
    minHeight: "100vh",
    background: "radial-gradient(circle at 50% -20%, #ffffff 0%, #f6faf7 80%)",
    color: "#111827",
    fontFamily: "Inter, Arial, sans-serif",
  },
  main: {
    flex: 1,
    padding: "16px 24px 40px",
    marginLeft: "216px",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "32px",
    paddingBottom: "24px",
    borderBottom: "1px solid #dfeae3",
  },
  titleWrapper: {
    display: "flex",
    alignItems: "center",
    gap: "14px",
  },
  titleDot: {
    width: "12px",
    height: "12px",
    borderRadius: "50%",
    backgroundColor: "#06b6d4",
    boxShadow: "0 0 15px rgba(56, 189, 248, 0.8)",
  },
  titleText: {
    fontSize: "clamp(24px, 3vw, 32px)",
    fontWeight: "800",
    letterSpacing: "-0.03em",
    color: "#111111",
    margin: 0,

  },
  subtitle: {
    fontSize: "10px",
    margin: "8px 0 0 0",
    fontWeight: "600",
    color: "#94a3b8",
    textTransform: "uppercase",
    letterSpacing: "3px",
  },
  layoutGrid: {
    display: "grid",
    gridTemplateColumns: "380px 1fr",
    gap: "24px",
  },
  leftPanel: {
    ...glassPanel,
    padding: "20px",
    display: "flex",
    flexDirection: "column",
    gap: "20px",
  },
  leftPanelHeader: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    paddingBottom: "16px",
    borderBottom: "1px solid #dfeae3",
  },
  leftPanelTitle: {
    fontSize: "15px",
    fontWeight: "900",
    color: "#1d7a4d",
    margin: 0,
    textTransform: "uppercase",
    letterSpacing: "0.5px",
  },
  loaderWrapper: {
    display: "flex",
    justifyContent: "center",
    padding: "80px 0",
  },
  emptyListText: {
    textAlign: "center",
    padding: "40px",
    color: "#5f7b69",
    fontSize: "14px",
    fontWeight: "700",
  },
  adminListContainer: {
    display: "flex",
    flexDirection: "column",
    gap: "16px",
  },
  adminCardButton: (isSelected) => ({
    padding: "20px",
    textAlign: "left",
    cursor: "pointer",
    backgroundColor: isSelected ? "#e7f5eb" : "#ffffff",
    border: isSelected ? "1px solid #8bcaa0" : "1px solid #dfeae3",
    borderRadius: "12px",
    transition: "all 0.3s ease",
    outline: "none",
    boxShadow: isSelected ? "0 8px 18px rgba(29, 122, 77, 0.1)" : "none",
  }),
  adminCardName: (isSelected) => ({
    fontWeight: "900",
    color: isSelected ? "#177a4a" : "#111827",
    fontSize: "16px",
    marginBottom: "8px",
  }),
  adminCardEmail: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    color: "#5f7b69",
    fontSize: "14px",
    marginBottom: "16px",
  },
  adminCardFooter: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  positionText: {
    fontSize: "12px",
    color: "#5f7b69",
    fontWeight: "900",
    textTransform: "uppercase",
  },
  moduleCountBadge: (isSelected) => ({
    fontSize: "12px",
    fontWeight: "900",
    backgroundColor: isSelected ? "#1a874f" : "#edf3ee",
    color: isSelected ? "#ffffff" : "#5f7b69",
    padding: "6px 12px",
    borderRadius: "10px",
  }),
  rightPanel: {
    display: "flex",
    flexDirection: "column",
    gap: "24px",
  },
  activeAdminCard: {
    ...glassPanel,
    padding: "24px",
  },
  activeAdminHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    paddingBottom: "18px",
    borderBottom: "1px solid #dfeae3",
    marginBottom: "24px",
  },
  targetAccountLabel: {
    fontSize: "13px",
    fontWeight: "900",
    color: "#1d7a4d",
    textTransform: "uppercase",
    letterSpacing: "1px",
  },
  activeAdminName: {
    margin: "8px 0 0 0",
    fontSize: "28px",
    fontWeight: "900",
    color: "#111827",
  },
  activeAdminSubtext: {
    margin: "8px 0 0 0",
    fontSize: "15px",
    color: "#5f7b69",
    fontWeight: "700",
  },
  actionBtnGroup: {
    display: "flex",
    gap: "16px",
  },
  selectAllBtn: {
    padding: "12px 24px",
    backgroundColor: "#e7f5eb",
    color: "#177a4a",
    border: "1px solid #b8d7c1",
    borderRadius: "10px",
    cursor: "pointer",
    fontWeight: "900",
    fontSize: "14px",
    display: "flex",
    alignItems: "center",
    gap: "10px",
    transition: "all 0.3s",
  },
  clearAllBtn: {
    padding: "12px 24px",
    backgroundColor: "#fff1f2",
    color: "#b91c1c",
    border: "1px solid #f5d6d6",
    borderRadius: "10px",
    cursor: "pointer",
    fontWeight: "900",
    fontSize: "14px",
    display: "flex",
    alignItems: "center",
    gap: "10px",
    transition: "all 0.3s",
  },
  moduleSectionTitle: {
    fontSize: "15px",
    fontWeight: "900",
    color: "#5f7b69",
    marginBottom: "24px",
    textTransform: "uppercase",
    letterSpacing: "1px",
    display: "flex",
    alignItems: "center",
    gap: "12px",
  },
  moduleListContainer: {
    display: "flex",
    flexDirection: "column",
    gap: "20px",
    marginBottom: "40px",
  },
  moduleCard: (hasAccess) => ({
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "16px",
    backgroundColor: hasAccess ? "#f0fbf4" : "#ffffff",
    border: `1px solid ${hasAccess ? "#8bd8ad" : "#dfeae3"}`,
    borderRadius: "14px",
    cursor: "pointer",
    transition: "all 0.3s ease",
    boxShadow: hasAccess ? "0 8px 18px rgba(29, 122, 77, 0.08)" : "none",
  }),
  checkboxInput: {
    width: "24px",
    height: "24px",
    accentColor: "#1a874f",
    cursor: "pointer",
  },
  moduleLabel: {
    fontSize: "17px",
    fontWeight: "900",
    color: "#111827",
  },
  moduleDesc: {
    fontSize: "14px",
    color: "#5f7b69",
    marginTop: "8px",
    lineHeight: "1.6",
  },
  permissionBadge: (hasAccess) => ({
    fontSize: "13px",
    fontWeight: "900",
    padding: "8px 16px",
    borderRadius: "32px",
    backgroundColor: hasAccess ? "#dcfce7" : "#edf3ee",
    color: hasAccess ? "#15803d" : "#5f7b69",
    border: `1px solid ${hasAccess ? "#bbf7d0" : "transparent"}`,
  }),
  saveRulesBtn: (loading) => ({
    width: "100%",
    padding: "16px",
    background: "linear-gradient(135deg, #1a874f 0%, #0f6c3d 100%)",
    color: "white",
    border: "none",
    borderRadius: "10px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "12px",
    fontWeight: "900",
    fontSize: "16px",
    transition: "all 0.3s",
    opacity: loading ? 0.7 : 1,
    boxShadow: "0 8px 18px rgba(24, 95, 53, 0.16)",
  }),
  unselectedPlaceholder: {
    ...glassPanel,
    border: "1px dashed #dfeae3",
    padding: "100px",
    textAlign: "center",
    color: "#5f7b69",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "20px",
    fontWeight: "800",
  },
};
