export const AVAILABLE_MODULES = [
  {
    id: "incidents",
    label: "Incidents Management",
    description: "Manage incoming emergency reports, assign units, and update case statuses.",
  },
  {
    id: "sos",
    label: "SOS Tracking",
    description: "Live spatial tracking of active emergency SOS signals and dispatch telemetry.",
  },
  {
    id: "users",
    label: "User Registration Management",
    description: "Audit and verify civilian account registrations and submitted credentials.",
  },
  {
    id: "reports",
    label: "Data & Reports Analytics",
    description: "Access system analytics, generate telemetry graphs, and export official PDF logs.",
  },
  {
    id: "pins",
    label: "Responder PIN Generation",
    description: "Generate and manage responder registration access PINs for the emergency system.",
  },
];

const glassPanel = {
  backgroundColor: "#ffffff",
  border: "1px solid #e2e8f0",
  boxShadow: "0 1px 2px rgba(0, 0, 0, 0.03)",
  borderRadius: "8px",
};

export const rbacStyles = {
  shell: {
    display: "flex",
    minHeight: "100vh",
    background: "#f8fafc",
    color: "#0f172a",
    fontFamily: "Inter, Arial, sans-serif",
  },
  main: {
    flex: 1,
    padding: "24px 24px 40px",
    marginLeft: "216px",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "24px",
    paddingBottom: "14px",
    borderBottom: "1px solid #e2e8f0",
  },
  titleWrapper: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
  },
  titleDot: {
    width: "8px",
    height: "8px",
    borderRadius: "50%",
    backgroundColor: "#0284c7",
  },
  titleText: {
    fontSize: "20px",
    fontWeight: "600",
    letterSpacing: "-0.02em",
    color: "#0f172a",
    margin: 0,
  },
  subtitle: {
    fontSize: "11px",
    margin: "4px 0 0 0",
    fontWeight: "600",
    color: "#64748b",
    textTransform: "uppercase",
    letterSpacing: "0.04em",
  },
  layoutGrid: {
    display: "grid",
    gridTemplateColumns: "360px 1fr",
    gap: "20px",
  },
  leftPanel: {
    ...glassPanel,
    padding: "16px",
    display: "flex",
    flexDirection: "column",
    gap: "14px",
  },
  leftPanelHeader: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    borderBottom: "1px solid #f1f5f9",
    paddingBottom: "10px",
  },
  leftPanelTitle: {
    fontSize: "14px",
    fontWeight: "600",
    color: "#0f172a",
    margin: 0,
  },
  adminList: {
    display: "flex",
    flexDirection: "column",
    gap: "6px",
    maxHeight: "calc(100vh - 250px)",
    overflowY: "auto",
  },
  adminItem: (isSelected) => ({
    padding: "10px 12px",
    borderRadius: "6px",
    border: isSelected ? "1px solid #15803d" : "1px solid #e2e8f0",
    backgroundColor: isSelected ? "#f0fdf4" : "#ffffff",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: "10px",
    transition: "all 0.15s ease",
  }),
  adminAvatar: {
    width: "32px",
    height: "32px",
    borderRadius: "50%",
    backgroundColor: "#f1f5f9",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#0f172a",
    fontWeight: "600",
    fontSize: "12px",
  },
  adminInfo: {
    flex: 1,
    minWidth: 0,
  },
  adminName: {
    fontSize: "13px",
    fontWeight: "600",
    color: "#0f172a",
    margin: 0,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  adminEmail: {
    fontSize: "11px",
    color: "#64748b",
    margin: 0,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  rightPanel: {
    ...glassPanel,
    padding: "20px",
    display: "flex",
    flexDirection: "column",
    gap: "16px",
  },
  rightPanelHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    borderBottom: "1px solid #f1f5f9",
    paddingBottom: "12px",
  },
  moduleGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(280px, 1fr))",
    gap: "12px",
  },
  moduleCard: (isEnabled) => ({
    padding: "14px",
    borderRadius: "6px",
    border: isEnabled ? "1px solid #dcfce7" : "1px solid #e2e8f0",
    backgroundColor: isEnabled ? "#f0fdf4" : "#ffffff",
    cursor: "pointer",
    display: "flex",
    flexDirection: "column",
    gap: "6px",
    transition: "all 0.15s ease",
  }),
  moduleTitle: {
    fontSize: "13px",
    fontWeight: "600",
    color: "#0f172a",
    margin: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  moduleDesc: {
    fontSize: "11px",
    color: "#64748b",
    margin: 0,
    lineHeight: "1.4",
  },
  saveBtn: {
    padding: "8px 18px",
    backgroundColor: "#15803d",
    color: "#ffffff",
    border: "none",
    borderRadius: "6px",
    fontWeight: "600",
    fontSize: "12px",
    cursor: "pointer",
    transition: "background-color 0.15s ease",
  },
  emptySelection: {
    padding: "40px",
    textAlign: "center",
    color: "#94a3b8",
    fontSize: "13px",
  },
};
