// admin-dashboard/src/themes/rbacStyles.js

export const AVAILABLE_MODULES = [
  {
    id: "incidents",
    label: "Incidents Management",
    description: "Manage incoming emergency reports, assign units, and update case statuses.",
  },
  {
    id: "sos",
    label: "SOS Tracking",
    description: "Live spatial tracking of active emergency SOS signals and dispatch telemetry.",
  },
  {
    id: "users",
    label: "User Registration Management",
    description: "Audit and verify civilian account registrations and submitted credentials.",
  },
  {
    id: "reports",
    label: "Data & Reports Analytics",
    description: "Access system analytics, generate telemetry graphs, and export official PDF logs.",
  },
];

export const rbacStyles = {
  shell: {
    display: "flex",
    minHeight: "100vh",
    backgroundColor: "#0b0f19",
    color: "#f8fafc",
    fontFamily: "'Inter', sans-serif",
  },
  main: {
    flex: 1,
    padding: "32px",
    marginLeft: "260px",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "28px",
    paddingBottom: "20px",
    borderBottom: "1px solid #1e293b",
  },
  titleWrapper: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
  },
  titleDot: {
    width: "12px",
    height: "12px",
    borderRadius: "50%",
    backgroundColor: "#38bdf8",
    boxShadow: "0 0 12px #38bdf8",
  },
  titleText: {
    fontSize: "28px",
    fontWeight: "900",
    letterSpacing: "-0.5px",
    color: "#ffffff",
    margin: 0,
  },
  subtitle: {
    color: "#94a3b8",
    fontSize: "14px",
    margin: "6px 0 0 24px",
    fontWeight: "500",
  },
  layoutGrid: {
    display: "grid",
    gridTemplateColumns: "320px 1fr",
    gap: "24px",
  },
  leftPanel: {
    backgroundColor: "#1e293b",
    borderRadius: "16px",
    border: "1px solid #334155",
    padding: "20px",
    display: "flex",
    flexDirection: "column",
    gap: "16px",
  },
  leftPanelHeader: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    paddingBottom: "12px",
    borderBottom: "1px solid #334155",
  },
  leftPanelTitle: {
    fontSize: "14px",
    fontWeight: "800",
    color: "#f8fafc",
    margin: 0,
    textTransform: "uppercase",
    letterSpacing: "0.5px",
  },
  loaderWrapper: {
    display: "flex",
    justifyContent: "center",
    padding: "40px 0",
  },
  emptyListText: {
    textAlign: "center",
    padding: "20px",
    color: "#64748b",
    fontSize: "13px",
  },
  adminListContainer: {
    display: "flex",
    flexDirection: "column",
    gap: "10px",
  },
  adminCardButton: (isSelected) => ({
    padding: "14px",
    textAlign: "left",
    cursor: "pointer",
    backgroundColor: isSelected ? "rgba(56, 189, 248, 0.1)" : "#0f172a",
    border: isSelected ? "1px solid #38bdf8" : "1px solid #334155",
    borderRadius: "12px",
    transition: "all 0.2s ease",
    outline: "none",
  }),
  adminCardName: (isSelected) => ({
    fontWeight: "800",
    color: isSelected ? "#38bdf8" : "#f8fafc",
    fontSize: "14px",
    marginBottom: "4px",
  }),
  adminCardEmail: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    color: "#94a3b8",
    fontSize: "12px",
    marginBottom: "10px",
  },
  adminCardFooter: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  positionText: {
    fontSize: "11px",
    color: "#64748b",
    fontWeight: "600",
  },
  moduleCountBadge: (isSelected) => ({
    fontSize: "10px",
    fontWeight: "800",
    backgroundColor: isSelected ? "#38bdf8" : "#334155",
    color: isSelected ? "#0f172a" : "#94a3b8",
    padding: "2px 8px",
    borderRadius: "6px",
  }),
  rightPanel: {
    display: "flex",
    flexDirection: "column",
    gap: "20px",
  },
  activeAdminCard: {
    backgroundColor: "#1e293b",
    borderRadius: "16px",
    border: "1px solid #334155",
    padding: "24px",
  },
  activeAdminHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    paddingBottom: "20px",
    borderBottom: "1px solid #334155",
    marginBottom: "24px",
  },
  targetAccountLabel: {
    fontSize: "11px",
    fontWeight: "800",
    color: "#38bdf8",
    textTransform: "uppercase",
  },
  activeAdminName: {
    margin: "4px 0 0 0",
    fontSize: "20px",
    fontWeight: "800",
    color: "#f8fafc",
  },
  activeAdminSubtext: {
    margin: "4px 0 0 0",
    fontSize: "13px",
    color: "#94a3b8",
  },
  actionBtnGroup: {
    display: "flex",
    gap: "10px",
  },
  selectAllBtn: {
    padding: "8px 14px",
    backgroundColor: "#0f172a",
    color: "#38bdf8",
    border: "1px solid #38bdf8",
    borderRadius: "8px",
    cursor: "pointer",
    fontWeight: "700",
    fontSize: "12px",
    display: "flex",
    alignItems: "center",
    gap: "6px",
  },
  clearAllBtn: {
    padding: "8px 14px",
    backgroundColor: "#0f172a",
    color: "#f87171",
    border: "1px solid #ef4444",
    borderRadius: "8px",
    cursor: "pointer",
    fontWeight: "700",
    fontSize: "12px",
    display: "flex",
    alignItems: "center",
    gap: "6px",
  },
  moduleSectionTitle: {
    fontSize: "13px",
    fontWeight: "800",
    color: "#94a3b8",
    marginBottom: "16px",
    textTransform: "uppercase",
    letterSpacing: "0.5px",
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  moduleListContainer: {
    display: "flex",
    flexDirection: "column",
    gap: "12px",
    marginBottom: "28px",
  },
  moduleCard: (hasAccess) => ({
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "16px",
    backgroundColor: hasAccess ? "rgba(16, 185, 129, 0.08)" : "#0f172a",
    border: `1px solid ${hasAccess ? "#10b981" : "#334155"}`,
    borderRadius: "12px",
    cursor: "pointer",
    transition: "all 0.15s ease",
  }),
  checkboxInput: {
    width: "18px",
    height: "18px",
    accentColor: "#10b981",
    cursor: "pointer",
  },
  moduleLabel: {
    fontSize: "14px",
    fontWeight: "800",
    color: "#f8fafc",
  },
  moduleDesc: {
    fontSize: "12px",
    color: "#94a3b8",
    marginTop: "2px",
  },
  permissionBadge: (hasAccess) => ({
    fontSize: "11px",
    fontWeight: "800",
    padding: "4px 10px",
    borderRadius: "6px",
    backgroundColor: hasAccess ? "rgba(16, 185, 129, 0.2)" : "rgba(148, 163, 184, 0.1)",
    color: hasAccess ? "#34d399" : "#94a3b8",
    border: `1px solid ${hasAccess ? "#10b981" : "#475569"}`,
  }),
  saveRulesBtn: (loading) => ({
    width: "100%",
    padding: "12px 20px",
    backgroundColor: "#10b981",
    color: "#0f172a",
    border: "none",
    borderRadius: "10px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
    fontWeight: "900",
    fontSize: "14px",
    transition: "opacity 0.2s",
    opacity: loading ? 0.7 : 1,
  }),
  unselectedPlaceholder: {
    backgroundColor: "#1e293b",
    borderRadius: "16px",
    border: "2px dashed #334155",
    padding: "60px",
    textAlign: "center",
    color: "#94a3b8",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "12px",
  },
};