// src/themes/reportStyles.js

const glassPanel = {
  backgroundColor: "#ffffff",
  border: "1px solid #e2e8f0",
  boxShadow: "0 1px 2px rgba(0, 0, 0, 0.03)",
  borderRadius: "8px",
};

export const reportStyles = {
  shell: {
    display: "flex",
    minHeight: "100vh",
    background: "#f8fafc",
    color: "#0f172a",
    fontFamily: "Inter, Arial, sans-serif",
  },
  main: {
    flex: 1,
    padding: "24px 24px 40px",
    marginLeft: "216px",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-end",
    marginBottom: "20px",
    paddingBottom: "14px",
    borderBottom: "1px solid #e2e8f0",
  },
  headerTitleGroup: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
  },
  statusDot: {
    width: "8px",
    height: "8px",
    borderRadius: "50%",
    backgroundColor: "#15803d",
  },
  title: {
    fontSize: "20px",
    fontWeight: "600",
    letterSpacing: "-0.02em",
    color: "#0f172a",
    margin: 0,
  },
  subtitle: {
    fontSize: "13px",
    margin: "4px 0 0 0",
    fontWeight: "400",
    color: "#64748b",
    textTransform: "none",
    letterSpacing: "0",
  },
  filterBar: {
    ...glassPanel,
    padding: "16px 20px",
    display: "flex",
    alignItems: "center",
    gap: "14px",
    marginBottom: "20px",
  },
  dateInputGroup: {
    display: "flex",
    flexDirection: "column",
    gap: "6px",
    flex: 1,
  },
  dateLabel: {
    fontSize: "11px",
    fontWeight: "600",
    color: "#64748b",
    display: "flex",
    alignItems: "center",
    gap: "6px",
    textTransform: "uppercase",
    letterSpacing: "0.04em",
  },
  dateInput: {
    padding: "8px 12px",
    borderRadius: "6px",
    border: "1px solid #e2e8f0",
    backgroundColor: "#ffffff",
    color: "#0f172a",
    fontSize: "13px",
    fontWeight: "500",
    outline: "none",
  },
  actionColumn: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  generateBtn: {
    width: "100%",
    padding: "10px 16px",
    background: "#15803d",
    color: "#ffffff",
    border: "none",
    borderRadius: "6px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
    fontWeight: "600",
    fontSize: "13px",
    minHeight: "40px",
    transition: "background-color 0.15s ease",
  },
  progressBarTrack: {
    width: "100%",
    height: "6px",
    backgroundColor: "#f1f5f9",
    borderRadius: "3px",
    overflow: "hidden",
  },
  progressBarFill: (progress) => ({
    height: "100%",
    background: "#15803d",
    width: `${progress}%`,
    transition: "width 0.2s ease-in-out",
  }),
  metricsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(4, 1fr)",
    gap: "16px",
    marginBottom: "24px",
  },
  metricCardDefault: {
    ...glassPanel,
    padding: "16px 20px",
  },
  metricCardOngoing: {
    ...glassPanel,
    padding: "16px 20px",
    border: "1px solid #fde68a",
  },
  metricCardResolved: {
    ...glassPanel,
    padding: "16px 20px",
    border: "1px solid #dcfce7",
  },
  metricCardPending: {
    ...glassPanel,
    padding: "16px 20px",
    border: "1px solid #fee2e2",
  },
  metricLabel: (color) => ({
    fontSize: "11px",
    fontWeight: "600",
    color: color || "#64748b",
    textTransform: "uppercase",
    letterSpacing: "0.04em",
  }),
  metricValue: (color) => ({
    margin: "8px 0 0 0",
    fontSize: "28px",
    fontWeight: "600",
    color: color || "#0f172a",
  }),
  sectionHeaderRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "20px",
  },
  sectionTitle: {
    fontSize: "16px",
    fontWeight: "600",
    color: "#0f172a",
    margin: 0,
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  exportPdfBtn: {
    padding: "8px 16px",
    background: "#0f172a",
    color: "white",
    border: "none",
    borderRadius: "6px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: "8px",
    fontWeight: "600",
    fontSize: "12px",
    transition: "background-color 0.15s ease",
  },
  chartRowGrid: {
    display: "grid",
    gridTemplateColumns: "2fr 1fr",
    gap: "20px",
    marginBottom: "20px",
  },
  chartPanel: {
    ...glassPanel,
    padding: "20px",
  },
  chartTitle: {
    margin: "0 0 16px 0",
    fontSize: "14px",
    fontWeight: "600",
    color: "#0f172a",
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  middleChartsGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "20px",
    marginBottom: "20px",
  },
  bottomGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 2fr",
    gap: "20px",
  },
  reporterList: {
    listStyleType: "none",
    padding: 0,
    margin: 0,
  },
  reporterItem: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "10px 0",
    borderBottom: "1px solid #f1f5f9",
  },
  reporterBadge: {
    backgroundColor: "#f0fdf4",
    color: "#15803d",
    padding: "3px 8px",
    borderRadius: "4px",
    fontSize: "11px",
    fontWeight: "600",
    border: "1px solid #dcfce7",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
  },
  th: {
    textAlign: "left",
    padding: "10px 14px",
    fontSize: "11px",
    fontWeight: "600",
    color: "#64748b",
    letterSpacing: "0.04em",
    textTransform: "uppercase",
    borderBottom: "1px solid #e2e8f0",
    backgroundColor: "#f8fafc",
  },
  td: {
    padding: "12px 14px",
    borderBottom: "1px solid #f1f5f9",
    color: "#334155",
    fontSize: "12px",
  },
};
