// src/themes/reportStyles.js

export function getReportStyles(isDark = false) {
  const glassPanel = {
    backgroundColor: isDark ? "#131c2e" : "#ffffff",
    border: isDark ? "1px solid rgba(255, 255, 255, 0.08)" : "1px solid #e2e8f0",
    boxShadow: isDark
      ? "0 4px 20px -2px rgba(0, 0, 0, 0.5)"
      : "0 1px 2px rgba(0, 0, 0, 0.03)",
    borderRadius: "12px",
  };

  return {
    shell: {
      display: "flex",
      minHeight: "100vh",
      background: isDark ? "#090d16" : "#f8fafc",
      color: isDark ? "#f8fafc" : "#0f172a",
      fontFamily: "'Plus Jakarta Sans', sans-serif",
    },
    main: {
      flex: 1,
      padding: "32px 38px",
      marginLeft: "216px",
      minWidth: 0,
      overflowY: "auto",
    },
    header: {
      display: "flex",
      justifyContent: "space-between",
      alignItems: "flex-end",
      marginBottom: "28px",
      flexWrap: "wrap",
      gap: "18px",
    },
    headerTitleGroup: {
      display: "flex",
      alignItems: "center",
      gap: "10px",
    },
    statusDot: {
      width: "10px",
      height: "10px",
      borderRadius: "50%",
      backgroundColor: isDark ? "#4ade80" : "#15803d",
    },
    title: {
      fontSize: "clamp(24px, 3.2vw, 32px)",
      fontWeight: "900",
      letterSpacing: "-0.03em",
      color: isDark ? "#f8fafc" : "#0f172a",
      margin: 0,
    },
    subtitle: {
      fontSize: "14px",
      margin: "6px 0 0 0",
      fontWeight: "500",
      color: isDark ? "#94a3b8" : "#64748b",
    },
    filterBar: {
      ...glassPanel,
      padding: "24px",
      marginBottom: "28px",
      borderTop: isDark ? "4px solid #4ade80" : "4px solid #15803d",
    },
    dateInputGroup: {
      display: "flex",
      flexDirection: "column",
      gap: "6px",
      flex: 1,
    },
    dateLabel: {
      fontSize: "11.5px",
      fontWeight: "800",
      color: isDark ? "#cbd5e1" : "#334155",
      display: "flex",
      alignItems: "center",
      gap: "6px",
      textTransform: "uppercase",
      letterSpacing: "0.03em",
    },
    dateInput: {
      padding: "10px 14px",
      borderRadius: "10px",
      border: isDark ? "1px solid rgba(255, 255, 255, 0.12)" : "1px solid #cbd5e1",
      backgroundColor: isDark ? "#172338" : "#ffffff",
      color: isDark ? "#f8fafc" : "#0f172a",
      fontSize: "13.5px",
      fontWeight: "700",
      outline: "none",
      boxSizing: "border-box",
    },
    actionColumn: {
      flex: 1,
      display: "flex",
      flexDirection: "column",
      gap: "8px",
    },
    generateBtn: {
      width: "100%",
      padding: "11px 18px",
      background: "linear-gradient(135deg, #15803d 0%, #166534 100%)",
      color: "#ffffff",
      border: "none",
      borderRadius: "10px",
      cursor: "pointer",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      gap: "8px",
      fontWeight: "900",
      fontSize: "13.5px",
      boxShadow: "0 4px 14px rgba(21, 128, 61, 0.25)",
      transition: "all 0.15s ease",
    },
    progressBarTrack: {
      width: "100%",
      height: "6px",
      backgroundColor: isDark ? "#1e293b" : "#f1f5f9",
      borderRadius: "999px",
      overflow: "hidden",
    },
    progressBarFill: (progress) => ({
      height: "100%",
      background: "linear-gradient(90deg, #15803d 0%, #22c55e 100%)",
      width: `${progress}%`,
      transition: "width 0.25s ease-out",
    }),
    metricsGrid: {
      display: "grid",
      gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
      gap: "18px",
      marginBottom: "28px",
    },
    metricCardDefault: {
      ...glassPanel,
      padding: "22px 24px",
      borderLeft: isDark ? "6px solid #4ade80" : "6px solid #0f172a",
    },
    metricCardOngoing: {
      ...glassPanel,
      padding: "22px 24px",
      borderLeft: "6px solid #f59e0b",
    },
    metricCardResolved: {
      ...glassPanel,
      padding: "22px 24px",
      borderLeft: "6px solid #15803d",
    },
    metricCardPending: {
      ...glassPanel,
      padding: "22px 24px",
      borderLeft: "6px solid #dc2626",
    },
    metricLabel: (color) => ({
      fontSize: "11.5px",
      fontWeight: "800",
      color: color || (isDark ? "#94a3b8" : "#64748b"),
      textTransform: "uppercase",
      letterSpacing: "0.05em",
      display: "flex",
      alignItems: "center",
      gap: "6px",
    }),
    metricValue: (color) => ({
      margin: "10px 0 0 0",
      fontSize: "38px",
      fontWeight: "900",
      color: color || (isDark ? "#f8fafc" : "#0f172a"),
      letterSpacing: "-0.03em",
    }),
    sectionHeaderRow: {
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: "20px",
    },
    sectionTitle: {
      fontSize: "16px",
      fontWeight: "900",
      color: isDark ? "#f8fafc" : "#0f172a",
      margin: 0,
      display: "flex",
      alignItems: "center",
      gap: "8px",
    },
    exportPdfBtn: {
      display: "inline-flex",
      alignItems: "center",
      gap: "8px",
      padding: "11px 22px",
      borderRadius: "12px",
      border: "none",
      background: "linear-gradient(135deg, #15803d 0%, #166534 100%)",
      color: "#ffffff",
      fontSize: "13.5px",
      fontWeight: "800",
      cursor: "pointer",
      boxShadow: "0 6px 18px rgba(21, 128, 61, 0.28)",
      transition: "all 0.18s ease",
    },
    chartRowGrid: {
      display: "grid",
      gridTemplateColumns: "repeat(auto-fit, minmax(420px, 1fr))",
      gap: "24px",
      marginBottom: "28px",
    },
    chartPanel: {
      ...glassPanel,
      padding: "26px",
    },
    chartTitle: {
      margin: 0,
      fontSize: "16px",
      fontWeight: "900",
      color: isDark ? "#f8fafc" : "#0f172a",
      display: "flex",
      alignItems: "center",
      gap: "8px",
    },
    middleChartsGrid: {
      display: "grid",
      gridTemplateColumns: "repeat(auto-fit, minmax(380px, 1fr))",
      gap: "24px",
      marginBottom: "28px",
    },
    bottomGrid: {
      display: "grid",
      gridTemplateColumns: "1fr 2fr",
      gap: "20px",
    },
    table: {
      width: "100%",
      borderCollapse: "collapse",
    },
    th: {
      textAlign: "left",
      padding: "12px 14px",
      backgroundColor: "#15803d",
      color: "#ffffff",
      fontSize: "12px",
      fontWeight: "800",
      letterSpacing: "0.02em",
    },
    td: {
      padding: "12px 14px",
      borderBottom: isDark ? "1px solid rgba(255, 255, 255, 0.06)" : "1px solid #f1f5f9",
      color: isDark ? "#cbd5e1" : "#334155",
      fontSize: "12.5px",
    },
  };
}

export const reportStyles = getReportStyles(false);
