export const resolvedIncidentDetailsStyles = {
  shell: { display: "flex", minHeight: "100vh", background: "radial-gradient(circle at 80% 0%, #ffffff 0%, #f3f8f5 62%, #eaf2ed 100%)", color: "#18251d", fontFamily: "Inter, Arial, sans-serif" },
  main: { flex: 1, marginLeft: "216px", padding: "24px 32px 42px", maxWidth: "1400px" },
  loading: { minHeight: "80vh", display: "flex", alignItems: "center", justifyContent: "center", gap: "10px", color: "#177a4a", fontWeight: "800" },
  backButton: { display: "inline-flex", alignItems: "center", gap: "7px", border: "1px solid #cfe3d5", borderRadius: "6px", background: "rgba(255,255,255,.8)", color: "#177a4a", cursor: "pointer", padding: "8px 11px", marginBottom: "18px", fontSize: "12px", fontWeight: "800" },
  header: { display: "flex", alignItems: "flex-start", justifyContent: "space-between", borderBottom: "1px solid #cfe3d5", paddingBottom: "18px", marginBottom: "20px" },
  eyebrow: { display: "block", color: "#177a4a", fontSize: "10px", fontWeight: "800", letterSpacing: "1px", textTransform: "uppercase", marginBottom: "5px" },
  title: { margin: 0, color: "#10251a", fontSize: "20px", fontWeight: "900" },
  subtitle: { margin: "6px 0 0", color: "#71897a", fontSize: "15px" },
  status: { padding: "6px 11px", borderRadius: "999px", background: "#dcfce7", color: "#15803d", fontSize: "11px", fontWeight: "900", textTransform: "uppercase" },
  grid: { display: "grid", gridTemplateColumns: "minmax(0, 1.55fr) minmax(270px, .85fr)", gap: "18px", alignItems: "start" },
  column: { display: "grid", gap: "18px" },
  panel: { background: "#ffffff", border: "1px solid #cfe3d5", borderTop: "3px solid #18864b", borderRadius: "10px", padding: "18px", boxShadow: "0 12px 28px rgba(24,95,53,.07)" },
  panelTitle: { display: "flex", alignItems: "center", gap: "7px", margin: 0, color: "#18251d", fontSize: "14px", fontWeight: "900" },
  panelHeader: { display: "flex", justifyContent: "space-between", gap: "12px", alignItems: "center", borderBottom: "1px solid #edf3ee", paddingBottom: "11px", marginBottom: "15px" },
  metadata: { display: "grid", gridTemplateColumns: "repeat(2, minmax(0, 1fr))", gap: "16px 22px" },
  label: { display: "block", width: "fit-content", background: "#e7f5eb", borderRadius: "3px", padding: "3px 6px", color: "#177a4a", fontSize: "11px", fontWeight: "800", lineHeight: "1.2", marginBottom: "5px" },
  value: { display: "block", minWidth: 0, color: "#18251d", fontSize: "13px", fontWeight: "400", lineHeight: "1.45", overflowWrap: "anywhere", wordBreak: "break-word" },
  description: { margin: "16px 0 0", padding: "12px", background: "#f6faf7", border: "1px solid #dfeae3", borderRadius: "6px", color: "#53645a", fontSize: "13px", lineHeight: "1.6", whiteSpace: "pre-wrap" },
  reporter: { display: "flex", alignItems: "center", gap: "12px", paddingBottom: "14px", borderBottom: "1px solid #dfeae3" },
  avatar: { width: "44px", height: "44px", borderRadius: "8px", background: "#dce9ff", color: "#315ea8", display: "flex", alignItems: "center", justifyContent: "center", fontWeight: "900", overflow: "hidden" },
  avatarImage: { width: "100%", height: "100%", objectFit: "cover" },
  reporterName: { display: "block", minWidth: 0, fontSize: "14px", fontWeight: "400", lineHeight: "1.4", color: "#18251d", overflowWrap: "anywhere" },
  muted: { display: "block", marginTop: "3px", color: "#71897a", fontSize: "12px" },
  contactList: { display: "grid", gap: "11px", marginTop: "14px" },
  mediaGrid: { display: "grid", gridTemplateColumns: "repeat(2, minmax(0, 1fr))", gap: "10px" },
  media: { width: "100%", height: "170px", objectFit: "cover", display: "block", borderRadius: "6px", border: "1px solid #dfeae3", background: "#edf3ee" },
  mediaButton: { display: "block", width: "100%", padding: 0, border: 0, background: "transparent", cursor: "zoom-in" },
  mediaLabel: { display: "block", marginBottom: "6px", color: "#71897a", fontSize: "11px", fontWeight: "800" },
  empty: { minHeight: "170px", display: "flex", alignItems: "center", justifyContent: "center", color: "#71897a", background: "#f6faf7", border: "1px dashed #cfe3d5", borderRadius: "6px", fontSize: "12px" },
  dispatch: { display: "grid", gridTemplateColumns: "minmax(0, 1fr) auto", gap: "10px", alignItems: "center", padding: "11px 12px", background: "#f6faf7", border: "1px solid #dfeae3", borderRadius: "7px" },
  dispatchName: { display: "block", color: "#177a4a", fontSize: "13px", fontWeight: "800" },
  dispatchMeta: { display: "block", marginTop: "3px", color: "#71897a", fontSize: "11px", lineHeight: "1.4", overflowWrap: "anywhere" },
  dispatchStatus: { color: "#177a4a", fontSize: "10px", fontWeight: "900", textTransform: "uppercase", whiteSpace: "nowrap" },
  map: { width: "100%", height: "235px", border: 0, borderRadius: "6px", background: "#edf3ee" },
  mapLink: { display: "inline-flex", alignItems: "center", gap: "5px", color: "#177a4a", fontSize: "11px", fontWeight: "800", textDecoration: "none" },
  overlay: { position: "fixed", inset: 0, zIndex: 20000, display: "flex", alignItems: "center", justifyContent: "center", padding: "24px", background: "rgba(15,23,42,.74)" },
  preview: { position: "relative", maxWidth: "90vw", maxHeight: "88vh" },
  previewMedia: { maxWidth: "90vw", maxHeight: "88vh", borderRadius: "8px", background: "#ffffff" },
  close: { position: "absolute", top: "-14px", right: "-14px", width: "32px", height: "32px", display: "flex", alignItems: "center", justifyContent: "center", border: "1px solid #dfeae3", borderRadius: "50%", background: "#ffffff", color: "#53645a", cursor: "pointer" },
};
