export const resolvedIncidentDetailsStyles = {
  shell: { display: "flex", minHeight: "100vh", background: "#f8fafc", color: "#0f172a", fontFamily: "Inter, Arial, sans-serif" },
  main: { flex: 1, marginLeft: "216px", padding: "24px 32px 40px", maxWidth: "1400px" },
  loading: { minHeight: "80vh", display: "flex", alignItems: "center", justifyContent: "center", gap: "10px", color: "#15803d", fontWeight: "600" },
  backButton: { display: "inline-flex", alignItems: "center", gap: "6px", border: "1px solid #e2e8f0", borderRadius: "6px", background: "#ffffff", color: "#334155", cursor: "pointer", padding: "6px 12px", marginBottom: "16px", fontSize: "12px", fontWeight: "500" },
  header: { display: "flex", alignItems: "flex-start", justifyContent: "space-between", borderBottom: "1px solid #e2e8f0", paddingBottom: "16px", marginBottom: "20px" },
  eyebrow: { display: "block", color: "#15803d", fontSize: "10px", fontWeight: "600", letterSpacing: "0.04em", textTransform: "uppercase", marginBottom: "4px" },
  title: { margin: 0, color: "#0f172a", fontSize: "20px", fontWeight: "600", letterSpacing: "-0.02em" },
  subtitle: { margin: "4px 0 0", color: "#64748b", fontSize: "13px" },
  status: { padding: "4px 10px", borderRadius: "6px", background: "#f0fdf4", color: "#15803d", border: "1px solid #dcfce7", fontSize: "11px", fontWeight: "600", textTransform: "uppercase" },
  grid: { display: "grid", gridTemplateColumns: "minmax(0, 1.55fr) minmax(270px, .85fr)", gap: "16px", alignItems: "start" },
  column: { display: "grid", gap: "16px" },
  panel: { background: "#ffffff", border: "1px solid #e2e8f0", borderRadius: "8px", padding: "16px", boxShadow: "0 1px 2px rgba(0,0,0,.03)" },
  panelTitle: { display: "flex", alignItems: "center", gap: "6px", margin: 0, color: "#0f172a", fontSize: "13px", fontWeight: "600" },
  panelHeader: { display: "flex", justifyContent: "space-between", gap: "10px", alignItems: "center", borderBottom: "1px solid #f1f5f9", paddingBottom: "10px", marginBottom: "12px" },
  metadata: { display: "grid", gridTemplateColumns: "repeat(2, minmax(0, 1fr))", gap: "12px 18px" },
  label: { display: "block", width: "fit-content", background: "#f8fafc", border: "1px solid #e2e8f0", borderRadius: "4px", padding: "2px 6px", color: "#64748b", fontSize: "10px", fontWeight: "600", lineHeight: "1.2", marginBottom: "4px" },
  value: { display: "block", minWidth: 0, color: "#0f172a", fontSize: "12px", fontWeight: "400", lineHeight: "1.4", overflowWrap: "anywhere", wordBreak: "break-word" },
  description: { margin: "12px 0 0", padding: "10px 12px", background: "#f8fafc", border: "1px solid #e2e8f0", borderRadius: "6px", color: "#334155", fontSize: "12px", lineHeight: "1.5", whiteSpace: "pre-wrap" },
  reporter: { display: "flex", alignItems: "center", gap: "10px", paddingBottom: "12px", borderBottom: "1px solid #f1f5f9" },
  avatar: { width: "36px", height: "36px", borderRadius: "6px", background: "#f0fdf4", color: "#15803d", display: "flex", alignItems: "center", justifyContent: "center", fontWeight: "600", fontSize: "13px", overflow: "hidden" },
  avatarImage: { width: "100%", height: "100%", objectFit: "cover" },
  reporterName: { display: "block", minWidth: 0, fontSize: "13px", fontWeight: "600", lineHeight: "1.3", color: "#0f172a", overflowWrap: "anywhere" },
  muted: { display: "block", marginTop: "2px", color: "#64748b", fontSize: "11px" },
  contactList: { display: "grid", gap: "8px", marginTop: "12px" },
  mediaGrid: { display: "grid", gridTemplateColumns: "repeat(2, minmax(0, 1fr))", gap: "10px" },
  media: { width: "100%", height: "150px", objectFit: "cover", display: "block", borderRadius: "6px", border: "1px solid #e2e8f0", background: "#f8fafc" },
  mediaButton: { display: "block", width: "100%", padding: 0, border: 0, background: "transparent", cursor: "zoom-in" },
  mediaLabel: { display: "block", marginBottom: "4px", color: "#64748b", fontSize: "10px", fontWeight: "600" },
  empty: { minHeight: "150px", display: "flex", alignItems: "center", justifyContent: "center", color: "#94a3b8", background: "#f8fafc", border: "1px dashed #cbd5e1", borderRadius: "6px", fontSize: "11px" },
  dispatch: { display: "grid", gridTemplateColumns: "minmax(0, 1fr) auto", gap: "8px", alignItems: "center", padding: "10px 12px", background: "#f8fafc", border: "1px solid #e2e8f0", borderRadius: "6px" },
  dispatchName: { display: "block", color: "#0f172a", fontSize: "12px", fontWeight: "600" },
  dispatchMeta: { display: "block", marginTop: "2px", color: "#64748b", fontSize: "11px", lineHeight: "1.4", overflowWrap: "anywhere" },
  dispatchStatus: { color: "#15803d", fontSize: "10px", fontWeight: "600", textTransform: "uppercase", whiteSpace: "nowrap" },
  map: { width: "100%", height: "200px", border: 0, borderRadius: "6px", background: "#f8fafc" },
  mapLink: { display: "inline-flex", alignItems: "center", gap: "4px", color: "#15803d", fontSize: "11px", fontWeight: "600", textDecoration: "none" },
  overlay: { position: "fixed", inset: 0, zIndex: 20000, display: "flex", alignItems: "center", justifyContent: "center", padding: "24px", background: "rgba(15,23,42,.45)", backdropFilter: "blur(4px)" },
  preview: { position: "relative", maxWidth: "90vw", maxHeight: "88vh" },
  previewMedia: { maxWidth: "90vw", maxHeight: "88vh", borderRadius: "8px", background: "#ffffff", border: "1px solid #e2e8f0" },
  close: { position: "absolute", top: "-12px", right: "-12px", width: "30px", height: "30px", display: "flex", alignItems: "center", justifyContent: "center", border: "1px solid #e2e8f0", borderRadius: "50%", background: "#ffffff", color: "#475569", cursor: "pointer" },
};
