// admin-dashboard/src/sosStyles.js

const glassPanel = {
  backgroundColor: "#ffffff",
  border: "1px solid #d7e5da",
  boxShadow: "0 8px 24px rgba(24, 95, 53, 0.06)",
  borderRadius: "12px",
};

export const sosStyles = {
  shell: {
    display: "flex",
    minHeight: "100vh",
    background: "radial-gradient(circle at 50% -20%, #ffffff 0%, #f6faf7 80%)",
    color: "#111111",
    fontFamily: "Inter, Arial, sans-serif",
  },
  main: {
    flex: 1,
    padding: "28px 24px 40px",
    marginLeft: "216px",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "20px",
    paddingBottom: "14px",
    borderBottom: "1px solid #d7e5da",
  },
  headerTitleGroup: {
    display: "flex",
    alignItems: "center",
    gap: "14px",
  },
  titleDot: {
    width: "12px",
    height: "12px",
    borderRadius: "50%",
    backgroundColor: "#06b6d4",
    boxShadow: "0 0 15px rgba(56, 189, 248, 0.8)",
    animation: "pulseGlowRed 2s infinite",
  },
  pageTitle: {
    fontFamily: '"Didot", "Bodoni MT", "Times New Roman", serif',
    fontSize: "48px",
    fontWeight: "400",
    color: "#111111",
    letterSpacing: "1px",
    margin: 0,
    textTransform: "capitalize",
  },
  subtitle: {
    fontSize: "10px",
    margin: "8px 0 0 0",
    fontWeight: "600",
    color: "#477257",
    textTransform: "none",
    letterSpacing: "0.3px",
  },
  refreshBtn: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    background: "rgba(255, 255, 255, 0.05)",
    color: "#ffffff",
    padding: "12px 24px",
    borderRadius: "32px",
    border: "1px solid rgba(255, 255, 255, 0.1)",
    cursor: "pointer",
    fontWeight: "900",
    fontSize: "13px",
    transition: "all 0.3s ease",
    boxShadow: "0 15px 35px 0 rgba(0, 0, 0, 0.5)",
  },
  emptyState: {
    textAlign: "center",
    padding: "100px 20px",
    ...glassPanel,
    border: "2px dashed rgba(255, 255, 255, 0.1)",
    color: "#94a3b8",
  },
  emptyStateIcon: {
    marginBottom: "20px",
    opacity: 0.8,
    color: "#06b6d4",
    filter: "drop-shadow(0 0 10px rgba(6, 182, 212, 0.5))",
  },
  emptyStateTitle: {
    color: "#ffffff",
    margin: "0 0 10px 0",
    fontWeight: "900",
    fontSize: "18px",
  },
  emptyStateText: {
    margin: 0,
    fontSize: "15px",
    fontWeight: "600",
  },
  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(420px, 1fr))",
    gap: "32px",
  },
  card: {
    ...glassPanel,
    border: "1px solid rgba(239, 68, 68, 0.4)",
    overflow: "hidden",
    display: "flex",
    flexDirection: "column",
    boxShadow: "0 0 30px rgba(239,68,68,0.15)",
  },
  cardBanner: {
    backgroundColor: "rgba(239, 68, 68, 0.15)",
    padding: "20px 24px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    borderBottom: "1px solid rgba(239, 68, 68, 0.2)",
  },
  bannerLabel: {
    fontWeight: "900",
    fontSize: "15px",
    display: "flex",
    alignItems: "center",
    gap: "10px",
    color: "#fca5a5",
    letterSpacing: "0.5px",

  },
  timeBadge: {
    fontSize: "12px",
    fontWeight: "900",
    backgroundColor: "rgba(239, 68, 68, 0.2)",
    color: "#fca5a5",
    padding: "6px 14px",
    borderRadius: "32px",
    border: "1px solid rgba(239, 68, 68, 0.4)",
    boxShadow: "0 15px 35px 0 rgba(0, 0, 0, 0.5)",
  },
  cardBody: {
    padding: "clamp(32px, 5vw, 64px)",
    flex: 1,
    display: "flex",
    flexDirection: "column",
  },
  callerBox: {
    backgroundColor: "rgba(0,0,0,0.2)",
    padding: "20px",
    borderRadius: "32px",
    border: "1px solid rgba(255, 255, 255, 0.08)",
    marginBottom: "20px",
  },
  callerHeader: {
    display: "flex",
    alignItems: "center",
    gap: "14px",
    marginBottom: "12px",
  },
  avatarIcon: {
    width: "48px",
    height: "48px",
    borderRadius: "32px",
    backgroundColor: "rgba(239, 68, 68, 0.15)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#fca5a5",
    border: "1px solid rgba(239,68,68,0.3)",
  },
  callerName: {
    display: "block",
    fontWeight: "900",
    fontSize: "17px",
    color: "#ffffff",
  },
  verifiedBadge: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    color: "#34d399",
    fontSize: "12px",
    fontWeight: "900",
  },
  phoneText: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    fontSize: "14px",
    color: "#cbd5e1",
    fontWeight: "700",
  },
  locationText: {
    margin: "0 0 16px 0",
    fontSize: "15px",
    fontWeight: "800",
    color: "#06b6d4",
    display: "flex",
    alignItems: "flex-start",
    gap: "10px",
    lineHeight: "1.5",
  },
  locationIcon: {
    flexShrink: 0,
    marginTop: "2px",
  },
  assignmentBox: {
    backgroundColor: "rgba(0,0,0,0.2)",
    padding: "20px",
    borderRadius: "32px",
    border: "1px solid rgba(255, 255, 255, 0.08)",
    marginBottom: "20px",
    display: "flex",
    flexDirection: "column",
    gap: "16px",
  },
  statusHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    fontSize: "13px",
  },
  statusLabel: {
    color: "#94a3b8",
    fontWeight: "900",
    textTransform: "uppercase",
    letterSpacing: "0.5px",
  },
  statusBadge: (isAssigned) => ({
    fontWeight: "900",
    color: isAssigned ? "#34d399" : "#fbbf24",
    backgroundColor: isAssigned
      ? "rgba(16, 185, 129, 0.15)"
      : "rgba(245, 158, 11, 0.15)",
    padding: "6px 14px",
    borderRadius: "32px",
    border: `1px solid ${isAssigned ? "rgba(52, 211, 153, 0.3)" : "rgba(251, 191, 36, 0.3)"}`,
    boxShadow: `0 0 15px ${isAssigned ? "rgba(16, 185, 129, 0.1)" : "rgba(245, 158, 11, 0.1)"}`,
  }),
  selectInput: {
    width: "100%",
    padding: "16px",
    borderRadius: "14px",
    border: "1px solid rgba(255, 255, 255, 0.1)",
    backgroundColor: "rgba(15, 23, 42, 0.7)",
    backdropFilter: "blur(40px)",
    WebkitBackdropFilter: "blur(40px)",
    color: "#ffffff",
    fontWeight: "800",
    fontSize: "14px",
    outline: "none",
    boxShadow: "inset 0 2px 4px rgba(0,0,0,0.2)",
  },
  dispatchBtn: (isDisabled) => ({
    width: "100%",
    padding: "18px",
    background: isDisabled ? "rgba(255, 255, 255, 0.05)" : "linear-gradient(135deg, #ef4444 0%, #b91c1c 100%)",
    color: isDisabled ? "#64748b" : "white",
    border: isDisabled ? "1px solid rgba(255, 255, 255, 0.1)" : "none",
    borderRadius: "32px",
    fontWeight: "900",
    fontSize: "15px",
    cursor: isDisabled ? "not-allowed" : "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "10px",
    boxShadow: isDisabled ? "none" : "0 8px 25px rgba(239,68,68,0.4)",
    transition: "all 0.3s",
  }),
  mapPreviewWrapper: {
    height: "200px",
    borderRadius: "32px",
    overflow: "hidden",
    position: "relative",
    cursor: "zoom-in",
    border: "1px solid rgba(255, 255, 255, 0.1)",
    marginBottom: "20px",
    boxShadow: "0 15px 35px 0 rgba(0, 0, 0, 0.5)",
  },
  mapBadge: {
    position: "absolute",
    bottom: "12px",
    right: "12px",
    backgroundColor: "rgba(15, 23, 42, 0.7)",
    backdropFilter: "blur(40px)",
    WebkitBackdropFilter: "blur(40px)",
    
    color: "#06b6d4",
    padding: "8px 16px",
    borderRadius: "32px",
    fontSize: "12px",
    fontWeight: "900",
    display: "flex",
    alignItems: "center",
    gap: "8px",
    border: "1px solid rgba(6, 182, 212, 0.3)",
    zIndex: 10,
  },
  overlayModal: {
    position: "fixed",
    inset: 0,
    backgroundColor: "rgba(2, 6, 23, 0.85)",
    zIndex: 9999,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    padding: "40px",
    
    cursor: "zoom-out",
  },
  modalCard: {
    width: "90vw",
    maxWidth: "1200px",
    ...glassPanel,
    cursor: "default",
  },
  modalHeader: {
    padding: "24px 32px",
    borderBottom: "1px solid rgba(255, 255, 255, 0.05)",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  modalTitle: {
    margin: 0,
    fontSize: "24px",
    fontWeight: "900",
    color: "#fca5a5",
    display: "flex",
    alignItems: "center",
    gap: "12px",

  },
  modalSubtitle: {
    margin: "6px 0 0 0",
    color: "#94a3b8",
    fontSize: "15px",
    fontWeight: "600",
  },
  modalCloseBtn: {
    background: "rgba(255, 255, 255, 0.1)",
    border: "1px solid rgba(255,255,255,0.2)",
    width: "48px",
    height: "48px",
    borderRadius: "32px",
    color: "#ffffff",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    transition: "background 0.3s",
  },
  modalMapCanvas: {
    width: "100%",
    height: "65vh",
    backgroundColor: "rgba(15, 23, 42, 0.7)",
    backdropFilter: "blur(40px)",
    WebkitBackdropFilter: "blur(40px)",
  },
};
