// admin-dashboard/src/sosStyles.js

const glassPanel = {
  backgroundColor: "#ffffff",
  border: "1px solid #dfeae3",
  boxShadow: "0 8px 20px rgba(15, 23, 42, 0.04)",
  borderRadius: "14px",
};

export const sosStyles = {
  shell: {
    display: "flex",
    minHeight: "100vh",
    background: "radial-gradient(circle at 50% -20%, #ffffff 0%, #f6faf7 80%)",
    color: "#111827",
    fontFamily: "Inter, Arial, sans-serif",
  },
  main: {
    flex: 1,
    padding: "28px 24px 40px",
    marginLeft: "216px",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "20px",
    paddingBottom: "14px",
    borderBottom: "1px solid #dfeae3",
  },
  headerTitleGroup: {
    display: "flex",
    alignItems: "center",
    gap: "14px",
  },
  titleDot: {
    width: "12px",
    height: "12px",
    borderRadius: "50%",
    backgroundColor: "#1d7a4d",
    boxShadow: "0 0 15px rgba(29, 122, 77, 0.28)",
    animation: "pulseGlowRed 2s infinite",
  },
  pageTitle: {
    fontFamily: "Inter, Arial, sans-serif",
    fontSize: "clamp(24px, 3vw, 32px)",
    fontWeight: "800",
    color: "#111827",
    letterSpacing: "-0.03em",
    margin: 0,
    textTransform: "uppercase",
    lineHeight: 1,
  },
  subtitle: {
    fontSize: "15px",
    margin: "8px 0 0 0",
    fontWeight: "600",
    color: "#477257",
    textTransform: "none",
    letterSpacing: "0.3px",
  },
  refreshBtn: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    background: "#ffffff",
    color: "#1f3a2f",
    padding: "12px 20px",
    borderRadius: "999px",
    border: "1px solid #dfeae3",
    cursor: "pointer",
    fontWeight: "800",
    fontSize: "13px",
    transition: "all 0.2s ease",
    boxShadow: "0 6px 18px rgba(15, 23, 42, 0.06)",
  },
  emptyState: {
    textAlign: "center",
    padding: "100px 20px",
    ...glassPanel,
    border: "1px dashed #dfeae3",
    color: "#5f7b69",
  },
  loadingState: {
    minHeight: "calc(100vh - 180px)",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: "12px",
    color: "#1d7a4d",
    fontSize: "16px",
    fontWeight: "800",
  },
  emptyStateIcon: {
    marginBottom: "20px",
    opacity: 0.9,
    color: "#1d7a4d",
    filter: "drop-shadow(0 0 8px rgba(29, 122, 77, 0.18))",
  },
  emptyStateTitle: {
    color: "#111827",
    margin: "0 0 10px 0",
    fontWeight: "800",
    fontSize: "18px",
  },
  emptyStateText: {
    margin: 0,
    fontSize: "15px",
    fontWeight: "600",
    color: "#5f7b69",
  },
  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(420px, 1fr))",
    gap: "24px",
  },
  card: {
    ...glassPanel,
    border: "1px solid #f3d7d7",
    overflow: "hidden",
    display: "flex",
    flexDirection: "column",
    boxShadow: "0 8px 24px rgba(239, 68, 68, 0.08)",
  },
  cardBanner: {
    backgroundColor: "#fff5f5",
    padding: "18px 22px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    borderBottom: "1px solid #f5d6d6",
  },
  bannerLabel: {
    fontWeight: "800",
    fontSize: "15px",
    display: "flex",
    alignItems: "center",
    gap: "10px",
    color: "#b91c1c",
    letterSpacing: "0.04em",
  },
  timeBadge: {
    fontSize: "12px",
    fontWeight: "800",
    backgroundColor: "#fff1f2",
    color: "#b91c1c",
    padding: "6px 12px",
    borderRadius: "999px",
    border: "1px solid #f5d6d6",
  },
  cardBody: {
    padding: "18px 20px 20px",
    flex: 1,
    display: "flex",
    flexDirection: "column",
  },
  callerBox: {
    backgroundColor: "#f6faf7",
    padding: "18px",
    borderRadius: "14px",
    border: "1px solid #dfeae3",
    marginBottom: "18px",
  },
  callerHeader: {
    display: "flex",
    alignItems: "center",
    gap: "14px",
    marginBottom: "12px",
  },
  avatarIcon: {
    width: "46px",
    height: "46px",
    borderRadius: "50%",
    backgroundColor: "#fff1f2",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#b91c1c",
    border: "1px solid #f5d6d6",
  },
  callerName: {
    display: "block",
    fontWeight: "800",
    fontSize: "17px",
    color: "#111827",
  },
  verifiedBadge: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    color: "#1d7a4d",
    fontSize: "12px",
    fontWeight: "800",
  },
  phoneText: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    fontSize: "14px",
    color: "#374151",
    fontWeight: "700",
  },
  locationText: {
    margin: "0 0 16px 0",
    fontSize: "15px",
    fontWeight: "700",
    color: "#1d7a4d",
    display: "flex",
    alignItems: "flex-start",
    gap: "10px",
    lineHeight: "1.5",
  },
  locationIcon: {
    flexShrink: 0,
    marginTop: "2px",
  },
  assignmentBox: {
    backgroundColor: "#f6faf7",
    padding: "18px",
    borderRadius: "14px",
    border: "1px solid #dfeae3",
    marginBottom: "18px",
    display: "flex",
    flexDirection: "column",
    gap: "16px",
  },
  statusHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    fontSize: "13px",
  },
  statusLabel: {
    color: "#5f7b69",
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: "0.08em",
  },
  statusBadge: (isAssigned) => ({
    fontWeight: "800",
    color: isAssigned ? "#1d7a4d" : "#b45309",
    backgroundColor: isAssigned ? "#dcfce7" : "#fef3c7",
    padding: "6px 12px",
    borderRadius: "999px",
    border: `1px solid ${isAssigned ? "#bbf7d0" : "#f9d49c"}`,
  }),
  selectInput: {
    width: "100%",
    padding: "15px 16px",
    borderRadius: "10px",
    border: "1px solid #dfeae3",
    backgroundColor: "#fbfdfb",
    color: "#111827",
    fontWeight: "700",
    fontSize: "14px",
    outline: "none",
    boxShadow: "inset 0 1px 2px rgba(15, 23, 42, 0.04)",
  },
  dispatchBtn: (isDisabled) => ({
    width: "100%",
    padding: "16px",
    background: isDisabled ? "linear-gradient(135deg, #dfe9e2 0%, #d2ddd5 100%)" : "linear-gradient(135deg, #ef4444 0%, #b91c1c 100%)",
    color: isDisabled ? "#6d7d73" : "white",
    border: "none",
    borderRadius: "10px",
    fontWeight: "800",
    fontSize: "14px",
    cursor: isDisabled ? "not-allowed" : "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "10px",
    boxShadow: isDisabled ? "none" : "0 8px 18px rgba(239,68,68,0.18)",
    transition: "all 0.2s ease",
    letterSpacing: "0.04em",
  }),
  mapPreviewWrapper: {
    height: "200px",
    borderRadius: "12px",
    overflow: "hidden",
    position: "relative",
    cursor: "zoom-in",
    border: "1px solid #dfeae3",
    marginBottom: "18px",
    boxShadow: "0 8px 18px rgba(15, 23, 42, 0.04)",
  },
  mapBadge: {
    position: "absolute",
    bottom: "12px",
    right: "12px",
    backgroundColor: "rgba(255, 255, 255, 0.92)",
    color: "#177a4a",
    padding: "8px 12px",
    borderRadius: "999px",
    fontSize: "11px",
    fontWeight: "800",
    display: "flex",
    alignItems: "center",
    gap: "8px",
    border: "1px solid #dfeae3",
    zIndex: 10,
  },
  overlayModal: {
    position: "fixed",
    inset: 0,
    backgroundColor: "rgba(15, 23, 42, 0.42)",
    zIndex: 9999,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    padding: "40px",
    cursor: "zoom-out",
  },
  modalCard: {
    width: "90vw",
    maxWidth: "1200px",
    ...glassPanel,
    cursor: "default",
  },
  modalHeader: {
    padding: "20px 24px",
    borderBottom: "1px solid #e2ebdf",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#f6faf7",
  },
  modalTitle: {
    margin: 0,
    fontSize: "22px",
    fontWeight: "800",
    color: "#111827",
    display: "flex",
    alignItems: "center",
    gap: "12px",
  },
  modalSubtitle: {
    margin: "6px 0 0 0",
    color: "#5f7b69",
    fontSize: "14px",
    fontWeight: "600",
  },
  modalCloseBtn: {
    background: "#ffffff",
    border: "1px solid #dfeae3",
    width: "44px",
    height: "44px",
    borderRadius: "10px",
    color: "#1f3a2f",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    transition: "background 0.2s",
  },
  modalMapCanvas: {
    width: "100%",
    height: "65vh",
    backgroundColor: "#f6faf7",
  },
};
