// admin-dashboard/src/sosStyles.js

export const sosStyles = {
  shell: {
    display: "flex",
    minHeight: "100vh",
    backgroundColor: "#0b0f19",
    color: "#f8fafc",
    fontFamily: "'Inter', sans-serif",
  },
  main: {
    flex: 1,
    padding: "32px",
    marginLeft: "260px",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "28px",
    paddingBottom: "20px",
    borderBottom: "1px solid #1e293b",
  },
  headerTitleGroup: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
  },
  titleDot: {
    width: "12px",
    height: "12px",
    borderRadius: "50%",
    backgroundColor: "#ef4444",
    boxShadow: "0 0 12px #ef4444",
  },
  pageTitle: {
    fontSize: "28px",
    fontWeight: "900",
    letterSpacing: "-0.5px",
    color: "#ffffff",
    margin: 0,
  },
  subtitle: {
    color: "#94a3b8",
    fontSize: "14px",
    margin: "6px 0 0 24px",
    fontWeight: "500",
  },
  refreshBtn: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    backgroundColor: "#1e293b",
    color: "#f8fafc",
    padding: "10px 18px",
    borderRadius: "10px",
    border: "1px solid #334155",
    cursor: "pointer",
    fontWeight: "700",
    fontSize: "13px",
    transition: "all 0.2s",
  },
  emptyState: {
    textAlign: "center",
    padding: "80px 20px",
    backgroundColor: "#1e293b",
    borderRadius: "20px",
    border: "1px dashed #334155",
    color: "#94a3b8",
  },
  emptyStateIcon: {
    marginBottom: "16px",
    opacity: 0.8,
  },
  emptyStateTitle: {
    color: "#f8fafc",
    margin: "0 0 8px 0",
  },
  emptyStateText: {
    margin: 0,
    fontSize: "14px",
  },
  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(400px, 1fr))",
    gap: "24px",
  },
  card: {
    backgroundColor: "#1e293b",
    border: "1px solid #ef4444",
    borderRadius: "20px",
    overflow: "hidden",
    boxShadow: "0 10px 25px -5px rgba(239, 68, 68, 0.2)",
    display: "flex",
    flexDirection: "column",
  },
  cardBanner: {
    backgroundColor: "rgba(239, 68, 68, 0.15)",
    padding: "14px 20px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    borderBottom: "1px solid rgba(255, 255, 255, 0.05)",
  },
  bannerLabel: {
    fontWeight: "900",
    fontSize: "14px",
    display: "flex",
    alignItems: "center",
    gap: "8px",
    color: "#f87171",
    letterSpacing: "0.5px",
  },
  timeBadge: {
    fontSize: "11px",
    fontWeight: "800",
    backgroundColor: "rgba(0,0,0,0.4)",
    color: "#fecaca",
    padding: "4px 10px",
    borderRadius: "8px",
    border: "1px solid rgba(239, 68, 68, 0.3)",
  },
  cardBody: {
    padding: "20px",
    flex: 1,
    display: "flex",
    flexDirection: "column",
  },
  callerBox: {
    backgroundColor: "#0f172a",
    padding: "14px",
    borderRadius: "14px",
    border: "1px solid #334155",
    marginBottom: "16px",
  },
  callerHeader: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    marginBottom: "10px",
  },
  avatarIcon: {
    width: "42px",
    height: "42px",
    borderRadius: "12px",
    backgroundColor: "rgba(239, 68, 68, 0.2)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#f87171",
  },
  callerName: {
    display: "block",
    fontWeight: "800",
    fontSize: "16px",
    color: "#f8fafc",
  },
  verifiedBadge: {
    display: "flex",
    alignItems: "center",
    gap: "4px",
    color: "#34d399",
    fontSize: "11px",
    fontWeight: "700",
  },
  phoneText: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    fontSize: "13px",
    color: "#cbd5e1",
    fontWeight: "600",
  },
  locationText: {
    margin: "0 0 12px 0",
    fontSize: "13px",
    fontWeight: "700",
    color: "#60a5fa",
    display: "flex",
    alignItems: "flex-start",
    gap: "8px",
    lineHeight: "1.4",
  },
  locationIcon: {
    flexShrink: 0,
    marginTop: "2px",
  },
  assignmentBox: {
    backgroundColor: "#0f172a",
    padding: "14px",
    borderRadius: "14px",
    border: "1px solid #334155",
    marginBottom: "16px",
    display: "flex",
    flexDirection: "column",
    gap: "10px",
  },
  statusHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    fontSize: "12px",
  },
  statusLabel: {
    color: "#94a3b8",
    fontWeight: "700",
  },
  statusBadge: (isAssigned) => ({
    fontWeight: "900",
    color: isAssigned ? "#34d399" : "#fbbf24",
    backgroundColor: isAssigned
      ? "rgba(52, 211, 153, 0.1)"
      : "rgba(251, 191, 36, 0.1)",
    padding: "4px 8px",
    borderRadius: "6px",
    border: `1px solid ${isAssigned ? "#34d399" : "#fbbf24"}`,
  }),
  selectInput: {
    width: "100%",
    padding: "10px 12px",
    borderRadius: "10px",
    border: "1px solid #334155",
    backgroundColor: "#1e293b",
    color: "#f8fafc",
    fontWeight: "700",
    fontSize: "13px",
    outline: "none",
  },
  dispatchBtn: (isDisabled) => ({
    width: "100%",
    padding: "10px",
    backgroundColor: "#ef4444",
    color: "white",
    border: "none",
    borderRadius: "10px",
    fontWeight: "800",
    fontSize: "12px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "6px",
    opacity: isDisabled ? 0.5 : 1,
  }),
  mapPreviewWrapper: {
    height: "160px",
    borderRadius: "14px",
    overflow: "hidden",
    position: "relative",
    cursor: "zoom-in",
    border: "1px solid #334155",
    marginBottom: "16px",
  },
  mapBadge: {
    position: "absolute",
    bottom: "8px",
    right: "8px",
    backgroundColor: "#0f172a",
    color: "#38bdf8",
    padding: "6px 12px",
    borderRadius: "8px",
    fontSize: "10px",
    fontWeight: "800",
    display: "flex",
    alignItems: "center",
    gap: "6px",
    border: "1px solid #334155",
    zIndex: 10,
  },
  overlayModal: {
    position: "fixed",
    inset: 0,
    backgroundColor: "rgba(11, 15, 25, 0.95)",
    zIndex: 9999,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    padding: "30px",
    backdropFilter: "blur(10px)",
    cursor: "zoom-out",
  },
  modalCard: {
    width: "90vw",
    maxWidth: "1000px",
    backgroundColor: "#1e293b",
    borderRadius: "24px",
    overflow: "hidden",
    border: "1px solid #334155",
    boxShadow: "0 25px 50px -12px rgba(0,0,0,0.7)",
    cursor: "default",
  },
  modalHeader: {
    padding: "20px 28px",
    borderBottom: "1px solid #334155",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  modalTitle: {
    margin: 0,
    fontSize: "18px",
    fontWeight: "900",
    color: "#f87171",
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  modalSubtitle: {
    margin: "4px 0 0 0",
    color: "#94a3b8",
    fontSize: "13px",
  },
  modalCloseBtn: {
    backgroundColor: "#0f172a",
    border: "1px solid #334155",
    width: "36px",
    height: "36px",
    borderRadius: "10px",
    color: "#94a3b8",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  modalMapCanvas: {
    width: "100%",
    height: "60vh",
    backgroundColor: "#0f172a",
  },
};
