export const verifiedUserDetailsStyles = {
  shell: { display: "flex", minHeight: "100vh", background: "radial-gradient(circle at 75% 0%, #ffffff 0%, #f3f9f5 62%, #edf5ef 100%)", color: "#111827", fontFamily: "Inter, Arial, sans-serif" },
  main: { flex: 1, marginLeft: "216px", padding: "26px 38px 42px", maxWidth: "1180px" },
  loadingState: { minHeight: "80vh", display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", gap: "14px", color: "#1d7a4d", fontSize: "16px", fontWeight: "800" },
  backButton: { display: "inline-flex", alignItems: "center", gap: "7px", border: "1px solid #cfe3d5", borderRadius: "6px", background: "rgba(255, 255, 255, 0.75)", color: "#1d7a4d", cursor: "pointer", padding: "8px 11px", marginBottom: "18px", fontSize: "12px", fontWeight: "800", boxShadow: "0 4px 12px rgba(24, 95, 53, 0.06)" },
  header: { display: "flex", alignItems: "flex-start", justifyContent: "space-between", borderBottom: "1px solid #cfe3d5", paddingBottom: "18px", marginBottom: "20px" },
  eyebrow: { display: "block", color: "#1d7a4d", fontSize: "10px", fontWeight: "800", textTransform: "uppercase", letterSpacing: "1px", marginBottom: "5px" },
  title: { margin: 0, color: "#10251a", fontSize: "24px", fontWeight: "900", letterSpacing: "0" },
  subtitle: { margin: "5px 0 0", color: "#7a9a83", fontSize: "12px" },
  statusBadge: (suspended) => ({ padding: "5px 10px", borderRadius: "999px", backgroundColor: suspended ? "#fee2e2" : "#dcfce7", color: suspended ? "#b91c1c" : "#15803d", fontSize: "11px", fontWeight: "800" }),
  contentGrid: { display: "grid", gridTemplateColumns: "220px minmax(0, 1fr)", gap: "16px", alignItems: "stretch" },
  sidebarColumn: { display: "flex", flexDirection: "column", gap: "18px", height: "100%" },
  profilePanel: { background: "#ffffff", border: "1px solid #cfe3d5", borderRadius: "8px", overflow: "hidden", paddingBottom: "12px", boxShadow: "0 8px 20px rgba(24, 95, 53, 0.07)" },
  incidentHistoryPanel: { flex: 1, minHeight: 0 },
  profileImage: { width: "100%", height: "168px", objectFit: "cover", display: "block", background: "#edf3ee", borderBottom: "3px solid #18864b" },
  profileFallback: { width: "100%", height: "168px", display: "flex", alignItems: "center", justifyContent: "center", background: "#edf3ee", color: "#7a9a83" },
  imageButton: { width: "100%", display: "block", padding: 0, border: 0, background: "transparent", cursor: "zoom-in" },
  profileName: { margin: "4px 12px 2px", fontSize: "13px", fontWeight: "700", lineHeight: "1.4", color: "#111827", overflowWrap: "anywhere" },
  profileNameLabel: { display: "block", width: "fit-content", margin: "12px 14px 0", backgroundColor: "#e7f5eb", borderRadius: "3px", padding: "3px 6px", color: "#1d7a4d", fontSize: "11px", fontWeight: "700" },
  profileRole: { margin: "0 14px 14px", color: "#1d7a4d", fontSize: "12px", textTransform: "capitalize" },
  profileMeta: { display: "flex", alignItems: "flex-start", gap: "6px", margin: "8px 12px", color: "#53645a", fontSize: "10px", lineHeight: "1.35" },
  profileMetaLabel: { color: "#1d7a4d", fontWeight: "800" },
  detailsColumn: { display: "flex", flexDirection: "column", gap: "14px" },
  panel: { background: "#ffffff", border: "1px solid #cfe3d5", borderTop: "3px solid #18864b", borderRadius: "8px", padding: "15px", boxShadow: "0 8px 20px rgba(24, 95, 53, 0.06)", display: "flex", flexDirection: "column", minHeight: 0 },
  panelHeader: { borderBottom: "1px solid #edf3ee", paddingBottom: "10px", marginBottom: "12px", flexShrink: 0 },
  panelTitle: { display: "flex", alignItems: "center", gap: "7px", margin: 0, color: "#111827", fontSize: "13px", fontWeight: "900" },
  panelSubtitle: { margin: "5px 0 0", color: "#7a9a83", fontSize: "12px" },
  comparisonGrid: { display: "grid", gridTemplateColumns: "1.05fr .95fr", gap: "14px" },
  infoBlock: { padding: "4px 14px 4px 0", borderRight: "1px solid #dfeae3", display: "grid", gridTemplateColumns: "repeat(2, minmax(0, 1fr))", columnGap: "14px", alignContent: "start" },
  idBlock: { minWidth: 0, padding: "4px 0 4px 2px" },
  blockLabel: { display: "block", gridColumn: "1 / -1", color: "#1d7a4d", fontSize: "11px", fontWeight: "900", letterSpacing: "0.5px", marginBottom: "12px" },
  detail: { minWidth: 0, marginBottom: "11px" },
  detailLabel: { display: "block", width: "fit-content", backgroundColor: "#e7f5eb", borderRadius: "3px", padding: "3px 6px", color: "#1d7a4d", fontSize: "11px", fontWeight: "700", marginBottom: "4px" },
  detailValue: { display: "block", minWidth: 0, color: "#111827", fontSize: "12px", fontWeight: "400", lineHeight: "1.4", overflowWrap: "anywhere", wordBreak: "break-word" },
  mediaHeader: { display: "flex", justifyContent: "space-between", alignItems: "center" },
  mediaAction: { display: "inline-flex", alignItems: "center", gap: "4px", border: 0, background: "transparent", color: "#1d7a4d", cursor: "pointer", fontSize: "9px", fontWeight: "700" },
  idImage: { width: "100%", height: "190px", objectFit: "contain", background: "#f1f7f3", border: "1px solid #dfeae3", borderRadius: "6px" },
  noImage: { minHeight: "190px", display: "flex", alignItems: "center", justifyContent: "center", background: "#f6faf7", color: "#7a9a83", fontSize: "11px", textAlign: "center" },
  previewOverlay: { position: "fixed", inset: 0, zIndex: 21000, display: "flex", alignItems: "center", justifyContent: "center", padding: "24px", backgroundColor: "rgba(15, 23, 42, 0.72)", backdropFilter: "blur(6px)" },
  previewPanel: { position: "relative", width: "min(80vw, 900px)", height: "min(80vh, 700px)", padding: "18px", borderRadius: "8px", backgroundColor: "#ffffff", boxShadow: "0 24px 70px rgba(0, 0, 0, 0.3)" },
  previewClose: { position: "absolute", top: "-14px", right: "-14px", width: "34px", height: "34px", display: "flex", alignItems: "center", justifyContent: "center", border: "1px solid #dfeae3", borderRadius: "50%", backgroundColor: "#ffffff", color: "#53645a", cursor: "pointer" },
  previewImage: { display: "block", width: "100%", height: "100%", objectFit: "contain" },
  statusAction: (suspended) => ({ display: "inline-flex", alignItems: "center", gap: "7px", marginTop: "16px", padding: "11px 16px", border: "none", borderRadius: "6px", backgroundColor: suspended ? "#18864b" : "#ef4444", color: "#ffffff", cursor: "pointer", fontSize: "12px", fontWeight: "800", boxShadow: suspended ? "0 6px 14px rgba(24, 134, 75, 0.2)" : "0 6px 14px rgba(239, 68, 68, 0.18)" }),
  reasonLabel: { display: "block", marginTop: "18px", marginBottom: "7px", color: "#53645a", fontSize: "12px", fontWeight: "800" },
  reasonInput: { width: "100%", minHeight: "75px", resize: "vertical", boxSizing: "border-box", border: "1px solid #dfeae3", borderRadius: "5px", padding: "9px", color: "#111827", fontSize: "13px", outline: "none" },
  incidentTableContainer: { flex: 1, overflowY: "auto", minHeight: 0 },
  incidentTable: { width: "100%", borderCollapse: "collapse", fontSize: "13px" },
  incidentTableRow: { borderBottom: "1px solid #dfeae3" },
  incidentTableHeader: { padding: "12px", backgroundColor: "#f6faf7", color: "#1d7a4d", fontWeight: "800", fontSize: "12px", textAlign: "left" },
  incidentTableCell: { padding: "12px", color: "#111827", fontSize: "13px" },
  incidentStatusBadge: (status) => ({ display: "inline-block", padding: "4px 8px", borderRadius: "4px", backgroundColor: status === "resolved" ? "#dcfce7" : status === "pending" ? "#fef3c7" : "#fee2e2", color: status === "resolved" ? "#15803d" : status === "pending" ? "#92400e" : "#b91c1c", fontSize: "12px", fontWeight: "700", textTransform: "capitalize" }),
};
