// src/verifiedUserStyle.js
const glassPanel = {
  backgroundColor: "#ffffff",
  border: "1px solid #dfeae3",
  boxShadow: "0 8px 20px rgba(15, 23, 42, 0.04)",
  borderRadius: "14px",
};

export const verifiedUserStyle = {
  container: {
    display: "flex",
    minHeight: "100vh",
    background: "radial-gradient(circle at 50% -20%, #ffffff 0%, #f6faf7 80%)",
    color: "#111827",
    fontFamily: "Inter, Arial, sans-serif",
  },
  main: {
    flex: 1,
    padding: "28px 24px 40px",
    marginLeft: "216px",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: "24px",
    marginBottom: "24px",
    paddingBottom: "14px",
    borderBottom: "1px solid #dfeae3",
  },
  headerContent: {
    flex: "1 1 auto",
    minWidth: 0,
  },
  headerTitleGroup: {
    display: "flex",
    alignItems: "center",
    gap: "14px",
  },
  statusDot: {
    width: "12px",
    height: "12px",
    borderRadius: "50%",
    backgroundColor: "#1d7a4d",
    boxShadow: "0 0 15px rgba(29, 122, 77, 0.28)",
  },
  title: {
    fontSize: "clamp(24px, 3vw, 32px)",
    fontWeight: "800",
    letterSpacing: "-0.03em",
    color: "#111111",
    margin: 0,

  },
  subtitle: {
    fontSize: "9px",
    margin: "8px 0 0 0",
    fontWeight: "600",
    color: "#477257",
    textTransform: "none",
    letterSpacing: "0.3px",
    lineHeight: 1.4,
  },
  headerActions: {
    display: "flex",
    gap: "16px",
    alignItems: "center",
    flex: "0 0 auto",
  },
  searchBox: {
    display: "flex",
    alignItems: "center",
    backgroundColor: "#ffffff",
    padding: "12px 16px",
    borderRadius: "10px",
    border: "1px solid #dfeae3",
    width: "300px",
    gap: "10px",
    transition: "all 0.2s ease",
  },
  searchInput: {
    border: "none",
    outline: "none",
    width: "100%",
    fontSize: "15px",
    backgroundColor: "transparent",
    color: "#111827",
    fontWeight: "600",
  },
  btnSuspended: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    padding: "12px 18px",
    borderRadius: "10px",
    border: "1px solid #f5d6d6",
    backgroundColor: "#fff5f5",
    color: "#b91c1c",
    fontWeight: "800",
    fontSize: "14px",
    cursor: "pointer",
    transition: "all 0.3s",
    boxShadow: "0 6px 18px rgba(239, 68, 68, 0.08)",
  },
  errorContainer: {
    textAlign: "center",
    padding: "100px 20px",
    ...glassPanel,
    border: "1px solid #f3d3d3",
    color: "#b91c1c",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "20px",
  },
  btnRetry: {
    padding: "14px 32px",
    background: "linear-gradient(135deg, #1a874f 0%, #0f6c3d 100%)",
    color: "white",
    border: "none",
    borderRadius: "10px",
    fontWeight: "900",
    cursor: "pointer",
    boxShadow: "0 8px 18px rgba(24, 95, 53, 0.16)",
  },
  loadingContainer: {
    textAlign: "center",
    padding: "120px",
    color: "#5f7b69",
    fontSize: "18px",
    fontWeight: "800",
  },
  emptyContainer: {
    textAlign: "center",
    padding: "100px 20px",
    ...glassPanel,
    border: "1px dashed #dfeae3",
    color: "#5f7b69",
  },
  cardsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(380px, 1fr))",
    gap: "24px",
  },
  paginationContainer: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    gap: "24px",
    marginTop: "32px",
  },
  paginationBtn: (isDisabled) => ({
    display: "flex",
    alignItems: "center",
    gap: "10px",
    padding: "14px 24px",
    borderRadius: "32px",
    border: isDisabled ? "1px solid rgba(255, 255, 255, 0.1)" : "1px solid rgba(6, 182, 212, 0.4)",
    backgroundColor: isDisabled ? "rgba(255, 255, 255, 0.05)" : "rgba(56, 189, 248, 0.1)",
    color: isDisabled ? "#64748b" : "#06b6d4",
    cursor: isDisabled ? "not-allowed" : "pointer",
    fontWeight: "900",
    fontSize: "15px",
    opacity: isDisabled ? 0.6 : 1,
    transition: "all 0.3s",
    boxShadow: isDisabled ? "none" : "0 0 20px rgba(56, 189, 248, 0.15)",
  }),
  paginationText: {
    fontSize: "16px",
    fontWeight: "900",
    color: "#cbd5e1",
  },
};
