export const verifiedUserDetailsStyles = {
  shell: { display: "flex", minHeight: "100vh", background: "#f8fafc", color: "#0f172a", fontFamily: "Inter, Arial, sans-serif" },
  main: { flex: 1, marginLeft: "216px", padding: "24px 32px 40px", maxWidth: "1180px" },
  loadingState: { minHeight: "80vh", display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", gap: "12px", color: "#15803d", fontSize: "14px", fontWeight: "600" },
  backButton: { display: "inline-flex", alignItems: "center", gap: "6px", border: "1px solid #e2e8f0", borderRadius: "6px", background: "#ffffff", color: "#334155", cursor: "pointer", padding: "6px 12px", marginBottom: "16px", fontSize: "12px", fontWeight: "500", boxShadow: "0 1px 2px rgba(0, 0, 0, 0.02)" },
  header: { display: "flex", alignItems: "flex-start", justifyContent: "space-between", borderBottom: "1px solid #e2e8f0", paddingBottom: "16px", marginBottom: "20px" },
  eyebrow: { display: "block", color: "#15803d", fontSize: "10px", fontWeight: "600", textTransform: "uppercase", letterSpacing: "0.04em", marginBottom: "4px" },
  title: { margin: 0, color: "#0f172a", fontSize: "20px", fontWeight: "600", letterSpacing: "-0.02em" },
  subtitle: { margin: "4px 0 0", color: "#64748b", fontSize: "12px" },
  statusBadge: (suspended) => ({ padding: "4px 10px", borderRadius: "6px", backgroundColor: suspended ? "#fef2f2" : "#f0fdf4", color: suspended ? "#b91c1c" : "#15803d", border: `1px solid ${suspended ? "#fee2e2" : "#dcfce7"}`, fontSize: "11px", fontWeight: "600" }),
  contentGrid: { display: "grid", gridTemplateColumns: "220px minmax(0, 1fr)", gap: "16px", alignItems: "stretch" },
  sidebarColumn: { display: "flex", flexDirection: "column", gap: "16px", height: "100%" },
  profilePanel: { background: "#ffffff", border: "1px solid #e2e8f0", borderRadius: "8px", overflow: "hidden", paddingBottom: "12px", boxShadow: "0 1px 2px rgba(0, 0, 0, 0.03)" },
  incidentHistoryPanel: { flex: 1, minHeight: 0 },
  profileImage: { width: "100%", height: "168px", objectFit: "cover", display: "block", background: "#f8fafc", borderBottom: "1px solid #e2e8f0" },
  profileFallback: { width: "100%", height: "168px", display: "flex", alignItems: "center", justifyContent: "center", background: "#f8fafc", color: "#94a3b8" },
  imageButton: { width: "100%", display: "block", padding: 0, border: 0, background: "transparent", cursor: "zoom-in" },
  profileName: { margin: "6px 12px 2px", fontSize: "13px", fontWeight: "600", lineHeight: "1.4", color: "#0f172a", overflowWrap: "anywhere" },
  profileNameLabel: { display: "block", width: "fit-content", margin: "10px 12px 0", backgroundColor: "#f0fdf4", borderRadius: "4px", padding: "2px 6px", color: "#15803d", fontSize: "10px", fontWeight: "600" },
  profileRole: { margin: "0 12px 12px", color: "#64748b", fontSize: "11px", textTransform: "capitalize" },
  profileMeta: { display: "flex", alignItems: "flex-start", gap: "6px", margin: "6px 12px", color: "#475569", fontSize: "11px", lineHeight: "1.4" },
  profileMetaLabel: { color: "#0f172a", fontWeight: "600" },
  detailsColumn: { display: "flex", flexDirection: "column", gap: "14px" },
  panel: { background: "#ffffff", border: "1px solid #e2e8f0", borderRadius: "8px", padding: "16px", boxShadow: "0 1px 2px rgba(0, 0, 0, 0.03)", display: "flex", flexDirection: "column", minHeight: 0 },
  panelHeader: { borderBottom: "1px solid #f1f5f9", paddingBottom: "10px", marginBottom: "12px", flexShrink: 0 },
  panelTitle: { display: "flex", alignItems: "center", gap: "6px", margin: 0, color: "#0f172a", fontSize: "13px", fontWeight: "600" },
  panelSubtitle: { margin: "4px 0 0", color: "#64748b", fontSize: "11px" },
  comparisonGrid: { display: "grid", gridTemplateColumns: "1.05fr .95fr", gap: "14px" },
  infoBlock: { padding: "4px 14px 4px 0", borderRight: "1px solid #f1f5f9", display: "grid", gridTemplateColumns: "repeat(2, minmax(0, 1fr))", columnGap: "14px", alignContent: "start" },
  idBlock: { minWidth: 0, padding: "4px 0 4px 2px" },
  blockLabel: { display: "block", gridColumn: "1 / -1", color: "#0f172a", fontSize: "11px", fontWeight: "600", letterSpacing: "0.02em", marginBottom: "10px" },
  detail: { minWidth: 0, marginBottom: "10px" },
  detailLabel: { display: "block", width: "fit-content", backgroundColor: "#f8fafc", border: "1px solid #e2e8f0", borderRadius: "4px", padding: "2px 6px", color: "#64748b", fontSize: "10px", fontWeight: "500", marginBottom: "3px" },
  detailValue: { display: "block", minWidth: 0, color: "#0f172a", fontSize: "12px", fontWeight: "400", lineHeight: "1.4", overflowWrap: "anywhere", wordBreak: "break-word" },
  mediaHeader: { display: "flex", justifyContent: "space-between", alignItems: "center" },
  mediaAction: { display: "inline-flex", alignItems: "center", gap: "4px", border: 0, background: "transparent", color: "#15803d", cursor: "pointer", fontSize: "10px", fontWeight: "600" },
  idImage: { width: "100%", height: "190px", objectFit: "contain", background: "#f8fafc", border: "1px solid #e2e8f0", borderRadius: "6px" },
  noImage: { minHeight: "190px", display: "flex", alignItems: "center", justifyContent: "center", background: "#f8fafc", color: "#94a3b8", fontSize: "11px", textAlign: "center" },
  previewOverlay: { position: "fixed", inset: 0, zIndex: 21000, display: "flex", alignItems: "center", justifyContent: "center", padding: "24px", backgroundColor: "rgba(15, 23, 42, 0.45)", backdropFilter: "blur(4px)" },
  previewPanel: { position: "relative", width: "min(80vw, 900px)", height: "min(80vh, 700px)", padding: "16px", borderRadius: "8px", backgroundColor: "#ffffff", border: "1px solid #e2e8f0", boxShadow: "0 20px 25px -5px rgba(0, 0, 0, 0.1)" },
  previewClose: { position: "absolute", top: "-12px", right: "-12px", width: "30px", height: "30px", display: "flex", alignItems: "center", justifyContent: "center", border: "1px solid #e2e8f0", borderRadius: "50%", backgroundColor: "#ffffff", color: "#64748b", cursor: "pointer" },
  previewImage: { display: "block", width: "100%", height: "100%", objectFit: "contain" },
  statusAction: (suspended) => ({ display: "inline-flex", alignItems: "center", gap: "6px", marginTop: "14px", padding: "9px 14px", border: "none", borderRadius: "6px", backgroundColor: suspended ? "#15803d" : "#b91c1c", color: "#ffffff", cursor: "pointer", fontSize: "12px", fontWeight: "600" }),
  reasonLabel: { display: "block", marginTop: "14px", marginBottom: "6px", color: "#475569", fontSize: "12px", fontWeight: "600" },
  reasonInput: { width: "100%", minHeight: "70px", resize: "vertical", boxSizing: "border-box", border: "1px solid #e2e8f0", borderRadius: "6px", padding: "8px", color: "#0f172a", fontSize: "12px", outline: "none" },
  incidentTableContainer: { flex: 1, overflowY: "auto", minHeight: 0 },
  incidentTable: { width: "100%", borderCollapse: "collapse", fontSize: "12px" },
  incidentTableRow: { borderBottom: "1px solid #f1f5f9" },
  incidentTableHeader: { padding: "10px", backgroundColor: "#f8fafc", color: "#64748b", fontWeight: "600", fontSize: "11px", textAlign: "left", textTransform: "uppercase", letterSpacing: "0.04em", borderBottom: "1px solid #e2e8f0" },
  incidentTableCell: { padding: "10px", color: "#334155", fontSize: "12px" },
  incidentStatusBadge: (status) => ({ display: "inline-block", padding: "3px 8px", borderRadius: "4px", backgroundColor: status === "resolved" ? "#f0fdf4" : status === "pending" ? "#fffbeb" : "#fef2f2", color: status === "resolved" ? "#15803d" : status === "pending" ? "#b45309" : "#b91c1c", border: `1px solid ${status === "resolved" ? "#dcfce7" : status === "pending" ? "#fef3c7" : "#fee2e2"}`, fontSize: "11px", fontWeight: "600", textTransform: "capitalize" }),
};
