export const verifiedUserStyle = {
  container: {
    display: "flex",
    minHeight: "100vh",
    backgroundColor: "#0b0f19",
    color: "#f8fafc",
    fontFamily: "'Inter', sans-serif",
  },
  main: {
    flex: 1,
    padding: "32px",
    marginLeft: "260px",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "28px",
    paddingBottom: "20px",
    borderBottom: "1px solid #1e293b",
  },
  headerTitleGroup: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
  },
  statusDot: {
    width: "12px",
    height: "12px",
    borderRadius: "50%",
    backgroundColor: "#10b981",
    boxShadow: "0 0 12px #10b981",
  },
  title: {
    fontSize: "28px",
    fontWeight: "900",
    letterSpacing: "-0.5px",
    color: "#ffffff",
    margin: 0,
  },
  subtitle: {
    color: "#94a3b8",
    fontSize: "14px",
    margin: "6px 0 0 24px",
    fontWeight: "500",
  },
  headerActions: {
    display: "flex",
    gap: "14px",
    alignItems: "center",
  },
  searchBox: {
    display: "flex",
    alignItems: "center",
    backgroundColor: "#1e293b",
    padding: "10px 16px",
    borderRadius: "12px",
    border: "1px solid #334155",
    width: "280px",
    gap: "10px",
  },
  searchInput: {
    border: "none",
    outline: "none",
    width: "100%",
    fontSize: "13px",
    backgroundColor: "transparent",
    color: "#f8fafc",
    fontWeight: "600",
  },
  btnSuspended: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "10px 18px",
    borderRadius: "12px",
    border: "1px solid #ef4444",
    backgroundColor: "rgba(239, 68, 68, 0.15)",
    color: "#f87171",
    fontWeight: "800",
    fontSize: "13px",
    cursor: "pointer",
    transition: "all 0.2s",
  },
  errorContainer: {
    textAlign: "center",
    padding: "80px 20px",
    backgroundColor: "#1e293b",
    borderRadius: "20px",
    border: "1px solid #ef4444",
    color: "#f87171",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "16px",
  },
  btnRetry: {
    padding: "10px 24px",
    backgroundColor: "#ef4444",
    color: "white",
    border: "none",
    borderRadius: "10px",
    fontWeight: "800",
    cursor: "pointer",
  },
  loadingContainer: {
    textAlign: "center",
    padding: "100px",
    color: "#94a3b8",
    fontSize: "15px",
    fontWeight: "600",
  },
  emptyContainer: {
    textAlign: "center",
    padding: "80px 20px",
    backgroundColor: "#1e293b",
    borderRadius: "20px",
    border: "1px dashed #334155",
    color: "#94a3b8",
  },
  cardsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(320px, 1fr))",
    gap: "24px",
  },
  paginationContainer: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    gap: "20px",
    marginTop: "36px",
  },
  paginationBtn: (isDisabled) => ({
    display: "flex",
    alignItems: "center",
    gap: "6px",
    padding: "10px 18px",
    borderRadius: "10px",
    border: "1px solid #334155",
    backgroundColor: "#1e293b",
    color: "#f8fafc",
    cursor: isDisabled ? "not-allowed" : "pointer",
    fontWeight: "800",
    fontSize: "13px",
    opacity: isDisabled ? 0.5 : 1,
  }),
  paginationText: {
    fontSize: "13px",
    fontWeight: "800",
    color: "#94a3b8",
  },
};
